### ISSUE TITLE
the rotate gesture detector does not work in the sample-ar-model-viewer

### ISSUE THREAD

**Issue by jacquesgiraudel** [SceneView/sceneview-android#100]
Is it supposed to work ? The scale gesture detector works well.

Samsung S8 - Android 9

**Comment by grassydragon** [comment]
Hi!
Yes, we are working on it. I think that the rotation gesture is sometimes confused with the scale gesture. You can find this and other issues here: #91

**Comment by ThomasGorisse** [comment]
Salut,

I can confirm that @grassydragon and @StevenMohr are actively working on it those days.
A coming next release will fix that.
