### ISSUE TITLE
Add performance configuration

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#103]
A performance configuration should allow adjusting limits for the number of hit tests, updates of a node pose and other performance parameters without changing them individually.

For example, there can be two performance configurations:

- **Optimized:** reduced limits for devices with medium performance
- **Unlimited:** disabled limits for devices with high performance

**Comment by ThomasGorisse** [comment]
Filament has a great devices performances dependant resolution system: Dynamic resolution.
We didn't activated it for now... if it's not `true` by default
With a little chance, we can retrieve something from it and adjust a `SceneView.maxHitPerSeconds` and maybe a `SceneView.maxTrackableUpdatePerSeconds`

**Comment by grassydragon** [comment]
Dynamic resolution is enabled in the `Renderer`:
https://github.com/SceneView/sceneview-android/blob/00a08e648773e27f6ae8be514e3be74129e0247d/sceneview/src/main/java/com/google/ar/sceneform/rendering/Renderer.java#L640

**Comment by grassydragon** [comment]
This issue is still relevant. We'll probably integrate the changes into the future releases.
