### ISSUE TITLE
Suggest a physics engine that can replace the old CollisionSystem

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#115]
:bulb: **Idea:**

We would like to replace the old [`CollisionSystem`](https://github.com/SceneView/sceneview-android/blob/996112e1ac321901235c685d211c252d11469fce/sceneview/src/main/java/com/google/ar/sceneform/collision/CollisionSystem.java), that is no longer used for interacting with nodes, with a physics engine for motion and collision detection.

:wrench: **Tasks:**

- Suggest a physics engine for Android (an overview of different physics engines will be great too).
- Propose a way to add it to Sceneview as an optional plugin (adding as little code as possible to the main `sceneview` module and creating a new `sceneview-physics` module or repository that implements synchronization of nodes state between Sceneview and the physics engine).
- Write your findings in this issue! :rocket:

**Comment by RGregat** [comment]
A quick search on Google brought me to **Bullet Physics**. Seem to be very popular since many years. The 3D-Engine **libgdx** has a JNI Wrapper for the 3D-Physics part of Bullet (https://libgdx.com/wiki/extensions/physics/bullet/bullet-physics).
