### ISSUE TITLE
Sceneview visual glitch, multiplying objects in android

### ISSUE THREAD

**Issue by vicode32** [SceneView/sceneview-android#119]
(1)This is link of a  video of third party model viewer app where how model loaded

https://drive.google.com/file/d/1SelSOpWpNfQIGYIquvCqT3yeOHzk_8hJ/view?usp=sharing

(2) This is the link of video where same model is loaded in sceneview in my app

https://drive.google.com/file/d/1sreSZbrUgxSwO9-Nq7uYRjCwT1vL_epQ/view?usp=sharing

(3) I Found this warning in My XML File
  

![WhatsApp Image 2022-07-16 at 2 33 17 PM](https://user-images.githubusercontent.com/84631869/179363766-2976cd5f-007b-4c68-a4b1-1b4db78d9cfb.jpeg)

(4) This warning in sceneview.kt

![WhatsApp Image 2022-07-16 at 3 11 41 PM](https://user-images.githubusercontent.com/84631869/179363791-d6ee89f1-00ec-4b00-980f-36f2cf4bf1ee.jpeg)

Please Help me

**Comment by grassydragon** [comment]
Hi!
Can you try running the application on another device or emulator?
The warning about the layout shouldn't affect the application at runtime.

**Comment by vicode32** [comment]
> Hi! Can you try running the application on another device or emulator? The warning about the layout shouldn't affect the application at runtime.

As you said I try it in another device but there is no improvement at all, 
this is the link of video.

https://user-images.githubusercontent.com/84631869/179397394-8e1a9eeb-5460-4b11-af53-cc76c2ed592b.mp4

**Comment by grassydragon** [comment]
Are there any lights in the scene? On the second device the are no traces left from the car lights. So the only issue is that the scene is completely dark.

**Comment by vicode32** [comment]
> Are there any lights in the scene? On the second device the are no traces left from the car lights. So the only issue is that the scene is completely dark.

Yes only issue is scene is completely dark

**Comment by vicode32** [comment]
This is my code 


(1)MainActivity XML 


![mainActivity](https://user-images.githubusercontent.com/84631869/179399122-b65967ab-3e59-4ca4-b70f-ebb4a2fba208.png)






(2) MainActivity.kt


![MainActivity kt](https://user-images.githubusercontent.com/84631869/179399152-56a97841-39ee-4b16-ab8a-19a9128a6bb5.png)


(3)  MainFragment.xml

![fragment](https://user-images.githubusercontent.com/84631869/179399178-7910d45e-f829-4d4e-9f24-eab53a76df15.png)

(4) MainFragment.kt


![fragment kt(1)](https://user-images.githubusercontent.com/84631869/179399204-7cf80db4-4d23-4a4a-8f4b-1995030ef919.png)

![fragment kt(2)](https://user-images.githubusercontent.com/84631869/179399208-778d0c59-9a2b-4f0a-b0d4-d85e190ca261.png)



(5)  AndroidMainfest.xml
![Screenshot 2022-07-17 181024](https://user-images.githubusercontent.com/84631869/179399228-f9853187-1304-4a5f-b4a9-571a847b0984.png)



(6) build.gradle

![build gradle(1)](https://user-images.githubusercontent.com/84631869/179399319-cf23ff4a-6d34-4cd2-ab32-0545e3e9f86b.png)


![build gradle(2)](https://user-images.githubusercontent.com/84631869/179399325-e814f297-7a47-4782-b5a3-44f43e4706c5.png)



![build gradle(3)](https://user-images.githubusercontent.com/84631869/179399330-19a43b1e-0061-43f7-a417-f26f0bc433f5.png)

**Comment by vicode32** [comment]
Any Updates @grassydragon

**Comment by grassydragon** [comment]
I've just looked at your code. There are no light in the scene since you have commented out the code that sets the environment. The environment is responsible for the ambient light.

**Comment by vicode32** [comment]
> I've just looked at your code. There are no light in the scene since you have commented out the code that sets the environment. The environment is responsible for the ambient light.

Hey it works . But why it is not working in first device , even device running on android 7.

**Comment by vicode32** [comment]
Hey @grassydragon  For first device I set sceneview height from match_parent to 200 dp.
Luckily It is not glitiching that much as before. But it still show some glitch 


https://user-images.githubusercontent.com/84631869/179450197-17090aba-ad5c-4f33-af90-fd0f9168f5a9.mp4

and I also found that if I kept model so small, Glitch gone itself.

**Comment by vicode32** [comment]
There is still some glitch in sceneview in android 7.0
