### ISSUE TITLE
How to animate glb or gltf model using buttton click in sceneview

### ISSUE THREAD

**Issue by vicode32** [SceneView/sceneview-android#123]

**Comment by ThomasGorisse** [comment]
What do you mean by animation?
glTF model animation included within the exported 3D object or `Node` transform animation?
The first one is already there through the `node.animate()` and the second in on its way and was planned in coming next release.
Meanwhile, you also have the `smooth` function to linear interpolate the node transform.

**Comment by vicode32** [comment]
Hey @ThomasGorisse 
Actually I am new to sceneform I want to ask that I have a gltf model having 2 to 3 animation, now how I animate the model in sceneview

**Comment by vicode32** [comment]
I want to animate the model on butttonclick , not autoanimation
so  I tried this
![WhatsApp Image 2022-07-19 at 9 36 16 PM](https://user-images.githubusercontent.com/84631869/179797504-80867de5-e1e1-4ea2-9f53-01ecc5ad21ba.jpeg)

**Comment by vicode32** [comment]
This is My code but I dont know how to animate model through butttonclick
Please help me @ThomasGorisse 

class BlankFragment : Fragment(R.layout.fragment_blank) {
    lateinit var sceneView: SceneView
    lateinit var loadingView: View
    var isLoading = false
        set(value) {
            field = value
            loadingView.isGone = !value
        }
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {

      val v = inflater.inflate(R.layout.fragment_blank,container,false)
        Toast.makeText(context,"View Created",Toast.LENGTH_SHORT).show()

        sceneView = v.findViewById(R.id.sceneView)
        loadingView = v.findViewById(R.id.loadingView)
        isLoading = true
        val modelNode = ModelNode(scale = Scale(0.1f))

        sceneView.addChild(modelNode)
        sceneView.camera.transform = lookAt(
            eye = modelNode.worldPosition.let {
                Position(x = it.x, y = it.y + 0.5f, z = it.z + 2.0f)
            },
            target = modelNode.worldPosition,
            up = Direction(y = 1.0f))


        lifecycleScope.launchWhenCreated{
            modelNode.loadModel(
                context = requireContext(),
                lifecycle = lifecycle,
                autoAnimate = false,
                autoScale = true,
                glbFileLocation = "https://firebasestorage.googleapis.com/v0/b/dream-152c8.appspot.com/o/Dinosaur.glb?alt=media&token=a8bfc191-e7af-4eb9-a548-2d85e42c3c2f",
                centerOrigin = Position(x = 0.0f, y = -1.0f, z = 0.0f),
                onError = { exception -> } ,
                )

          
            


      sceneView.environment = HDRLoader.loadEnvironment(
                context = requireContext(),
                lifecycle = lifecycle,
                hdrFileLocation = "environments/studio_small_09_2k.hdr",
                specularFilter = false,
            )?.apply {
                indirectLight?.intensity = 50_000f
            }
            isLoading = false
            sceneView.camera.smooth(
                lookAt(
                    eye = modelNode.worldPosition.let {
                        Position(x = it.x - 0.4f, y = it.y + 0.4f, z = it.z - 0.6f)
                    },
                    target = modelNode.worldPosition,
                    up = Direction(y = 1.0f)
                ), speed = 0.7f
            )
        }


        return v
    }










    override fun onPause() {
        super.onPause()
        sceneView.onPause(viewLifecycleOwner)
    }

    override fun onResume() {
        super.onResume()
        try {
            sceneView.onResume(viewLifecycleOwner)

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }










}

**Comment by vicode32** [comment]
Hey @ThomasGorisse  I tried this code but nothing worked. 



    class BlankFragment : Fragment(R.layout.fragment_blank) {
    lateinit var sceneView: SceneView
    lateinit var loadingView: View
    var isLoading = false
        set(value) {
            field = value
            loadingView.isGone = !value
        }
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {

      val v = inflater.inflate(R.layout.fragment_blank,container,false)
        Toast.makeText(context,"View Created",Toast.LENGTH_SHORT).show()

        sceneView = v.findViewById(R.id.sceneView)
        loadingView = v.findViewById(R.id.loadingView)
        isLoading = true
        val modelNode = ModelNode(scale = Scale(0.1f))
        sceneView.addChild(modelNode)
        sceneView.camera.transform = lookAt(
            eye = modelNode.worldPosition.let {
                Position(x = it.x, y = it.y + 0.5f, z = it.z + 2.0f)
            },
            target = modelNode.worldPosition,
            up = Direction(y = 1.0f))
        
        lifecycleScope.launchWhenCreated{
            modelNode.loadModel(
                context = requireContext(),
                lifecycle = lifecycle,
                autoAnimate = false,
                autoScale = true,
                glbFileLocation = "https://firebasestorage.googleapis.com/v0/b/dream-152c8.appspot.com/o/Dinosaur.glb?alt=media&token=a8bfc191-e7af-4eb9-a548-2d85e42c3c2f",
                centerOrigin = Position(x = 0.0f, y = -1.0f, z = 0.0f),
                onError = { exception -> } ,
                )
            modelNode.modelInstance?.renderable?.createInstance(modelNode)?.apply {
                animate(true).start()
            }

            sceneView.environment = HDRLoader.loadEnvironment(
                context = requireContext(),
                lifecycle = lifecycle,
                hdrFileLocation = "environments/studio_small_09_2k.hdr",
                specularFilter = false,
            )?.apply {
                indirectLight?.intensity = 50_000f
            }
            isLoading = false
            sceneView.camera.smooth(
                lookAt(
                    eye = modelNode.worldPosition.let {
                        Position(x = it.x - 0.4f, y = it.y + 0.4f, z = it.z - 0.6f)
                    },
                    target = modelNode.worldPosition,
                    up = Direction(y = 1.0f)
                ), speed = 0.7f
            )
        }


        return v
    }

       override fun onPause() {
        super.onPause()
        sceneView.onPause(viewLifecycleOwner)
    }

    override fun onResume() {
        super.onResume()
        try {
            sceneView.onResume(viewLifecycleOwner)

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }










}

**Comment by vicode32** [comment]
Hey @ThomasGorisse 
I tried this code to animate model but not worked 

 modelNode.modelInstance?.renderable?.createInstance(modelNode)?.apply {
                animate(true).start()
            }

**Comment by vicode32** [comment]
And this is my whole code

    class BlankFragment : Fragment(R.layout.fragment_blank) {
    lateinit var sceneView: SceneView
    lateinit var loadingView: View
    var isLoading = false
        set(value) {
            field = value
            loadingView.isGone = !value
        }
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {

      val v = inflater.inflate(R.layout.fragment_blank,container,false)
      Toast.makeText(context,"View Created",Toast.LENGTH_SHORT).show()
        sceneView = v.findViewById(R.id.sceneView)
        loadingView = v.findViewById(R.id.loadingView)
        isLoading = true
        val modelNode = ModelNode(scale = Scale(0.1f))
        sceneView.addChild(modelNode)
        sceneView.camera.transform = lookAt(
            eye = modelNode.worldPosition.let {
                Position(x = it.x, y = it.y + 0.5f, z = it.z + 2.0f)
            },
            target = modelNode.worldPosition,
            up = Direction(y = 1.0f))

        lifecycleScope.launchWhenCreated{
            modelNode.loadModel(
                context = requireContext(),
                lifecycle = lifecycle,
                autoAnimate = false,
                autoScale = true,
                glbFileLocation = "https://firebasestorage.googleapis.com/v0/b/dream-152c8.appspot.com/o/Dinosaur.glb?alt=media&token=a8bfc191-e7af-4eb9-a548-2d85e42c3c2f",
                centerOrigin = Position(x = 0.0f, y = -1.0f, z = 0.0f),
                onError = { exception -> } ,
                )
               
            modelNode.modelInstance?.renderable?.createInstance(modelNode)?.apply {
                animate(true).start()
            }


            sceneView.environment = HDRLoader.loadEnvironment(
                context = requireContext(),
                lifecycle = lifecycle,
                hdrFileLocation = "environments/studio_small_09_2k.hdr",
                specularFilter = false,
            )?.apply {
                indirectLight?.intensity = 50_000f
            }    
            isLoading = false
            sceneView.camera.smooth(
                lookAt(
                    eye = modelNode.worldPosition.let {
                        Position(x = it.x - 0.4f, y = it.y + 0.4f, z = it.z - 0.6f)
                    },
                    target = modelNode.worldPosition,
                    up = Direction(y = 1.0f)
                ), speed = 0.7f
            )
        }


        return v
    }




     override fun onPause() {
        super.onPause()
        sceneView.onPause(viewLifecycleOwner)
    }

    override fun onResume() {
        super.onResume()
        try {
            sceneView.onResume(viewLifecycleOwner)

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }










}

**Comment by vicode32** [comment]
This code works:

modelNode.modelInstance?.animate(0)?.start()
