### ISSUE TITLE
How to use with Geospatial API

### ISSUE THREAD

**Issue by lincollincol** [SceneView/sceneview-android#131]
Hey there! Thank you for this useful library which saves a lot of time when working with ARCore :)

I'm trying to create an android app that shows AR markers by specific location (LatLng). I'd like to create something like [in this video](https://www.youtube.com/watch?v=QZYg9WU5wSA) (from README [AR Geospatial API](https://github.com/SceneView/sceneview-android#ar-geospatial-api)), but with simple `ViewNode` instead of `ArModelNode`.

I also can't place AR model at a specific location with a sample code from README. The model spawns just in front of the current camera position.

Here is my code:
``` kotlin
val earth = binding.sceneView.arSession?.earth ?: return@launchWhenResumed
if (earth.trackingState == TrackingState.TRACKING) {
    val cameraGeospatialPose = earth.cameraGeospatialPose
    val earthAnchor = earth.createAnchor(49.844141, 24.024532, cameraGeospatialPose.altitude, 0f, 0f, 0f, 1f)
    val arModelNode = ArModelNode(
        context = this@MainActivity,
        lifecycle = lifecycle,
        modelFileLocation = "https://sceneview.github.io/assets/models/Gumball.glb"
    )
    arModelNode.anchor = earthAnchor
    binding.sceneView.addChild(arModelNode)
}
```

I would be grateful for your help!

**Comment by lincollincol** [comment]
I also attached a file with the desired result

<img src="https://user-images.githubusercontent.com/32796762/183409138-f4bcd114-5166-4dfc-ac1a-7a28302cd7b5.jpg" width="50%"/>

**Comment by SeyedAlirezaFatemi** [comment]
Hi.
The code you posted looks fine to me. Did you figure out the problem? Does setting `editableTransforms` on `arModelNode` to `EditableTransform.ALL` help?

**Comment by lincollincol** [comment]
It looks like `EditableTransform` doesn't exist in `io.github.sceneview:arsceneview:0.8.0`

![image](https://user-images.githubusercontent.com/32796762/183649450-2ae351d5-3d55-47f5-af32-eed25b84f754.png)

**Comment by SeyedAlirezaFatemi** [comment]
I guess the `editableTransforms` is not important. I think it's a problem with 0.8.0. You can downgrade to 0.7.0 for now until the problems are fixed.

**Comment by lincollincol** [comment]
@SeyedAlirezaFatemi You are right, downgrading to `0.7.0` helped me to fix it. 
I also added `implementation 'com.google.ar:core:1.32.0'` to enable Geospatial API. More here: #109 

Thank you for your help and hope that it will be fixed in the next version :)

**Comment by yhishi** [comment]
@lincollincol 
Does `earth.trackingState` become `TrackingState.TRACKING`?
Always different.

```
binding.arSceneView.apply {
    geospatialEnabled = true

    onArSessionFailed = { _: Exception ->
    
    }
    onArSessionCreated = { arSession ->
        val earth = arSession.earth
        if (earth != null && earth.trackingState == TrackingState.TRACKING) {
            val altitude = earth.cameraGeospatialPose.altitude - 1
            val rotation = Rotation(0f, 0f, 0f)
            val latitude = earth.cameraGeospatialPose.latitude + 0.0004
            val longitude = earth.cameraGeospatialPose.longitude + 0.0004
            earthAnchor = earth.createAnchor(latitude, longitude, altitude, rotation.toFloatArray())

            val arModelNode = ArModelNode(
                context = this@GeoSpatialActivity,
                lifecycle = lifecycle,
                modelFileLocation = "https://sceneview.github.io/assets/models/Gumball.glb"
            )

            arModelNode.anchor = earthAnchor
            binding.arSceneView.addChild(arModelNode)
        }
    }
}
```

**Comment by yhishi** [comment]
I solved ↑.
In `onArSessionCreated`, the trackingState was still PAUSED. When a button is clicked, it is TRACKING.

**Comment by mobile-appz** [comment]
> I solved ↑.
> 
> In `onArSessionCreated`, the trackingState was still PAUSED. When a button is clicked, it is TRACKING.

Hi, is this working with latest Android version? Do you know if there are there any full code samples to implement this please? I'm not seeing much documentation in this repository on implementing geospatial AR. Is it necessary to use the Google geospatial API, which is rate limited, or can I simply use compass and geolocation like before when I was using https://github.com/appoly/ARCore-Location? but it seems to be broken in the latest Android version. Thanks
