### ISSUE TITLE
hi, bro, can i use java to implement all these functions, i am not very proficient in kotlin

### ISSUE THREAD

**Issue by weijiaqi** [SceneView/sceneview-android#133]

**Comment by weijiaqi** [comment]
The tap events were fixed and documented in this pull request: https://github.com/SceneView/sceneview-android/pull/96

**Comment by weijiaqi** [comment]
I can't find the code you changed in the imported library, can you please mark the code in detail how to get the name of the child node of the touch part after loading the glb model, I have to start the sceneview-kotlin code in order to realize this touch operation, Can I also use sceneform-java to get the name of the child node of the touch area?

**Comment by weijiaqi** [comment]
@ThomasGorisse

**Comment by weijiaqi** [comment]
@grassydragon

**Comment by grassydragon** [comment]
Hi!
Take a look at how picking is implemented in SceneView and implement it yourself in Sceneform.
https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L603
