### ISSUE TITLE
ModelNode, set minZoom/maxZoom allowed while zooming in/out camera

### ISSUE THREAD

**Issue by gabrielazwaat** [SceneView/sceneview-android#134]
hello dears, I would like to disable zooming for my 3d model, is there any option to set max scale or disable scale from modelNode,
As well I am still not able to set max rotation angles to the camera manipulator while rotating, I would like the scene to stop rotating after reaching a certain angle from right left top and bottom, is that possible doable, appreciate your help

**Comment by grassydragon** [comment]
Hi!
Scaling can be disabled using this property:
https://github.com/SceneView/sceneview-android/blob/00bae0697efa8fad30c1922def99794e49a7a712/sceneview/src/main/java/io/github/sceneview/node/Node.kt#L311

The minimum and maximum scale can be set using these properties:
https://github.com/SceneView/sceneview-android/blob/00bae0697efa8fad30c1922def99794e49a7a712/sceneview/src/main/java/io/github/sceneview/node/Node.kt#L320

And I see that you've already found the issue about restricting the camera angles #62

**Comment by grassydragon** [comment]
Hi!
Can it be so that the model isn't scaled but the camera is zoomed in and out?

**Comment by gabrielazwaat** [comment]
> Hi! Can it be so that the model isn't scaled but the camera is zoomed in and out?

Hello!
On camera zoom in and out, I want to keep a space between the camera and the 3d model,
currently when zooming too much I am reaching inside the model and passing by it, 
Same for zoom out the model is getting too small and disappearing,
what is required is to let the user zoom the camera in and out to a certain position
 
Thanks

**Comment by grassydragon** [comment]
> what is required is to let the user zoom the camera in and out to a certain position

I think it is currently only possible to extend the `SceneView` class and override the `cameraManipulator` property to set the minimum zoom distance. However, I'm not sure if it is available for modes other than `MAP`.
https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L354
https://github.com/google/filament/blob/eaa86060e2039c3da4031ec71ff9dfea7a4efd72/android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java#L193
