### ISSUE TITLE
Model is loaded fom internet everytime because activity is destroyed 

### ISSUE THREAD

**Issue by Aryan1g** [SceneView/sceneview-android#136]
Because the activity is just destroyed every time, cache strategy is not possible with this library. every time I need to fetch the database for model

Please help me

**Comment by grassydragon** [comment]
Hi!
You should implement downloading and caching the model file on the device storage. Then you can check whether the model has been already downloaded and open the file.

**Comment by Aryan1g** [comment]
Hey there is a lot of model to cache on device storage and in further updates no of model is also increased, so cache gonna too big .

**Comment by Aryan1g** [comment]
> Hi! You should implement downloading and caching the model file on the device storage. Then you can check whether the model has been already downloaded and open the file.

Hey there is a lot of model to cache on device storage and in further updates no of model is also increased, so cache gonna too big .

**Comment by grassydragon** [comment]
You can always restrict the number of models stored in cache.

**Comment by StevenMOG** [comment]
Additionally I'd use the app's cache directory for model caching and let the system (and/or user) decide when to delete the files.

**Comment by Aryan1g** [comment]
> Additionally I'd use the app's cache directory for model caching and let the system (and/or user) decide when to delete the files.

can you tell me what is ideal cache size
