### ISSUE TITLE
Use ArModelNode to load different .glb?

### ISSUE THREAD

**Issue by dulimarta** [SceneView/sceneview-android#137]
Can I use one `ArModelNode()` and call `loadModel()` many times to reuse the same `ArModelNode` to render different 3D models? I could not find the details from the current documentation.

**Comment by grassydragon** [comment]
Hi!
Yes, I think it should work. However, you should destroy the previous model after you change it. See how the model is destroyed based on the lifecycle state: https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/model/GLBLoader.kt#L71
