### ISSUE TITLE
3D Model gets re-rendered after the user moves the 3D object

### ISSUE THREAD

**Issue by ayasser-identity** [SceneView/sceneview-android#138]
Hi I am still new to the whole AR thing and I don't know how this framework actually work but it's great now I am facing a problem that the shape is added over and over again and it's not re-rendered upon
here is the photo of the shape : 
![Screenshot from 2022-08-23 15-26-08](https://user-images.githubusercontent.com/105722255/186169943-4181dd40-7c2e-4fe7-90eb-56c04885ac45.png)
here is the photo of the shape after trying to move it down  and up :
![Screenshot from 2022-08-23 15-25-34](https://user-images.githubusercontent.com/105722255/186170299-d7a87f04-fe06-40cd-b49e-6ef19d472324.png)
 I am doing something wrong I don't know what it is
here is the source code that I wrote  : 
![Screenshot from 2022-08-23 15-29-02](https://user-images.githubusercontent.com/105722255/186170689-f9679d50-17f5-4a05-a033-0e594eaf9569.png)

**Comment by grassydragon** [comment]
Hi!
Does it happen with the sample applications or on a real device? Please insert the code as a highlighted Markdown block next time.

**Comment by ayasser-identity** [comment]
well in a real device something weird screen shot happens : 
![Screenshot_20220823-154820](https://user-images.githubusercontent.com/105722255/186175738-3070a2a7-9a29-4772-9780-931c1fe2e3cb.png)

**Comment by grassydragon** [comment]
Thank you for the report! I'll check that on my Google Pixel 3a.

**Comment by ThomasGorisse** [comment]
Hi.
It could be a surface clearing issue.
Can you try setting an opaque background on the `SceneView`?

**Comment by grassydragon** [comment]
The `sample-model-viewer` application works fine on the latest main branch in my case:

![Model Viewer](https://user-images.githubusercontent.com/35110066/186839573-9c91ab3e-8262-4cf9-95fa-b0255ce27a76.png)

**Comment by nayash** [comment]
> Hi. It could be a surface clearing issue. Can you try setting an opaque background on the `SceneView`?

I have the same issue while rendering a ModelNode on SceneView. I tried white background on SceneView but couldn't see the model at all.

**Comment by lukaloens** [comment]
On Pixel 4a (5G)

![Screenshot_20220920_142203](https://user-images.githubusercontent.com/113993175/191256789-d52b1011-456d-4635-85ac-0fb178d6ea77.png)
