### ISSUE TITLE
Wrong LifeCycle manage when pass onDestroy

### ISSUE THREAD

**Issue by eguizabal98** [SceneView/sceneview-android#139]
If you have a ArSceneView or SceneView in a Fragment with a backStack and you try to go back for example a menu fragment the application crash, maybe is the method that destroy the assets.

`GLBLoader`
```
lifecycle?.observe(onDestroy = {
                // Prevent double destroy in case of manually destroyed
                runCatching { asset.destroy() }
            })
```

with this change the app doesn't crash anymore but i know that is not the optimal solution.

```
lifecycle?.observe(onDestroy = { lifecycleOwnerLoader ->
                // Prevent double destroy in case of manually destroyed
                runCatching {
                    if ((lifecycleOwnerLoader.javaClass).superclass != Fragment::class.java) {
                        asset.destroy()
                    }
                }
            })
```

**Comment by ThomasGorisse** [comment]
Hi,
Your issue might be an "already destroyed" issue.
We don't try catch the `destroy` to help you know that you shouldn't call the destroy manually since it's already handle by `SceneView`.
So the best answer would be "Cool, SceneView well handles the destroy by itself".

**Comment by eschoenawa** [comment]
Putting a fragment on the backstack won't call a fragment's `onDestroy`, just `onStop`. If you navigate back to that fragment it will start again from `onStart`.

Crucially, putting a fragment on the backstack will call
> onPause
onStop
onDestroyView

on that fragment. When the backstack is popped again, then the fragment's lifecycle calls will be
> onCreateView
onActivityCreated
onStart
onResume

At no point `onDestroy` of that fragment is called. Thus, Sceneview won't automatically destroy these assets when the fragment is added to the backstack.
