### ISSUE TITLE
Improper model view for SceneView (3d-only) and inconsistent loaded model sizes for different models

### ISSUE THREAD

**Issue by nayash** [SceneView/sceneview-android#142]
First of thanks for your efforts in building this library. While the setup was easy, I am facing two issues:

1. The SceneView is not loading "glb" models properly (haven't tried other formats). I have tried with 2 freely available models (unable to attach here) but one of them is the famous Avocado [https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF-Binary/Avocado.glb], and both models are successfully loaded on https://modelviewer.dev/editor/ so nothing wrong with the glb files. Here is how the SceneView renders both:

**Avocado**
![Screenshot_20220829-143933_Test App](https://user-images.githubusercontent.com/25876491/187170074-9a6b3a2e-5c48-4173-bdc9-cce0281e6280.jpg)
![Screenshot_20220829-143944_Test App](https://user-images.githubusercontent.com/25876491/187170096-0310302b-852b-4e0e-81cc-9827680953af.jpg)
Above happens when I interact with it to zoom in/out

Code usage:
XML: 
```
<io.github.sceneview.SceneView
        android:id="@+id/sceneView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

```
        val modelNode = ModelNode(
            position = Position(x = 0.0f, y = 0.0f, z = -4.0f),
            rotation = Rotation(y = 90.0f),
            scale = Scale(0.2f) // no change with 0.5f too
        )
        activity?.let {
            modelNode.loadModelAsync(it,
                glbFileLocation = "file:///android_asset/tv.glb", //"https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF-Binary/Avocado.glb",
                onError = { ex -> Log.e("loadError", "$ex") },
                onLoaded = { model -> Log.v("modelLoaded", "$model") })
        }
        binding.sceneView.addChild(
            modelNode
        )
```

**TV**
![Screenshot_20220829-144851_Test App](https://user-images.githubusercontent.com/25876491/187170803-d35b0d45-dd81-43f7-83fd-8b008ae9d179.jpg)

2. In the AR View Avocado appears too small (unable to zoom in/out on the object). On the other hand "tv.glb" appears too big to start with (tried both on same surface). How to control this behaviour? any code examples would help.
![Screenshot_20220829-144555_Test App](https://user-images.githubusercontent.com/25876491/187172055-f97e1e77-2cd5-47a7-913d-47a3ce3a96a3.jpg)

![Screenshot_20220829-144445_Test App](https://user-images.githubusercontent.com/25876491/187172096-7c63d7cc-7c1b-4a87-8d7b-d672538999f5.jpg)

Device Details:
Samsung M51
One UI : 4.1
Android: 12

Please let me know if any other details are needed.

**Comment by nayash** [comment]
hey SceneView team, is it being looked at? any workarounds? I could use some acknowledgments.

**Comment by grassydragon** [comment]
Hi!
For the first problem please see this issue: https://github.com/SceneView/sceneview-android/issues/138
There can be some issues with the currently used version of Filament on your device.
For the second problem use the `scaleToUnits` parameter when loading a model:
https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/samples/ar-model-viewer/src/main/java/io/github/sceneview/sample/armodelviewer/MainActivity.kt#L148
The scale gesture is currently a little bit tricky to execute. Make sure that both fingers are within the model.

**Comment by nayash** [comment]
Also, what gesture is used to rotate the model? (dragging with 2 fingers didn't work)

**Comment by grassydragon** [comment]
You should twist the fingers clockwise or counterclockwise.

**Comment by nayash** [comment]
The first issue is happening even on the sample app "sample-model-viewer" if I comment out the HDR environment loading:

```
lifecycleScope.launchWhenCreated {
            /*sceneView.environment = HDRLoader.loadEnvironment(
                context = requireContext(),
                lifecycle = lifecycle,
                hdrFileLocation = "environments/studio_small_09_2k.hdr",
                specularFilter = false
            )?.apply {
                indirectLight?.intensity = 50_000f
            }*/

            modelNode.loadModelGlb(
                context = requireContext(),
                lifecycle = lifecycle,
                glbFileLocation = "https://sceneview.github.io/assets/models/MaterialSuite.glb",
                scaleToUnits = 2.0f,
                centerOrigin = Position(x = 0.0f, y = 0.0f, z = 0.0f)
            )
            delay(1500)
            isLoading = false
            sceneView.cameraNode.smooth(
                lookAt(
                    eye = modelNode.worldPosition.let {
                        Position(x = it.x - 0.4f, y = it.y + 0.4f, z = it.z - 0.6f)
                    },
                    target = modelNode.worldPosition,
                    up = Direction(y = 1.0f)
                ),
                speed = 0.7f
            )
        }
```

Issue is happening for all the models if HDR env code is commented out. So it's not code issue. It also doesn't seem like Filament version issue because your SceneForm-android library is rendering properly.

![Screenshot_20220912-175045_3D Model Viewer](https://user-images.githubusercontent.com/25876491/189652331-01689a4e-67b8-4bbb-923b-f20a688d3d78.jpg)
