### ISSUE TITLE
VideoNode does not work after upgrading from 0.5.2 to 0.8.0

### ISSUE THREAD

**Issue by dulimarta** [SceneView/sceneview-android#144]
I'd like to upgrade to 0.9.0 but my app depends on showing a video layer. It worked fine with 0.5.2 but now it stopped working.

**Comment by grassydragon** [comment]
Hi!
Thank you for the report! We'll try to address this issue in the next release.

**Comment by Sergiobop** [comment]
Video doesn't work right now because the complete functionality is commented out?

https://github.com/SceneView/sceneview-android/blob/main/arsceneview/src/main/java/com/google/ar/sceneform/ux/VideoNode.java

@grassydragon

**Comment by grassydragon** [comment]
> Video doesn't work right now because the complete functionality is commented out?

Yes, we didn't have time to make it work with the newer versions of SceneView, however, Thomas have said that `VideoNode` support is coming soon.

**Comment by Sergiobop** [comment]
Thank you for your fast response @grassydragon

In think we should reopen this issue meantime @ThomasGorisse

**Comment by PepaZapletal** [comment]
@S1996ouvik  Hi, can you share your new video node class?

**Comment by MasudaH** [comment]
Hello, it has been a while since the VideoNode feature was last discussed. Are there still plans to support it?

**Comment by grassydragon** [comment]
Hi!
Unfortunately, I can't promise anything since we don't have the capacity to implement it right now.
