### ISSUE TITLE
Try to migrate Augmented Image example of SceneForm to sceneview

### ISSUE THREAD

**Issue by dendy-prtha-tiukdw** [SceneView/sceneview-android#146]
Hello
I new with kotlin and try to recreate Augmented Image example from SceneForm using kotlin sceneview. i try to use onAugmentedImageUpdate to get a callback from sceneview but no luck.
How can i detect images come from sceneview? 

Thanks

**Comment by ThomasGorisse** [comment]
Hi,
Use `sceneView.configureSection{ config-> }` to add your database or images to ARCore recognizable images.
Call ```kotlin
sceneView.onAugmentedImage{augmentedImage->
//Check for tracking state before anchoring
    if(augmentedImage.isTracking)
        If(arNode.anchor==null) {
            arNode.anchor = augmentedImage.createAnchor()
        }
        If(!isPlaying) {
            play()
        }
   } else if(isPlaying){
        pause
   }
}
```

**Comment by dendy-prtha-tiukdw** [comment]
Hi,
i try to call onAugmentedImage function, but could not found it, What i found is onAugmentedImageUpdate. i found a closed issue on https://github.com/SceneView/sceneview-android/issues/81, and try to use that snippet code but still no luck. Currently, I got a type mismatch error while implementing this code 
`  override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMain2Binding.inflate(layoutInflater)
        setContentView(binding.root)
        sceneView = binding.sceneView
        sceneView.configureSession { session, config ->
            config.planeFindingMode = Config.PlaneFindingMode.DISABLED
            database = AugmentedImageDatabase(session)
            val matrixImage: Bitmap = BitmapFactory.decodeResource(resources, R.raw.matrix)
            database.addImage("matrix", matrixImage)
            config.setAugmentedImageDatabase(database)
        }

        sceneView.onAugmentedImageUpdate = this::checkAugmentedImageUpdate
    }

    private fun checkAugmentedImageUpdate(augmentedImage: AugmentedImage) {
    }`

Thanks for enlighting me since, I am still newbie with kotlin and still learning on lambda function.

**Comment by Cardo** [comment]
Hi @dendy-prtha-tiukdw , did you manage to make the checkAugmentedImageUpdate function to work?

**Comment by AMarquis1** [comment]
I have the same error as @dendy-prtha-tiukdw & @Cardo . Did you guys find the solution?

**Comment by ThomasGorisse** [comment]
`onAugmentedImageUpdate` is a list of listeners. So you should call:
```kotlin
sceneView.onAugmentedImageUpdate += checkAugmentedImageUpdate
```

**Comment by AMarquis1** [comment]
Thanks thomas, it works now!
