### ISSUE TITLE
How to add dot and make line between two dot in android sceneview

### ISSUE THREAD

**Issue by thanhphong190** [SceneView/sceneview-android#148]
hi everyone, how to i can add dot when tap model and make line between two dot using library
link image: https://drive.google.com/file/d/1EefYfMxao-3UqBE1gwILQjq2uAi_SNuR/view?usp=sharing

**Comment by grassydragon** [comment]
Hi!
The simplest way to display dots and lines is to use spheres and cylinders with an unlit materials. You can create them as glTF models and scale appropriately.

**Comment by thanhphong190** [comment]
> 

hi @grassydragon , i have create renderable, but how to it in library, code:
 val color = com.google.ar.sceneform.rendering.Color(.8f, 0f, 0f)
        MaterialFactory.makeOpaqueWithColor(activity, color)
            .thenAccept { material->
                // The sphere is in local coordinate space, so make the center 0,0,0
                val sphere = ShapeFactory.makeSphere(0.02f, Vector3.zero(),
                    material)
               // How to render sphere???
            }

**Comment by grassydragon** [comment]
Hi!
A similar question has been asked on our Discord server and we've found out that the latest version of SceneView doesn't allow rendering shapes without creating a custom node or using a glTF model.

**Comment by thanhphong190** [comment]
> Hi! A similar question has been asked on our Discord server and we've found out that the latest version of SceneView doesn't allow rendering shapes without creating a custom node or using a glTF model.

hi @grassydragon @ThomasGorisse when i tap model, have add dot and line between two dots but the position of measurement points and lines cannot stick to the model. Can u help me resolve it? (i have research but not have way)
link video: https://drive.google.com/file/d/1KOuO52MDQY6mVZKl1kn0R3DuRbWWh4Oi/view?usp=sharing

**Comment by ThomasGorisse** [comment]
Hi.

Does your model contains sub objects/meshes or is it a single object one?
(You can check it within blender)

The [SceneView.pickNode](https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L592) function will give you a `Renderable` that correspond to the picked subpart of your model at export time.

What you actually want to do will be very easy to handle in SceneView 1.0.0 since the `ModelNode` will directly have child nodes coming from the glTF objects (Renderables, Lights and even Cameras).
So you will just have make each child `Node` of your `ModelNode` clickable and add an `onTap` listener to it.

**Comment by thanhphong190** [comment]
> > Hi! A similar question has been asked on our Discord server and we've found out that the latest version of SceneView doesn't allow rendering shapes without creating a custom node or using a glTF model.
> 
> hi @grassydragon @ThomasGorisse when i tap model, have add dot and line between two dots but the position of measurement points and lines cannot stick to the model. Can u help me resolve it? (i have research but not have way) link video: https://drive.google.com/file/d/1KOuO52MDQY6mVZKl1kn0R3DuRbWWh4Oi/view?usp=sharing

hi @ThomasGorisse video above(i using sceneform library https://github.com/SceneView/sceneform-android) when I rotate model not center. Can u help me resolve it? (this is model load in https://modelviewer.dev/editor/ : https://drive.google.com/file/d/1Zz5I_8Ma8A1SlUCzMI0xQb5GsyNt5v-0/view?usp=sharing)
My code rotation:
class DragRotationController(
    private val transformableNode: DragTransformableNode,
    gestureRecognizer: DragGestureRecognizer
) :
    BaseTransformationController<DragGesture>(transformableNode, gestureRecognizer) {

    companion object {

        private const val initialLat = 26.15444376319647
        private const val initialLong = 18.995950736105442

        var lat: Double = initialLat
        var long: Double = initialLong
    }

    // Rate that the node rotates in degrees per degree of twisting.
    private var rotationRateDegrees = 0.1f

    public override fun canStartTransformation(gesture: DragGesture): Boolean {
        return transformableNode.isSelected
    }

    private fun getX(lat: Double, long: Double): Float {
        return (transformableNode.radius * Math.cos(Math.toRadians(lat)) * Math.sin(Math.toRadians(long))).toFloat()
    }

    private fun getY(lat: Double, long: Double): Float {
        return transformableNode.radius * Math.sin(Math.toRadians(lat)).toFloat()
    }

    private fun getZ(lat: Double, long: Double): Float {
        return (transformableNode.radius * Math.cos(Math.toRadians(lat)) * Math.cos(Math.toRadians(long))).toFloat()
    }

    override fun onActivated(node: Node?) {
        super.onActivated(node)
        Handler().postDelayed({
            transformCamera(lat, long)
        }, 0)
    }

    public override fun onContinueTransformation(gesture: DragGesture) {

        val rotationAmountY = gesture.delta.y * rotationRateDegrees
        val rotationAmountX = gesture.delta.x * rotationRateDegrees
        val deltaAngleY = rotationAmountY.toDouble()
        val deltaAngleX = rotationAmountX.toDouble()

        long -= deltaAngleX
        lat += deltaAngleY

        lat = Math.max(Math.min(lat, 90.0), 0.0)

        transformCamera(lat, long)
    }

    private fun transformCamera(lat: Double, long: Double) {
        val camera = transformableNode.scene?.camera

        var rot = Quaternion.eulerAngles(Vector3(0F, 0F, 0F))
        val pos = Vector3(getX(lat, long), getY(lat, long), getZ(lat, long))
        rot = Quaternion.multiply(rot, Quaternion(Vector3.up(), (long).toFloat()))
        rot = Quaternion.multiply(rot, Quaternion(Vector3.right(), (-lat).toFloat()))
        camera?.localRotation = rot
        camera?.localPosition = pos
    }

    fun resetInitialState() {
        transformCamera(initialLat, initialLong)
    }

    public override fun onEndTransformation(gesture: DragGesture) {}
}

class DragTransformableNode(val radius: Float, transformationSystem: TransformationSystem) :
    TransformableNode(transformationSystem) {
    val dragRotationController = DragRotationController(
        this,
        transformationSystem.dragRecognizer
    )
}

**Comment by thanhphong190** [comment]
> Hi.
> 
> Does your model contains sub objects/meshes or is it a single object one? (You can check it within blender)
> 
> The [SceneView.pickNode](https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L592) function will give you a `Renderable` that correspond to the picked subpart of your model at export time.
> 
> What you actually want to do will be very easy to handle in SceneView 1.0.0 since the `ModelNode` will directly have child nodes coming from the glTF objects (Renderables, Lights and even Cameras). So you will just have make each child `Node` of your `ModelNode` clickable and add an `onTap` listener to it.

hi @ThomasGorisse @grassydragon can you for me example **onTap** in ModelNode and get point at position tap?(gen rendering shape and show it). Please!

**Comment by grassydragon** [comment]
> hi @ThomasGorisse @grassydragon can you for me example onTap in ModelNode and get point at position tap?(gen rendering shape and show it). Please!

Hi!
Yes, as Thomas said you can find the tapped renderable and modify its material, for example. However, to find the point in the 3D scene where the model was tapped you will need to do additional calculations (to unproject the screen point).

**Comment by pfontainesur** [comment]
> Hi.
> 
> Does your model contains sub objects/meshes or is it a single object one? (You can check it within blender)
> 
> The [SceneView.pickNode](https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L592) function will give you a `Renderable` that correspond to the picked subpart of your model at export time.
> 
> What you actually want to do will be very easy to handle in SceneView 1.0.0 since the `ModelNode` will directly have child nodes coming from the glTF objects (Renderables, Lights and even Cameras). So you will just have make each child `Node` of your `ModelNode` clickable and add an `onTap` listener to it.

Can you also retreive child nodes from GLB files in SceneView 1.0.0 ?
I want to change the node material color onTap.

**Comment by ThomasGorisse** [comment]
You can also, just add an `onTap` listener to  your `ModelNode` children (only renderable can be touch detected)

**Comment by thanhphong190** [comment]
hi @ThomasGorisse , version 1.0.0, can i set position for view node? I don't see any function or param to set

**Comment by grassydragon** [comment]
> hi @ThomasGorisse @grassydragon , version 1.0.0, can i set position for view node? I don't see any function or param to set

Hi!
It should be possible to position a `ViewNode` since it implements the `TransformComponent` interface.

**Comment by thanhphong190** [comment]
> > hi @ThomasGorisse @grassydragon , version 1.0.0, can i set position for view node? I don't see any function or param to set
> 
> Hi! It should be possible to position a `ViewNode` since it implements the `TransformComponent` interface.

![Screen Shot 2022-10-28 at 17 05 37](https://user-images.githubusercontent.com/15722859/198562449-20ab6f8c-d16f-4a6d-96fd-c560be512064.png)

**Comment by ThomasGorisse** [comment]
Hi,
Thanks for the feedback.

Can you share the part of code you are using for the ViewNode (with its layout please) so we can have a look at where the issue is coming from.

**Comment by thanhphong190** [comment]
> Hi, Thanks for the feedback.
> 
> Can you share the part of code you are using for the ViewNode (with its layout please) so we can have a look at where the issue is coming from.
hi @ThomasGorisse @grassydragon 
layout item_dot.xml

<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/dots"
    android:layout_width="8dp"
    android:layout_height="8dp"
    android:layout_weight="1"
    android:background="@drawable/ic_red_dot"
    android:textColor="#ffffff"
    android:gravity="center"
    android:orientation="vertical"
    android:paddingStart="18dp"
    android:paddingEnd="18dp"
    android:paddingTop="12dp"
    android:paddingBottom="12dp"
    android:textSize="30dp"
    android:textStyle="bold"
    android:text=""
    android:textAlignment="center" />


create viewnode:
val view = ViewNode(sceneView, R.layout.item_dot, true, true)
        sceneView.addChildNode(view)

**Comment by thanhphong190** [comment]
> Hi, Thanks for the feedback.
> 
> Can you share the part of code you are using for the ViewNode (with its layout please) so we can have a look at where the issue is coming from.

hi @ThomasGorisse , can you help me resolve it, please

**Comment by ozh-dev** [comment]
> > Hi, Thanks for the feedback.
> > Can you share the part of code you are using for the ViewNode (with its layout please) so we can have a look at where the issue is coming from.
> 
> hi @ThomasGorisse , can you help me resolve it, please


There some bug in ViewStream Builder
![image](https://user-images.githubusercontent.com/8090222/208091762-ef6e8b88-471d-44ae-99f9-9b3b6391f467.png)

**Comment by ThomasGorisse** [comment]
Nice catch @ozh-dev !
I added you the contributor role. You should be able to push directly to the repository.
Would you mind creating a PR with your fix?
Thanks

**Comment by ozh-dev** [comment]
> Nice catch @ozh-dev ! I added you the contributor role. You should be able to push directly to the repository. Would you mind creating a PR with your fix? Thanks

No problem. I'll do it.
