### ISSUE TITLE
App is crashed, during loading the model

### ISSUE THREAD

**Issue by Aryan1g** [SceneView/sceneview-android#151]
App is crashed every time during loading model, even model is only 4 mb. 

Below is the code:

class MainActivity : AppCompatActivity() {
    lateinit var sceneView: SceneView
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        sceneView = findViewById(R.id.sceneview)
        val modelnode = ModelNode(
            position = Position(z = -4.0f),
            rotation = Rotation(x = 35.0f)
        )
        sceneView.addChild(modelnode)
       sceneView.cameraNode.transform = lookAt(
            eye = modelnode.worldPosition.let {
                Position(x = it.x, y = it.y + 0.5f, z = it.z + 2.0f)
            },
            target = modelnode.worldPosition,
            up = Direction(y = 1.0f)
        )

        lifecycleScope.launchWhenCreated {
            sceneView.environment = HDRLoader.loadEnvironment(
                context = this@MainActivity,
                lifecycle = lifecycle,
                hdrFileLocation = "environments/clarens_midday_1k.hdr",
                specularFilter = false,
            )?.apply {
                indirectLight?.intensity = 50_000f
            }

            modelnode.loadModel(
                context = this@MainActivity,
                lifecycle = lifecycle,
                glbFileLocation = "models/kamla.glb",
                autoAnimate = false,
                scaleToUnits = 0.1f,
                centerOrigin = Position(x = 0.0f, y = 0.0f, z = 0.0f)
                )

            sceneView.cameraNode.smooth(
                lookAt(
                    eye = modelnode.worldPosition.let {
                        Position(x = it.x - 0.4f, y = it.y + 0.4f, z = it.z - 0.6f)
                    },
                    target = modelnode.worldPosition,
                    up = Direction(y = 1.0f)
                ), speed = 0.7f
            )
        }

    }

}

**Comment by ThomasGorisse** [comment]
So your model is corrupted
