### ISSUE TITLE
what should be position of x ,y and z axis to make model always on ground in hdr background

### ISSUE THREAD

**Issue by Aryan1g** [SceneView/sceneview-android#153]
I want like this

https://user-images.githubusercontent.com/111751463/190189030-bd47bce7-8ccf-4e7b-9ad1-74a33cd48004.mp4

How to do exactly like this

**Comment by grassydragon** [comment]
Hi!
It depends on your HDR texture. However, it isn't possible to keep the model attached to a point on the ground because of how the HDR texture is rendered (like a background).

**Comment by Aryan1g** [comment]
So how can I achieved this

**Comment by Aryan1g** [comment]
> Hi! It depends on your HDR texture. However, it isn't possible to keep the model attached to a point on the ground because of how the HDR texture is rendered (like a background).

So how can I achieved this

**Comment by grassydragon** [comment]
> So how can I achieved this

You can add the ground and other decorations as 3D objects.

**Comment by Aryan1g** [comment]
> > So how can I achieved this
> 
> You can add the ground and other decorations as 3D objects.

okk one more thing is there way  to stop the rotation of model and hdr
