### ISSUE TITLE
Issues with rendering on Samsung devices and simulator

### ISSUE THREAD

**Issue by Ncit** [SceneView/sceneview-android#165]
### Discussed in https://github.com/SceneView/sceneview-android/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **Ncit** September 26, 2022</sup>
I have issues with model on devices samsung a52 and simulator. Can you give me some advices, on how to fix it?
On test device honor 10 everything is ok.
These is model on samsung a52
![image_2022_09_23T13_18_54_198Z](https://user-images.githubusercontent.com/2179841/192256580-c1404469-00e3-474b-80a9-2ef301554d32.png)
This is model in simulator
![image](https://user-images.githubusercontent.com/2179841/192257306-02e16862-9639-4ad7-8635-cf7501c79494.png)
</div>

**Comment by Ncit** [comment]
also found issue on xiaomi and pixel3 devices. Scene rendereres multiple models

**Comment by UnicornJin** [comment]
Me too
