### ISSUE TITLE
Create simple shape

### ISSUE THREAD

**Issue by Yare-Yare-Daze** [SceneView/sceneview-android#166]
Hello, can i create simple shape from class ShapeFactory?

I tried this one, but com.google.ar.sceneform.rendering.Color is deprecated:
val material = MaterialFactory.makeTransparentWithColor(this@MainActivity, lifecycle, com.google.ar.sceneform.rendering.Color(1f, 0f, 0f, 0.5f))
val modelTest = ShapeFactory.makeCube(lifecycle, Vector3(1f, 1f, 1f), Vector3(0f, 0f, 0f,), material.get())

How can i create simple half transparent cube? 
Thanks in advance!

**Comment by stackunderflows** [comment]
I would like to know how to do this as well. An example would be much appreciated.

**Comment by pablojoseoroz** [comment]
Hi, I want to render a CubeNode when tap, can any help me? I am using this code:
```
getScene().addChildNode(
                AnchorNode(getEngine(), hitResult.createAnchor()).addChildNode(
                    CubeNode(getEngine())
                )
            )
```
Thx
