### ISSUE TITLE
ARCore Camera Image is rotated by 90 degrees anti-clockwise in portrait mode but is the right way up when used in landscape mode

### ISSUE THREAD

**Issue by sarimmehdi** [SceneView/sceneview-android#170]
This is a problem as old as ARCore itself. Basically, if you record the ARCore camera image (I used [renderscript](https://github.com/android/renderscript-intrinsics-replacement-toolkit/issues/6) and a [helpful blog article](https://blog.minhazav.dev/how-to-use-renderscript-to-convert-YUV_420_888-yuv-image-to-bitmap/#tobitmapimage-image-method) to setup the YUV to ARGB conversion):

```
val cameraImage = arFrame.frame.acquireCameraImage()
val width = cameraImage.width
val height = cameraImage.height
val byteArray = Toolkit.toNv21(cameraImage)
byteArray?.let {
Toolkit.yuvToRgbBitmap(
        byteArray,
        width,
        height,
        YuvFormat.NV21
).let { bitmap ->
        saveBitmapToDevice(
            name,
            session,
            bitmap,
            context
)}}
```
And then save it as a bitmap, the saved image is rotated 90 degrees anticlockwise if it was recorded in portrait mode but it would be the right side if recorded in landscape mode. I am returning to ARCore and Sceneform development after several months and it seems the problem is still there. 

However, I did notice `arSession.displayRotation` and I tried setting it to different Surface rotation values (`ROTATION_270` and `ROTATION_0`) but that doesn't seem to work as well. It's not that big of a deal since I can set up the post-processing pipeline to rotate the images after they are recorded but it always struck me as odd why the images are like this and whether we can have an option to do something about it.

**Comment by grassydragon** [comment]
Hi!
It is only a guess but I think that ARCore doesn't care about the display orientation internally and it is only used for rendering. Therefore, the landscape orientation of the camera sensor is the default one.
