### ISSUE TITLE
App crash when render larger file gltf

### ISSUE THREAD

**Issue by thanhphong190** [SceneView/sceneview-android#171]
hi @ThomasGorisse @grassydragon , when render large  file (>50mb)-> crash app? can u help check and fix it? thanks
link file: https://drive.google.com/file/d/1mns9-Q3ggKq26SDobXTXrI5y9E53oXXK/view?usp=sharing

**Comment by AdrienBotrel** [comment]
Hi
Do you see any error in the logcat when the app crash?

**Comment by grassydragon** [comment]
Hi!
I'm not able to view your file in the [sample glTF viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/). It shows a message that there is an error in the file.

**Comment by thanhphong190** [comment]
when render file, memory high, from 0.1gb increase to >2gb -> crash app.

**Comment by thanhphong190** [comment]
> Hi
> Do you see any error in the logcat when the app crash?

when render file, memory high, from 0.1gb increase to >2gb -> crash app.

**Comment by thanhphong190** [comment]
> Hi!
> I'm not able to view your file in the [sample glTF viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/). It shows a message that there is an error in the file.

hi @grassydragon you can use link https://modelviewer.dev/editor/ view file

**Comment by AdrienBotrel** [comment]
I tried to display it and I did it with no error in augmented reality.
The error come from your code I think. Or maybe your mobile phone is not enough efficient for big files

**Comment by hammad-siraj** [comment]
@grassydragon @ThomasGorisse Would be able to render 140 MB glb file through sceneform android, We tried to render it but it wouldn’t be able to load on the emulator or Samsung Tab s8. 

Would you recommend me something to achieve this? and we can’t compromise on the glb file size as reducing the size would also effect the quality.
