### ISSUE TITLE
Plan to upgrade ARcore SDK 1.33 above

### ISSUE THREAD

**Issue by akunerio** [SceneView/sceneview-android#177]
Do you have plan to update the ARCore SDK to 1.33 or latest version?
It is because the cloud anchor will deprecated next year. https://developers.google.com/ar/develop/cloud-anchors/endpoint-changes

I still try to use this dependency, previously I used Sceneform 1.15 (archived). Now, I think is more easy to handle. Thanks!

**Comment by grassydragon** [comment]
Hi!
Yes, we'll update the ARCore dependency. Thanks for pointing this out!

**Comment by akunerio** [comment]
Great! Thank you! I will continue to implement this dependency for research.

**Comment by ThomasGorisse** [comment]
We had an issue with the 1.33 at the camera stream level from what I remember.
