### ISSUE TITLE
3d model is not scaling ones loaded as default scale

### ISSUE THREAD

**Issue by vigit3** [SceneView/sceneview-android#178]
### Below is my code

class SceneActivity : AppCompatActivity() {
    lateinit var sceneView: SceneView
    lateinit var linearLayout1: LinearLayout
    lateinit var linearLayout2: LinearLayout
    
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_scene)
        sceneView = findViewById(R.id.sceneview)
        linearLayout1 = findViewById(R.id.linear)
        linearLayout2 = findViewById(R.id.ppp)
        
        val param = LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT,
            0f)
        
        linearLayout2.setLayoutParams(param)
        val param3 = LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT,
            0.6f)
        
        linearLayout1.setOnClickListener {
            val param1 = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT,
                0.6f)
            linearLayout2.setLayoutParams(param1)
        }
        
        sceneView.setZOrderOnTop(true)
        val modelNode = ModelNode(
            position = Position(x = 0.0f, y = 0.0f, z = 0.0f)
        )
        sceneView.addChild(modelNode)
        
        sceneView.cameraNode.transform = lookAt(
            eye = modelNode.worldPosition.let {
                Position(x = it.x - 0.28f, y = it.y + 0.2f, z = it.z + 0.1f)
            },
            target = modelNode.worldPosition,
            up = Direction(y = 1.0f)
        )
        
        lifecycleScope.launchWhenCreated {
            sceneView.environment = HDRLoader.loadEnvironment(
                context = this@SceneActivity,
                lifecycle = lifecycle,
                hdrFileLocation = "environments/studio_small_08_1k.hdr",
                specularFilter = true
            )?.apply {
                indirectLight?.intensity = 50_000f
            }

            if (linearLayout2.layoutParams == param3){
                modelNode.loadModel(
                    context = this@SceneActivity,
                    lifecycle = lifecycle,
                    glbFileLocation = "models/tree.glb",
                    scaleToUnits = 0.34f,
                    centerOrigin = Position(x = 1.4f, y = -0.1f, z = 0.2f))
            }
            if (linearLayout2.layoutParams == param){
                modelNode.loadModel(
                    context = this@SceneActivity,
                    lifecycle = lifecycle,
                    glbFileLocation = "models/tree.glb",
                    scaleToUnits = 1.0f,
                    centerOrigin = Position(x = 1.4f, y = -0.1f, z = 0.2f))
            }

        }
    }
}

**Comment by grassydragon** [comment]
Hi!
I think you shouldn't use `LayoutParams` to scale the model. Instead you should change the scale of the `Node`.
