### ISSUE TITLE
3D viewer example

### ISSUE THREAD

**Issue by kelvinwatson** [SceneView/sceneview-android#18]
I tried following the `sample-ar-model-viewer`, except I want to only use the SceneView (3D only). However, I am unable to see the object, even when `sceneViewer.addChild(modelNode)` is called. 

I guess I'm not supposed to use an `ArModelNode` but instead, `ModelNode`, but I can't seem to get this working. Is it possible to post a working example using just 3D?

```
lateinit var sceneView: SceneView
lateinit var modelNode: ArModelNode

override fun onViewCreated(view: View, savedInstanceState: Bundle?) {

    modelNode = ArModelNode(placementMode = PlacementMode.BEST_AVAILABLE).apply {
            loadModel(
                context = requireContext(),
                coroutineScope = lifecycleScope,
                glbFileLocation = "models/spiderbot.glb",
                autoAnimate = true,
                onLoaded = { isLoading = false })
            onTrackingChanged = { _, isTracking, _ ->
                actionButton.isGone = !isTracking
            }
        }
        sceneView.addChild(modelNode)
```

**Comment by morhenny** [comment]
I believe the `ArModelNode` is not yet included in the latest release, try to just use the `ArNode` instead. 
That's what I've been using thus far to display my 3d models and it's a superclass of the future `ArModelNode`.

**Comment by ThomasGorisse** [comment]
Hi,
Can you please try to clone the main branch version?
I'm currently working on the model-viewer (3D only) sample.
It should be available soon on the 0.1.0.

**Comment by kelvinwatson** [comment]
@ThomasGorisse Sorry I didn't quite understand what you meant. I am pretty sure I cloned the main branch.

**Comment by kelvinwatson** [comment]
@morhenny ArNode still uses `ArSceneView` under the hood, like the `session` that doesn't apply to `SceneView`. Can you post some working code?

**Comment by morhenny** [comment]
Oh I think I misunderstood your issue then @kelvinwatson, as I have been using the `ArSceneView` myself and not the 3D-only.

Not sure if this helps you at all then, but this is code to position a 3D Model on a plane, after being tapped by the user.

`sceneView.onTouchAr = { hitResult, _ ->
            val node = ArNode()
            node.anchor = hitResult.createAnchor()
            node.setRenderable(cubeModel)
            sceneView.addChild(node)
        }`

**Comment by DvD-DvD** [comment]
Hey,
I face the same issue. When can we expect the 0.1.0 release?

**Comment by ThomasGorisse** [comment]
The 0.1.0 has been released and available on mavenCentral 🎉

We added a sample for 3D only usage.

Please consider sponsoring us if you like our work and want to see more features coming.
