### ISSUE TITLE
Duplicate Class Error

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#182]
**Steps to reproduce:**

- Create a new Android Studio project with an empty activity
- Build the project (the project should build successfully)
- Add the SceneView dependency (`implementation 'io.github.sceneview:arsceneview:0.9.0'`)
- Sync and build the project again

**Error:**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.lifecycle.ViewModelLazy found in modules lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1) and lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1)
     Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1) and lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

[Dependency tree](https://github.com/SceneView/sceneview-android/files/10049654/dependency-tree.txt)

**Comment by dineshoptisol** [comment]
Hi, 
It's because **viewmodel-ktx** is different version from **viewmodel** version.
it is solved by **viewmodel** and **viewmodel-ktx** version same. Even you do not have any in your dependency, we have to add these in order to solve the issue. 

> might be **SDK** Issue (not sure).

```
def lifecycle_version = "2.5.1"
implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
```
