### ISSUE TITLE
CameraX and Sceneview 3d 

### ISSUE THREAD

**Issue by dineshoptisol** [SceneView/sceneview-android#185]
Hi, I'm working on **CameraX** ImageAnalysis and **Sceneview**. need to show some models on overlay so i'm using Sceneview 3d only without AR. 
If I'll use Sceneview and PreviewView the Sceneview model is added behind the PreviewView., not coming on front of PreviewView. Means if i hide PreviewView the Sceneview Model is showing properly.

Am I using properly? any hint or some guidance would be appreciated.

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="false"
    tools:background="@android:color/white">

    <androidx.camera.view.PreviewView
        android:id="@+id/cameraPreview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <io.github.sceneview.SceneView
        android:id="@+id/sceneview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/transparent" />
</FrameLayout>
```

**Comment by dineshoptisol** [comment]
Adding view as child view Programatically working fine. please check this once you have time. not sure why.

**Comment by ThomasGorisse** [comment]
Thanks for the feedback. What SceneView version are you targeting?

**Comment by dineshoptisol** [comment]
Hi @ThomasGorisse using latest version 0.9.0
