### ISSUE TITLE
Model 3d always top view different and LoadingNode tags are too blurry

### ISSUE THREAD

**Issue by thanhphong190** [SceneView/sceneview-android#187]
hi @ThomasGorisse @grassydragon, when scroll model 3d alway top view different, how to set model 3d equal view different?
- I using LoadingNode loading tag but too blurry. How to improve quality view?
Can you help me resolve it? thank so much
![image](https://user-images.githubusercontent.com/15722859/206222625-36adced8-1662-4db6-b94d-7c30c63bf088.png)

**Comment by ThomasGorisse** [comment]
Hi.
Sorry about that but I totally don't get your question. Can you precise it?

**Comment by thanhphong190** [comment]
hi @ThomasGorisse when I set sceneView.setZOrderOnTop(false) -> background black. How to set background transparent? (I set  sceneView.setBackgroundDrawable(transparent) but not working!) 
![Screenshot_20221209-114111_BalancePlay](https://user-images.githubusercontent.com/15722859/206625634-9ed8c9ff-a539-498c-b495-1146bc59ebd7.jpg)

**Comment by rudashi** [comment]
How to fix this issue?
