### ISSUE TITLE
Crashed with creation ViewNode with Plane object

### ISSUE THREAD

**Issue by ozh-dev** [SceneView/sceneview-android#190]
When I need to create a Plane object, I also have to use a ViewNode. But the Plane object, when created, lost some parameters that will be needed in the future, and I have a crash.

And I have to use ugly workarounds to create the Plane properly.

ViewNode:
![image](https://user-images.githubusercontent.com/8090222/208299499-71a6dca4-7de4-4d9a-ac75-29be76006a2d.png)

I think the main source of the problem is the Plane.kt arch, because the Plane class has no parameters from Geometry.

@ThomasGorisse Maybe you should reconsider creating a Plane.kt class?

**Comment by ThomasGorisse** [comment]
Hi @ozh-dev.
Thanks for the report. I have to admit that I messed how will calls be at the end.
You're right on this `Geometry` fact
Would you mind creating a PR with a structure change proposal so we can discuss around it?

**Comment by ThomasGorisse** [comment]
I will then publish a SceneView 1.0.0 (3D only) to maven central.

**Comment by ozh-dev** [comment]
> Hi @ozh-dev. Thanks for the report. I have to admit that I messed how will calls be at the end. You're right on this `Geometry` fact Would you mind creating a PR with a structure change proposal so we can discuss around it?

I have been doing a feature for my work with SceneView, And after  it I'll think about fix for it, maybe I'll find more bugs

**Comment by Tnation87** [comment]
> I will then publish a SceneView 1.0.0 (3D only) to maven central.

Hi, I fixed the crash [here](https://github.com/SceneView/sceneview-android/pull/241), the fix isn't ideal, but I think it should be considered a hot fix until the architecture of the parent is refactored
