### ISSUE TITLE
SceneView 1.0 Release Date

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#191]
Hi, do you have a timeline for the 1.0 release date? I am considering entering the ARCore Geospatial API Challenge, but wanted the TerrainAnchor support for the app I have.

**Comment by ThomasGorisse** [comment]
Hi,
It's not totally ready yet. But we recently divided SceneView and ArSceneView versions so you can target the latest ARCore version (1.35 for now) by using the depencies from those released (SceneView 1.0.0 is also now available on maven central):
https://github.com/SceneView/sceneview-android/releases/tag/v0.9.1

**Comment by ryust** [comment]
v0.9.1 with ARCore 1.35 works well... I had no idea there was a 0.9.1 version.

Last problem is getting the #176 crash when onBackPress of an activity. Any fixes for that?
