### ISSUE TITLE
"Sceneview" and "Sceneform" dependencies cannot be added together

### ISSUE THREAD

**Issue by MohamedFouad999** [SceneView/sceneview-android#194]
When I added them together I got this error

Duplicate class com.google.ar.sceneform.ArHelpers found in modules arsceneview-0.9.1-runtime (io.github.sceneview:arsceneview:0.9.1) and core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0)
Duplicate class com.google.ar.sceneform.Sceneform found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.SequentialTask found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.Trackables found in modules arsceneview-0.9.1-runtime (io.github.sceneview:arsceneview:0.9.1) and core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0)
Duplicate class com.google.ar.sceneform.animation.AnimatableModel found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimation found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimation$1 found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimation$2 found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimation$3 found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimation$PropertyValuesHolder found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimator found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimator$1 found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimator$2 found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimator$PropertyValuesHolder found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.animation.ModelAnimator$PropertyValuesHolder$AnimationProperty found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.collision.Box found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.collision.Collider found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.collision.CollisionShape found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.collision.CollisionSystem found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
Duplicate class com.google.ar.sceneform.collision.Intersections found in modules core-1.21.0-runtime (com.gorisse.thomas.sceneform:core:1.21.0) and sceneview-0.9.0-runtime (io.github.sceneview:sceneview:0.9.0)
....................

**Comment by grassydragon** [comment]
Hi!
This is because SceneView is based on the Sceneform source code but has been almost completely rewritten. It isn't intended to use these to libraries at the same time.

**Comment by MohamedFouad999** [comment]
But i need to use the Sceneview for AR Model and Sceneform for Augmented Images, What i can do?

**Comment by grassydragon** [comment]
You need to use either of these libraries. It is possible to place models and Augmented Images in both cases since the libraries depend on ARCore. While Augmented Images aren't supported in SceneView at the level of API, you can create your own node to work with them.

**Comment by MohamedFouad999** [comment]
How can I do that can you give an example ?
