### ISSUE TITLE
Limit on number of ArModelNodes in an ArSceneView?

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#195]
Is there a limit on the number of ArModelNodes that can be anchored together in an ArSceneView? I'm having difficulty getting more than one node to show. It appears that only the last one added shows. So before I continue struggling with it I wanted to determine whether it's even possible to have more than one node anchored. Any insight (an example is better) would be helpful.

**Comment by AdrienBotrel** [comment]
Normally you should be able to use as many nodes as you want (depending of course of the performance of you phone). @ThomasGorisse did an example with a lot of rings in this video: https://youtube.com/shorts/-2b32ocBWM8?feature=share

**Comment by ryust** [comment]
But are those using Geospatial anchors? ArNodes? ArSceneView? Unless source is shown those could be apples to my oranges. As I said, only the last mode will display in my usage.

**Comment by AdrienBotrel** [comment]
Are you using one anchor for all your nodes. If yes, I can't help you for the moment, I never tried that before. If not, you can see this example using 1 anchor for each model displayed: https://github.com/SceneView/sceneview-android/tree/main/samples/ar-model-viewer

**Comment by ryust** [comment]
No, I'm using multiple TerrainAnchors, different for each node. I've viewed the example you linked... actually, viewed every example everywhere, but I'm unable to find a sample using multiple Geospatial anchors.

**Comment by ryust** [comment]
Ok, more testing revealed that I can show more than one anchored node... if they are practically on top of each other... which means multiple nodes will show in the scene. But I'm baffled why the ones about 100' left and right of from the visible ones don't show. I suspect they could displayed on edge so I can's distinguish them. 

So now my question is how to get anchored nodes to look at and face the camera? The API and lack of documentation on doing that is a challenge to figure out. Any help?
