### ISSUE TITLE
DepthOcclusion limited to 8 m. 

### ISSUE THREAD

**Issue by RGregat** [SceneView/sceneview-android#197]
The current implementation of the DepthOcclusion functionality uses still the old limitation of the DepthAPI, which is only around 8 m. With a newer Release of ARCore the new max range is around 65 m

**Comment by AdrienBotrel** [comment]
For me, these 2 lines should be modified:
https://github.com/SceneView/sceneview-android/blob/880c9dfbe34a4be159928c8037e88236a612a3a3/arsceneview/src/main/java/io/github/sceneview/ar/camera/ArCameraStream.kt#L280
https://github.com/SceneView/sceneview-android/blob/880c9dfbe34a4be159928c8037e88236a612a3a3/arsceneview/src/main/java/io/github/sceneview/ar/camera/ArCameraStream.kt#L285

**Comment by grassydragon** [comment]
You can create a pull request with the proposed changes.

**Comment by AdrienBotrel** [comment]
https://github.com/SceneView/sceneview-android/pull/199

**Comment by grassydragon** [comment]
@AdrienBotrel
Great! Thank you for your contribution!

**Comment by AdrienBotrel** [comment]
This issue can be closed now

**Comment by ThomasGorisse** [comment]
Merged in main
