### ISSUE TITLE
About Rotation and animation

### ISSUE THREAD

**Issue by AqeelAaqi** [SceneView/sceneview-android#209]
I want to show my GLB model and rotate it according to touch also my model has animations I want to play on button click can I achieve this functionality using this library please answer I'm stuck on this issue also try com.gorisse.thomas.sceneform:sceneform:1.21.0??

**Comment by AqeelAaqi** [comment]
resolved by myself

**Comment by rabinansal** [comment]
@AqeelAaqi please share the code
