### ISSUE TITLE
not Able to view using arsceneview

### ISSUE THREAD

**Issue by AqeelAaqi** [SceneView/sceneview-android#215]
Hello dear,
I want to view the **GLB** model with animation for both **AR** and **without AR** but I can only achieve one at the same time 
if I want to view a model then I can achieve this only using **sceneview**.
if want AR then I can achieve only just using **arsceneview** but I want both at the same.
now issues are
- I didn't achieve both functionalities using one library
- both libraries are not rendered in the same project due to duplication of filament
- what can I do also I want to play animations on both  **sceneview** and **arsceneview**

### Kindly reply me

**Comment by AqeelAaqi** [comment]
I've done by myself

**Comment by dhaval-android** [comment]
@AqeelAaqi  Can you explain how you managed animation with scenview I am also getting crash when using model with animation in latest version
