### ISSUE TITLE
Alternative to ViewRenderable

### ISSUE THREAD

**Issue by dimskom** [SceneView/sceneview-android#217]
It's not an issue but a question.
What is the alternative to ViewRenderable in this SDK?
I want to display (then rotate/scale/move) an android view and there is no way that I've found to achieve this using this SDK.

**Comment by ryust** [comment]
I got it to work by doing something like the code below:

val modelNode = ArModelNode(placementMode = PlacementMode.BEST_AVAILABLE).apply {...}

val textView = TextView(context)

ViewRenderable.builder()
                                                .setView(requireContext(), textView)
                                                .build(requireActivity().lifecycle)
                                                .thenAccept { renderable: ViewRenderable ->
                                                    val viewNode = ViewNode()
                                                    viewNode?.parent = modelNode
                                                    viewNode?.setRenderable(renderable)
                                                    viewNode?.position = Position(x = 0.0f, y = 0.0f, z = 0.0f)
                                                }

**Comment by dimskom** [comment]
@ryust I did something similar, but i still can get the ViewNode to rotate/scale/move. 
My usecase is having an android view that i can anchor and then move/scale/rotate. Maybe you can provide a better solution?

**Comment by ryust** [comment]
I'm not sure what you are trying to accomplish, but as I move closer to an anchored node it scales up/down automatically based on distance to it. I really am unsure about rotation or moves, but I've sorta got a node to face the camera (so the Android view is visible) by calling "modelNode.modelRotation = scenevView.cameraNode.rotation". I have no idea if this is the correct way. 

Much of my use of this library is through LOTS of trial and error until something works. I'm not by any means a 3D/AR expert so most of the concepts are obscure to me. My needs were simple... place nodes based on geospatial terrain anchors. Using Android views allows more flexibility to provide info cards to the user.
