### ISSUE TITLE
ArSceneView 0.9.7 breaks updating ViewRenderables

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#227]
I have a modelNode with an attached Android TextView renderable. The textView is updated with text as the user changes location. Everything was working great, but now 0.9.7 won't allow updates to the textView... it just displays the original text, not any updates. Going back to 0.9.4 and it all works again.

val modelNode = ArModelNode(placementMode = PlacementMode.BEST_AVAILABLE).apply {...}

val textView = TextView(context)

ViewRenderable.builder()
   .setView(requireContext(), textView)
   .build(requireActivity().lifecycle)
   .thenAccept { renderable: ViewRenderable ->
      val viewNode = ViewNode()
      viewNode?.parent = modelNode
      viewNode?.setRenderable(renderable)
      viewNode?.position = Position(x = 0.0f, y = 0.0f, z = 0.0f)
   }

**Comment by ThomasGorisse** [comment]
Thanks for the report. Could you please try to investigate it a little more?

**Comment by ryust** [comment]
Actually, I tried before posting anything. No matter the scenario once the textView renderable is showing with the modelNode it would no longer update contents via setText(). Used to work fine prior to 0.9.7 release. If I knew what to test I would. I am a novice regard AR and all the internal tech in the library... most of my success has been via tons of trial and error.

**Comment by ryust** [comment]
@wh173d3v11 Sorry, I don't have code to show other than above. So you were able to update multiple times in the onArFrame loop? That's where it breaks.

I reworked the app to not be dependent on updating a ViewRenderable... instead I just overlay the TextView on top of the screen to bypass the problem.

**Comment by ryust** [comment]
I have no idea if it's fixed, because I migrated the code away from updating a ViewRenderable in the onArFrame loop. Honestly, I have my doubts it's fixed because in the #245 issue ViewRenderables are even further broken in 0.9.8 and totally unusable. I am still on 0.9.7 and can't migrate until #245 (and possibly this issue) are resolved.

**Comment by jeromejs0** [comment]
the issue is still present in arsceneview 2.3.0; viewRenderable is broken but the anchor node placement and the view node placement works.
