### ISSUE TITLE
SceneView v1.0.7 Destroy issue

### ISSUE THREAD

**Issue by UnicornJin** [SceneView/sceneview-android#228]
Hi!

I'm using the sceneview in a multiple fragment app, when I switch from a fragment containing sceneview to another one without sceneview, the app will crash. I found the problem is because the sceneview is not correctly destroy.

After debugging I found the problems are from these line of codes:
<img width="642" alt="截屏2023-02-26 20 27 42" src="https://user-images.githubusercontent.com/47232548/221410516-f8277c49-4bcb-4f41-b789-2580cdc32eb0.png">

If I use skybox, the destroying skybox will give:
java.lang.IllegalStateException: Calling method on destroyed Skybox

If I don't use skybox, the destroy nodemanager will give:
java.lang.NullPointerException

Seems your order of destroy is not correct. And because the official sample is just one single fragment so your sample doesn't go through the destroy process completely.

I commented the destroy code for the skybox and nodemanager and now the thing works on my app. But this is not a good solution because there are some resources not released.

Please help us solve the issue!

**Comment by ThomasGorisse** [comment]
Thanks for the great report. Could you just precise where it's happening?

**Comment by UnicornJin** [comment]
> Thanks for the great report. Could you just precise where it's happening?

Sorry bro I can only confirm the bug is from these two destroy commands but I don't really understand how the whole system goes. >.<

**Comment by james-wemoms** [comment]
This crash happens in the SceneView destroy because 
`skyboxes.toList().forEach { runCatching { destroySkybox(it) } }`
Is called cleaning all sky boxes but then there is a call to 
`skybox?.let { engine.destroySkybox(it) }`

**Comment by ThomasGorisse** [comment]
Thanks @james-wemoms
Can you please make a PR removing the `skybox.destroy()` ?
Only the created ones from the SceneView should be destroyed.

**Comment by james-wemoms** [comment]
When removing the `skybox.destroy()` the code still crashes with a `ConcurrentModificationException` further along.
I am trying to find a solution but to no avail yet.

**Comment by princeku07** [comment]
any solution for that?

**Comment by Tnation87** [comment]
> When removing the `skybox.destroy()` the code still crashes with a `ConcurrentModificationException` further along. I am trying to find a solution but to no avail yet.

I'm not sure if it's the same issue I had, but for me using a concurrent hash map to represent the node manager fixed the issue of concurrent modification

**Comment by nero240399** [comment]
this problem related to navigation in compose too, i start a new activity for loading 3d model but when navigate back it still crash
