### ISSUE TITLE
Add a point clound renderer

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#23]
Add a point cloud renderer as suggested here: https://github.com/SceneView/sceneform-android/discussions/278

Things to consider:
- Integration with SceneView (using the new way of creating renderables and updating the points)
- Shape for visualizing the points (UV sphere or icosphere)

**Comment by grassydragon** [comment]
We still plan to implement it in future.

**Comment by raju535482** [comment]
Can you integrate Tango's Live Reconstrcution capabilities in ArSceneview ? I found one repo, but I am facing some NDK issues while building the project

Here is the link of repo: [](https://github.com/lvonasek/3DLiveScanner)
