### ISSUE TITLE
Some Native objects are not collected while switching between Ar and 3d

### ISSUE THREAD

**Issue by nischaysingla** [SceneView/sceneview-android#234]
I have observed that while frequently switching between Ar and 3d in same session. 

![sceneview_android_toggle](https://user-images.githubusercontent.com/11288494/224472141-e55ca87d-f8fa-4d3e-a86d-a52e94fb44d7.gif)

There is pilling up of native objects as seen in android studio profiler

<img width="898" alt="profiler_screen_shot" src="https://user-images.githubusercontent.com/11288494/224472189-bec2f0df-a2f6-419e-a2ae-51cdf57eae90.png">

Sample project for the same can be accessed by below link:

https://github.com/nischaysingla/SceneViewToggleImpl

complete video can be found here:

https://drive.google.com/file/d/1QT9Dh5UIrbo4CAYHHIdysrqLXz2Y-uqc/view?usp=sharing

**Comment by ThomasGorisse** [comment]
Hi,
You should use latest SceneView version, load your `Model` only one time instead each time you display your view and use one `ModelInstance` per `SceneView`/`ArSceneView`

**Comment by nischaysingla** [comment]
Hi @ThomasGorisse,

Thanks for your reply, 
I tried what you have suggested.

Issue is when i try to create **ModelInstance** second time from same Model object by calling **createInstance()** it throws following native exception:

`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x202a205d355c82 in tid 23572 (eviewtoggleimpl), pid 23572 (eviewtoggleimpl)
  pid: 23572, tid: 23572, name: eviewtoggleimpl  >>> com.labs.flipkart.sceneviewtoggleimpl <<<
        #00 pc 00000000001aead8  /data/app/~~kFK37XCDJC1p2CdyXYwlmw==/com.labs.flipkart.sceneviewtoggleimpl-_Vb_L4qyYmSsRVsiK_A29w==/base.apk!libgltfio-jni.so (offset 0x4ca000) (BuildId: ec46e810f55a650db8db54a45bb6d6b35dde0180)`

Please find the complete code [here](https://github.com/nischaysingla/SceneViewToggleImpl/blob/master/app/src/main/java/com/labs/flipkart/sceneviewtoggleimpl/MainActivity.kt)


Also below code always returns null when called outside **doOnAttachedToScene** 

GLBLoader.loadModel(
                        this@BlackActivity,
                "LRCFZ6CEGGHUTA4G.glb"
                )


Have a look [here](https://github.com/nischaysingla/SceneViewToggleImpl/blob/master/app/src/main/java/com/labs/flipkart/sceneviewtoggleimpl/BlackActivity.kt)


Thank you!

**Comment by nischaysingla** [comment]
> ThomasGorisse

Hi @ThomasGorisse,

Thanks for your reply,
I tried what you have suggested.

Issue is when i try to create ModelInstance second time from same Model object by calling createInstance() it throws following native exception:

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x202a205d355c82 in tid 23572 (eviewtoggleimpl), pid 23572 (eviewtoggleimpl) pid: 23572, tid: 23572, name: eviewtoggleimpl  >>> com.labs.flipkart.sceneviewtoggleimpl <<< #00 pc 00000000001aead8  /data/app/~~kFK37XCDJC1p2CdyXYwlmw==/com.labs.flipkart.sceneviewtoggleimpl-_Vb_L4qyYmSsRVsiK_A29w==/base.apk!libgltfio-jni.so (offset 0x4ca000) (BuildId: ec46e810f55a650db8db54a45bb6d6b35dde0180)

Please find the complete code [here](https://github.com/nischaysingla/SceneViewToggleImpl/blob/master/app/src/main/java/com/labs/flipkart/sceneviewtoggleimpl/MainActivity.kt)

Also below code always returns null when called outside doOnAttachedToScene

GLBLoader.loadModel(
this@BlackActivity,
"LRCFZ6CEGGHUTA4G.glb"
)

Have a look [here](https://github.com/nischaysingla/SceneViewToggleImpl/blob/master/app/src/main/java/com/labs/flipkart/sceneviewtoggleimpl/BlackActivity.kt)

Thank you!

**Comment by nischaysingla** [comment]
Hi @ThomasGorisse Please have a look at above response, thanks in advance
