### ISSUE TITLE
Node Touch Event

### ISSUE THREAD

**Issue by candyman15** [SceneView/sceneview-android#235]
hi
I am using sceneview very well and appreciate it.

I have one problem.
It is that I am not getting the event when an ArNode is touched. 

ArNode has an onTap function, but it is not executed on touch.

So when I press the onTap and onTapAr functions in sceneview, the event is fired, but in the case of onTapAr, the node gets a null value. So it's currently hard to tell which node was touched. 

Maybe I'm doing it wrong,
or if the method has changed with each version?

Please share your method.

**Comment by kiler222** [comment]
According to the [onTapAr documentation](https://sceneview.github.io/api/sceneview-android/arsceneview/io.github.sceneview.ar/-ar-scene-view/on-tap-ar.html?query=var%20onTapAr:%20(hitResult:%20HitResult,%20motionEvent:%20MotionEvent)%20-%3E%20Unit?%20=%20null) that listner is only invoked if "no node" is tapped. So it fires only if trackable (Plane, InstantPlacementPoint, DepthPoint) is touched.

Regarding the `onTap` it works for me. It will be easier to help you if you share your code.
