### ISSUE TITLE
Filament material not cleaning up properly and causes app to crash

### ISSUE THREAD

**Issue by morhenny** [SceneView/sceneview-android#24]
I have been running into an issue, where my app will crash after navigation from and back to my AR Fragment multiple times.

It seems to me, that the Filament material of the plane renderer is not getting cleaned up properly when my fragment is destroyed. 

Confusing to me is the fact, that it does not crash when opening it after closing just once, but usually after at least 3 and up to 6 times of navigating out and back into the fragment. Additionally, it doesn't crash instantly onCreate of my fragment, but rather after around 1-3 seconds of working normally.
 
`E/Filament: in bool filament::FEngine::destroy(const filament::FMaterial *):810`
   `reason: destroying material "AR Core Plane Material" but 4 instances still alive`
 [...]
 `java.lang.IllegalStateException: Object couldn't be destroyed (double destroy()?)`

It seems to crash for both the "AR Core Plane Material" and the "AR Core Plane Shadow Material", as I have had either in my stacktraces. This is one of these stacktrace: [https://pastebin.com/z8Bq35du](https://pastebin.com/z8Bq35du )

I couldn't find anything from sceneview to call onDestroy of my fragment to solve this, so I was hoping for some help here.

**Comment by morhenny** [comment]
I've created a small [sample](https://github.com/morhenny/sceneview_issue_sample) project to recreate the issue, for which I have been using my local sceneview snapshot that is based on the current master branch.


To recreate the issue with this app, just navigate to the AR fragment by using the button, then go back and navigate to the Ar Fragment again and wait.

Despite what I said originally if I just wait long enough after opening it the 2nd time it will also crash. Closing and opening the fragment more than that just seems to accelerate it.

**Comment by ThomasGorisse** [comment]
It's a filament `destroy()` call issue. This can happen if SceneView is telling Filament to destroy a resource still in use or already destroyed or if SceneView is trying to use a destroyed resource.
We didn't try/catch it in order to find the places where they shouldn't be called and you actually found one of them.

In this case, this is due to a mix of the old resource releasing system and the new lifecycle aware one (every used resource are destroyed at the `SceneView` destroy time=fragment `onDestroy()`). This is also due, to a wrong material caching implementation.
I will fix it and push. Please tell us if it's solved.

**Comment by morhenny** [comment]
Your fix seems to have resolved the issue for me, thank you very much!

**Comment by bankbiz** [comment]
I still got destroying material error on SceneView 0.9.0 while navigation from and back.

`2022-12-07 20:41:52.259 18346-18346 native       com.myapp            I  I0000 00:00:1670420512.259118   18346 session_lite_c_api.cc:39] Deleted ArSession.
2022-12-07 20:41:52.267 18346-18346 Filament    com.myapp             E  in destroy:959 reason: destroying material "base_lit_opaque" but 3 instances still alive
2022-12-07 20:41:52.267 18346-18346 Filament    com.myapp             E  
2022-12-07 20:41:52.276 18346-18346 libc             com.myapp             A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6d0 in tid 18346 (myapp), pid 18346 (myapp)`

Does anyone have the same issue?
