### ISSUE TITLE
ArSceneView 0.9.8 breaks adding ViewRenderables

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#245]
ArSceneView 0.9.7 broke updating a ViewRenderable. Now ArSceneView 0.9.8 completely breaks a ViewRenderable being added to a ViewNode which is added to an ArNode.

Are there any examples of attaching a ViewRenderable (of an Android View) to a ViewNode and then adding it to an ArNode?

**Comment by ryust** [comment]
Yes, I am still on 0.9.7 because of the 0.9.8 problem. On Apr 26, 2023 3:51 AM, Pawel Jobkiewicz ***@***.***> wrote:
You can use a ViewNode without a ViewRenderable, but you have to use ArSceneView 0.9.7. I tested adding the ViewNode to an ArModelNode and it works.

**Comment by sameerjj** [comment]
I'm experiencing the same issue with 0.9.8

**Comment by hshapley** [comment]
I don't have this issue with 0.9.9. I didn't test it with 0.9.8.

**Comment by ryust** [comment]
It all works now with 0.9.9 in my testing. This issue can be closed.

**Comment by ThomasGorisse** [comment]
Thanks for the check @ryust
