### ISSUE TITLE
Model Viewer with Jetpack Compose

### ISSUE THREAD

**Issue by gauravbiyani033** [SceneView/sceneview-android#252]
Hi, I was trying to build the model viewer in samples using jetpack compose. This is the composable I have written so far

```
fun XRScene(
    hdrFilePath: String,
    modelPath: String,
    modifier: Modifier = Modifier
){
    val nodes = remember { mutableStateListOf<Node>() }
    val scope = rememberCoroutineScope()

    Box(modifier = modifier.fillMaxSize()) {
        Scene(
            modifier = modifier.fillMaxSize().border(10.dp, Color.Black),
            nodes = nodes,
            onCreate = { sceneView ->
                // Apply your configuration
                scope.launch {
                    sceneView.loadHdrIndirectLight(hdrFilePath, specularFilter = true) {
                        println("HDR Light:" + this)
                        intensity(30_000f)
                    }
                    sceneView.loadHdrSkybox(hdrFilePath){
                        println("Skybox:" + this)
                        intensity(50_000f)
                    }
                    println("Tried to apply hdr to scene")
                    val model = sceneView.modelLoader.loadModel(modelPath)!!
                    val modelNode = ModelNode(sceneView, model).apply {
                        transform(
                            position = Position(z = -4.0f, y = -0.5f),
                            rotation = Rotation(x = 5.0f)
                        )
                        scaleToUnitsCube(1.5f)
                        playAnimation(loop=false)
                    }
                    sceneView.addChildNode(modelNode)
                    nodes.add(modelNode)
                }
            }
        )
    }
}
```

The above code results in a complete blank screen

**Comment by ErfanSn** [comment]
I had a similar problem before, solutions that can help you:

- Ensure that if the Android version of your phone is above 12 disable privacy mode, which that blocks other apps from using the camera.
-  I don't know why but to notify composable that node list changed must cast it into an immutable list with `SnapshotStateList<Node>.toList()`.

**Comment by gauravbiyani033** [comment]
Thank you for the reply. For the first part, I am just using the 3D part not the camera so will that still be a problem ? I am fairly new to Jetpack Compose so can you please elaborate with a code snippet for the same

**Comment by gauravbiyani033** [comment]
Thanks again, I tried doing that but it didn't work. Is there something else I might be doing wrong ?

**Comment by gauravbiyani033** [comment]
> Thanks again, I tried doing that but it didn't work. Is there something else I might be doing wrong ?

The same code works well when I dont use Jetpack compose, also when I try to print things sceneview and modelnode are all created and model is loaded as well, its just that there is a blank screen. What could be going wrong here @ThomasGorisse @grassydragon @StevenMOG

**Comment by lo-g** [comment]
Yes, it's seems that 
```
@Composable
fun Scene(
    modifier: Modifier = Modifier,
    nodes: List<Node> = listOf(),
    onCreate: ((SceneView) -> Unit)? = null
) {
```

does not render the view

**Comment by nero240399** [comment]
you can check this issue:
https://github.com/SceneView/sceneview-android/issues/275
