### ISSUE TITLE
ArModelNode position is frozen if rotation is edited

### ISSUE THREAD

**Issue by hshapley** [SceneView/sceneview-android#254]
If an ArModelNode has `followHitPosition` set to `true`, but then the position or rotation of the node is manually edited, then the node no longer follows the hit position. I don't know why this is exactly, but it is frustrating. 
The scenario for this is pretty simple: Wanting the default behavior of `followHitPosition`, but customizing the orientation, for instance to always face the camera. Currently, that's not possible unless you set `followHitPosition` to `false` and manually do hit tests and set the node's transform.

**Comment by hshapley** [comment]
I found a solution for this: you can set the variable `applyPosePosition` (from ArNode) to `false` (`applyPoseRotation` is false by default). This allows for the `hitResult` and `pose` to be continually updated, while setting the position and rotation yourself. 
However, I will say this is very non-obvious and there is no documentation about it. Although applyPosePosition/Rotation are helpful shortcuts once you understand them, I feel like this scenario could be simplified - for instance, `hitResult` could always be updated, but `pose` is only updated if `followHitPosition == true`. That way, we could set `followHitPosition` to `false` and then set the pose we want based on the `hitResult`.

**Comment by hshapley** [comment]
There is a similarly confusing issue with `isSmoothPoseEnable`. If it's set to true (which it is by default), then a scenario as simple as this won't work:
1. Anchor the node
2. Modify the node's orientation

This is because setting `anchor` in turn sets the `pose`, which in turn calls `transform()` with `smooth=true`. As noted on line 460 of `Node`, smooth transforming is aborted if part of the transform is modified. In other words, it won't finish smoothing the position because the rotation was modified during the smooth transform. Instead of moving to the anchor position, the node will stay where it was. I feel this is also non-obvious and not documented. 
One possible solution is to have the `anchor` setter force `smooth` to be `false` when calling `transform()`, so that the node is guaranteed to move to the anchor location. Another option is to not have setting the anchor change the pose/transform of the node at all. Honestly this is pretty weird default behavior...just because a node becomes anchored doesn't mean that the node should move to the anchor.

**Comment by ThomasGorisse** [comment]
Answers: https://photos.app.goo.gl/JSxtavU684cx9vcSA
