### ISSUE TITLE
AR Placement Mode seems to not recognize wall

### ISSUE THREAD

**Issue by IssaMansour** [SceneView/sceneview-android#258]
Hello,

I'm trying the AR Placement Mode sample, and I feel there is something different compare to the video available in the README.

This is what I got:
![Screenshot_20230426-174128](https://user-images.githubusercontent.com/841028/234710076-d04dd437-211d-4e11-a83c-9260f9a08fe2.png)

And this is what I can see on the video when aiming a wall:
<img width="497" alt="Screen Shot 2023-04-26 at 5 47 29 PM" src="https://user-images.githubusercontent.com/841028/234710287-5398a43f-fb80-400e-8d84-0885d4cae95e.png">

Is it because my wall is too white? 
Or do I need to write more code in the sample project to have the same result?

Thanks!

**Comment by IssaMansour** [comment]
Any idea @ThomasGorisse?

**Comment by Stefterv** [comment]
My experience is the lack of texture on your wall is indeed the cause of ARCore not being able to recognise it.

**Comment by IssaMansour** [comment]
> My experience is the lack of texture on your wall is indeed the cause of ARCore not being able to recognise it.

Also, I tried with the ARCore Depth Lab app from the Play Store, and it was working properly on the same wall.
Did you try the AR Placement Mode sample, did it work for you?

cc. @ThomasGorisse
