### ISSUE TITLE
Error when trying to destroy ARSceneView

### ISSUE THREAD

**Issue by gauravbiyani033** [SceneView/sceneview-android#266]
Hi, I am creating an app which has a 3d model viewer and AR which can be toggled. Switching from 3D to AR works fine but when I switch back from AR to 3D, I receive the following error: 
<img width="1170" alt="Screenshot 2023-05-23 at 7 49 09 AM" src="https://github.com/SceneView/sceneview-android/assets/67905186/2464ca3f-a23e-43df-b09c-0ab801ccc673">

My code flow is as follows:
-> First I download bytebuffers for both HDR and GLB from their respective urls
-> Then I have created two separate fragments for both 3D and AR and use a fragment manager to toggle between these two views
-> In each of the fragments, I create the model using GLBLoader.createModel(buffer)

**Comment by cryptowizard** [comment]
I am having the same issue

**Comment by gauravbiyani033** [comment]
There is some issue with planeRenderer.destroy() method so I disabled it by using planeRenderer.isEnabled = false. This solved it for me
