### ISSUE TITLE
Model scale causing unexpected height increase above the surface

### ISSUE THREAD

**Issue by itssidhere** [SceneView/sceneview-android#278]
Description:

I encountered an issue while using ArSceneView in Android, where changing the scale of a model using the scale property also causes the model to move upwards from the surface. This behavior is not desirable, as I would expect the model to maintain its position while only changing its scale. It happens with scaleToUnits parameter

Steps to Reproduce:

Initialize the SceneView and load a model.
Set the scale of the model using the scale property with a scale like Scale(100f,100f,100f)
Observe that the model not only scales but also moves upwards from the surface.
Expected Behavior:

When modifying the scale of the model, it should maintain its position relative to the surface, without any unexpected upward movement.

Actual Behavior:

The model moves upwards from the surface when its scale is changed using the scale property in SceneView.

**Comment by ThomasGorisse** [comment]
Your model might not be centered when you exported it.
You can modify your glTF or set the
`centerOrigin = Position(0.0f)` (same as geometry to cursor in Blender)

**Comment by itssidhere** [comment]
Thank you @ThomasGorisse I will try that. I have tried to scale every model in the example provided and it had the same issue.

**Comment by itssidhere** [comment]
Hi @ThomasGorisse 

I am  trying to change the scale of the model dynamically like 

```
Slider(
    value = scale,
    valueRange = 0.1f..10f,
    onValueChange = {
        scale = it
        modelNode?.scale = Scale(scale, scale, scale)
    },
    modifier = Modifier
        .fillMaxWidth()
        .padding(horizontal = 16.dp)
)

```

But doing so changes the position of the model too, I just want the surface to remain the same while the model continues to scale however it moves away from the original position

**Comment by ThomasGorisse** [comment]
You can try `modelNode.modelScale` but I don't get what you want. Your video has the standard scaling behavior.

**Comment by itssidhere** [comment]
@ThomasGorisse Thank you I combined the `centerOrigin = Position(0.0f)` with `modelNode.position` to get closer to the desired behaviour
