### ISSUE TITLE
Rendering on a TextureView

### ISSUE THREAD

**Issue by Roman-hub** [SceneView/sceneview-android#281]
Hi guys, first of all, want to preface this by saying thanks to everyone contributing to this awesome project.
I wanted to ask if it is possible to render on a TextureView? I can't use SurfaceView in my project unfortunately.
Any help would be much appreciated.

**Comment by tukez** [comment]
We need this too. TextureView allows changing the order of video views, for example to show one video in the background and other picture in picture style on top (and then changing them order back and forth). There might be another way to achieve this without TextureView?

**Comment by yschimke** [comment]
I think it's still an open request.
