### ISSUE TITLE
Is ar-augmented-image sample currently working?

### ISSUE THREAD

**Issue by Kang-Dongyoung** [SceneView/sceneview-android#285]
Is ar-augmented-image sample currently working?
I tried it on my device but video.png and rabbit.png are empty files and video url seems to be not working anymore.

If I want to implement augmented image, should I use sceneform-android instead?

**Comment by tjsearsz** [comment]
Same comment.

I wanted to check whether the code works by copy/pasting one of the .glb files from the other examples and changing the code of the "qrcode.png" to call this .glb file instead and it worked. This basically means they need to fix this empty files and put that URL on back again.

**Comment by AnByronV** [comment]
Hi @tjsearsz, but can you see the video in Ar?

**Comment by Kang-Dongyoung** [comment]
@ThomasGorisse hi, thank you for constantly updating. Could you please provide feedback to this? Have a great day.

**Comment by tjsearsz** [comment]
Hello @AnByronV 

I haven't tried with videos yet. However, I see that the URLs are back again, so I believe it should work.

The only thing missing part of this example is to add the images. In the meantime, what you could do is to import one random image into the project and then change the name of that image in the code that is being used for the video.

**Comment by PixelsteinLangenselbold** [comment]
I was able to get it work by overwriting the images with some of my own. In general it's working but it is not updating the position of the glb model when I rotate the marker the 3D object (spoons) are sometimes rotated but mostly in random directions. I thought that I could place a virtual image exactly above the marker but that is impossible if it doesn't track the right orientation and coordinates of the augmentedImage. 
Also sometimes the spoons seems to loose their anchor and keep moving with the camera at least on one axes.

**Comment by tjsearsz** [comment]
@PixelsteinLangenselbold  Glad to know that you were able to make it work :smiley: 

> In general it's working but it is not updating the position of the glb model when I rotate the marker the 3D object (spoons) are sometimes rotated but mostly in random directions

What you are saying is that when you rotate the market the spoons (3D Object) still keep the same position they were initially detected right? That happens to me. Maybe there is a missing flag/configuration?

**Comment by PixelsteinLangenselbold** [comment]
Yes right, it finds the image and places the object "somewhere"

**Comment by ThomasGorisse** [comment]
@Kang-Dongyoung , @tjsearsz and @PixelsteinLangenselbold Could you share some screen records?

**Comment by Kang-Dongyoung** [comment]
Hi @ThomasGorisse , I am attaching the images of my result.
![20230725_114011](https://github.com/SceneView/sceneview-android/assets/100178260/6a640d9d-6038-414b-8fc3-76e555ae2b6e)
target image to detect
![Screenshot_20230725_113927_AR Augmented Image](https://github.com/SceneView/sceneview-android/assets/100178260/1d598c58-0e02-4905-bfb2-e35775d99858)
result

Things I've done to make this work
- replace empty image with my own
- replace video url
- replace empty plane.glb that VideoNode.kt is referring to with non-empty plane.glb file from sceneform augmented image sample

Problem
- image detecting and video playing works but video does not align properly with target image in terms of size, orientation.
