### ISSUE TITLE
Screenshot of ARfragment or ARSceneView are resulting in black images

### ISSUE THREAD

**Issue by PixelsteinLangenselbold** [SceneView/sceneview-android#286]
I'm facing a difficult problem when trying to take a screenshot of an ARfragment or ARSceneView or even the whole view. 
Everything that belongs to the user interface is inside the screenshot image but instead of the camera image with rendered objects (which I can see on my display) I'm getting a black screen. 

This is how I'm talking my screenshots: 

 `
val bitmap = takeScreenShot(arSceneView)

private fun takeScreenShot(view: View): Bitmap {
        backButton!!.visibility = GONE
        val thescreenshot = Bitmap.createBitmap(view.width, view.height, Bitmap.Config.ARGB_8888)
        val draw = Canvas(thescreenshot)
        val drawGeeks = view.background
        if (drawGeeks != null) drawGeeks.draw(draw)
        else draw.drawColor(android.graphics.Color.BLUE)
        view.draw(draw)

        return thescreenshot
   }

`

The Bitmap is shown on an image view afterwards.

**Comment by Roman-hub** [comment]
You need to use PixelCopy API in order to take a screenshot of a SurfaceView. Here's an example: https://github.com/SceneView/sceneform-android/discussions/134
