### ISSUE TITLE
ArNodeManipulator + CameraManipulator (Filament Manipulator)

### ISSUE THREAD

**Issue by StevenMOG** [SceneView/sceneview-android#29]
I'd like to have an ARModelNode that can be moved and rotated using gestures.
I guess I can't use the ARModelNode directly as the TransformableNode needs a ArNode as its parent. The way to go would be this node hierachy:

- ArNode
  - TransformableNode
    - ModelNode  

This results in my model rotating around the anchor instead of rotating around itself.
Could you help me to achieve the right result?

Thanks!

**Comment by ThomasGorisse** [comment]
Hi.

I have to say that we didn't had time yet to move the old Sceneform `TransformableNode` to a Kotlin SceneView version.
So it might be a little tricky to use it with the new ArModelNode.

> This results in my model rotating around the anchor instead of rotating around itself.

Why isn't your model node at the same origin as the anchor?
Can you share a screen record and some code?

**Comment by StevenMOG** [comment]
Yes, sure! This is the minimal version of my current approach:
` sceneView.onTouchAr = { hitResult, motionEvent ->
            val trackable = hitResult.trackable
            if (trackable is Plane && trackable.isTracking) {
                launch(Dispatchers.Main) {
                    val arNode = ArNode(hitResult.createAnchor())
                    val transformableNode =
                        TransformableNode(sceneView.nodeGestureRecognizer)
                    val modelNode = ModelNode()
                    modelNode.loadModel(androidContext, "lp.glb")
                    arNode.addChild(transformableNode)
                    transformableNode.parent = modelNode
                    transformableNode.addChild(modelNode)
                    sceneView.addChild(arNode)
                }
            }
        }`
This is a video of the result:
https://user-images.githubusercontent.com/97528052/156728059-218f764f-759e-4dd3-8269-47a050b31c5f.mp4

**Comment by ThomasGorisse** [comment]
Your issue comes from the fact that your model is not centered at is origin.
You can modify your source model or use the `centerOrigin` parameter when loading it:
```kotlin
modelNode.loadModel(
    context = requireContext(),
    glbFileLocation = "lp.glb",
    autoAnimate = true,
    autoScale = true,
    centerOrigin = Position(x= 0.0f, y = 0.0f, z=0.0f)
)
```

**Comment by ThomasGorisse** [comment]
`autoScale` parameter will scale the model to fit inside a unit cube so 1 meter in case of AR.
Set it to `false` if you want your model to keep its original size or `true` if your want your model to fit inside the screen.

**Comment by StevenMOG** [comment]
Thanks! But changing is to:
```
sceneView.onTouchAr = { hitResult, motionEvent ->
            val trackable = hitResult.trackable
            if (trackable is Plane && trackable.isTracking) {
                launch(Dispatchers.Main) {
                    val arNode = ArNode(hitResult.createAnchor())
                    val transformableNode =
                        TransformableNode(sceneView.nodeGestureRecognizer)
                    val modelNode = ModelNode()

                    arNode.addChild(transformableNode)
                    transformableNode.addChild(modelNode)
                    sceneView.addChild(arNode)
                    modelNode.loadModel(androidContext, "lp.glb", centerOrigin = Position(x = 0.0f, y = 0.0f, z = 0.0f))
                }
            }
        }
```
doesn't change anything. 
When using ArModelNode directly (also without centerOrigin) the model is shown at the selected position in its original size (The sofa 3D model has the size of the original one).
```
val arNode = ArModelNode(hitResult)
sceneView.addChild(arNode)
arNode.loadModel(androidContext, "lp.glb")
```

**Comment by ThomasGorisse** [comment]
So the `TransformableNode` has to be moved to SceneView and directly at the `Node` level with an `isEditable : boolean = false`.
Would you try to do it inside SceneView?

**Comment by StevenMOG** [comment]
I'll give a try. I guess rotation and scaling can be done in SceneView but translation needs to create new Anchors so I'll move it to ArSceneView. If it works out I'll create a PR.

**Comment by ThomasGorisse** [comment]
That's it. Great analysis.

**Comment by ThomasGorisse** [comment]
Linked: https://github.com/SceneView/sceneview-android/issues/6

**Comment by grassydragon** [comment]
I'm closing this issue since the changes have been already merged and I'll create new issues for the problems related to the transformation and collision systems.
