### ISSUE TITLE
Incorrect conversion of 3D model position to 2D coordinates in sceneView

### ISSUE THREAD

**Issue by NohaSamir** [SceneView/sceneview-android#290]
I am encountering an issue with the conversion of the position of 3D models to 2D coordinates in the sceneView.

Here are the details of my environment:

The sceneView size is 1080x2148, and the Scene worldSize is defined as Float3(x=0.21548285, y=4.626002, z=-8.876022).
My sceneView contains two models.
- The first model is positioned at Float3(x=0.0, y=0.0, z=0.0) in the 3D world.
- The second model is positioned at Float3(x=1.0, y=1.0, z=1.0) in the 3D world.

When I try to convert the 3D position of the first model to 2D, it returns the expected result:
```
val firstModelPosIn2D = sceneView.worldToView(firstModel.position)
// The result is Float3(x=540.0, y=1074.0, z=0.5), which is the correct position.
```

However, when I try to do the same for the second model, it returns incorrect 2D coordinates:
```
val secondModelPosIn2D = sceneView.worldToView(secondModel.position)
// The result is Float3(x=-3519.2031, y=3861.7358, z=5.674519), which is not the expected position.
```
The output for the second model's position appears to be erroneous as the values do not correspond to any valid position within the sceneView dimensions. Can you please help me understand if this is an issue with the library or if there's something I'm missing in the conversion process?

**Comment by grassydragon** [comment]
Hi!
Yes, looks like there is a redundant multiplication by the projection matrix in this method:

https://github.com/SceneView/sceneview-android/blob/dc01ef79a0979c0a2ab4e68c0d9c7dff02e75d9f/sceneview_1_0_0/src/main/java/io/github/sceneview/scene/Camera.kt#L143

**Comment by NohaSamir** [comment]
Thanks @grassydragon, 

It does not have a redundant multiplication by the projection matrix, Maybe you link a wrong line. Please can you double check it ?

**Comment by NohaSamir** [comment]
I get what you mean but when I try it, it return wrong values for both points

For the center point, Float3(x=0.0, y=0.0, z=0.0) >> it return Float3(x=NaN, y=NaN, z=-Infinity)
For Float3(x=1.0, y=1.0, z=1.0) >> it return Float3(x=-26060.0, y=27739.998, z=10.5)

**Comment by grassydragon** [comment]
Probably, I need to experiment with the code myself to see if anything else is wrong.

**Comment by NohaSamir** [comment]
Hi @grassydragon 
Hope you are doing well. Did you have a chance to check it?

**Comment by grassydragon** [comment]
Hi!
Yes, I took a look last weekend and got the same result as you. I'll give it another go and try to find the error this weekend.

**Comment by grassydragon** [comment]
Hi @NohaSamir!
I've finally found the time to resolve the issue :tada:
