### ISSUE TITLE
Crash on creating Geometry

### ISSUE THREAD

**Issue by Takexito** [SceneView/sceneview-android#292]
I tried to create Plane with below code
``` kotlin
Plane.Builder(size = Float3(20f, 20f, 1f), center = Float3()).build()
```

I got an exception on startup it. 
``` kotlin
kotlin.UninitializedPropertyAccessException: lateinit property vertices has not been initialized
    at io.github.sceneview.geometries.Geometry.getVertices(Geometry.kt:65)
    at io.github.sceneview.geometries.Geometry$BaseBuilder.build(Geometry.kt:154)
    at io.github.sceneview.geometries.Geometry$BaseBuilder.build(Geometry.kt:159)
```

Looks like a problem with `BaseBuilder<T : Geometry>` inside `Geometry`.

BaseBuilder contains the following code
``` kotlin
abstract class BaseBuilder<T : Geometry> internal constructor(
        var vertices: List<Vertex> = listOf(),
        var submeshes: List<Submesh> = listOf()
    ) {

        fun vertices(vertices: List<Vertex>) = apply { this.vertices = vertices }
        fun submeshes(submeshes: List<Submesh>) = apply { this.submeshes = submeshes }

        open fun build(engine: Engine): T {
            val vertexBuffer = VertexBuffer.Builder().apply { … }.build(engine)

            // Determine how many indices there are
            val indexBuffer = IndexBuffer.Builder().apply {
                indexCount(submeshes.sumOf { it.triangleIndices.size })
                    .bufferType(IndexBuffer.Builder.IndexType.UINT)
            }.build(engine)

            return build(vertexBuffer, indexBuffer).apply {
                setBufferVertices(engine, vertices)
                setBufferIndices(engine, submeshes)
            }
        }

        fun build() = build(Filament.engine)

        internal abstract fun build(vertexBuffer: VertexBuffer, indexBuffer: IndexBuffer): T
    }
```

On return from `open fun build(engine: Engine): T` it applies the buffers
``` kotlin
 setBufferVertices(engine, vertices)
 setBufferIndices(engine, submeshes)
```
but the `vertices` and `submesh` arguments refer to the fields inside T created by the `build(vertexBuffer, indexBuffer)` function, not the `BaseBuilder` fields with the same name

**Comment by romasworld** [comment]
I am experiencing the same issue when creating any primitive from `io.github.sceneview.geometries`. The error occurs every time I attempt to do so. If there's any workaround or fix for this, please let me know. Thank you for your attention to this matter.

**Comment by itssidhere** [comment]
Just an out-of-context question, how do you place the geometry into the ArSceneView ?

**Comment by PixelsteinLangenselbold** [comment]
I didn't find a workaround so I needed to build my geometries in blender als glb files and import them which leads to a lot of work in my project. I would be very happy to get this solved soon.

**Comment by johnwhh** [comment]
> I didn't find a workaround so I needed to build my geometries in blender als glb files and import them which leads to a lot of work in my project. I would be very happy to get this solved soon.

@PixelsteinLangenselbold 
Have you tried passing the `sceneView` instance to the `build` method on `Plane.Builder`?

I'm able to create a plane using this code:
```
val geometry = Plane.Builder(
            size = Size(
                x = 10f,
                y = 10f
            )
        )
            .build(sceneView)
```
