### ISSUE TITLE
How to swap image Texture of an ArModelNode

### ISSUE THREAD

**Issue by PixelsteinLangenselbold** [SceneView/sceneview-android#294]
Hi everyone, great to see that you are keeping this wonderful package up and running! 

I want to change the texture of a glb file I've successfully loaded into my ARscene as an ArModelNode.
When looking into your PlaneRenderer I see that you are doing something similar but you are creating a material with this filamat file "plane_renderer_shadow.filamat" 
I was wondering if I could just create a material like 

`val material = Material.Builder().build()
`
then loading a texture file: 
`val texture = TextureLoader.createImageTexture(context!!, textureLocalURL.toString(), TextureLoader.TextureType.COLOR)
`

and after that I was trying to set this texture to the defaultInstance of that material:
`material.defaultInstance.setTexture("myTexture", texture)
`

and then adding the material instance to my loaded ArModelNode with my glb file:
`modelNode.setMaterialInstance(material.defaultInstance)`

Unfortunately all I get back is a huge error stack: 
`JNI DETECTED ERROR IN APPLICATION: JNI CallStaticIntMethodV called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.nio.Buffer.hasArray()' on a null object reference
    java_vm_ext.cc:594]   at java.lang.Object com.google.android.filament.NioUtils.getBaseArray(java.nio.Buffer) (NioUtils.java:54)
    java_vm_ext.cc:594]   at long com.google.android.filament.Material.nBuilderBuild(long, java.nio.Buffer, int) (Material.java:-2)
    java_vm_ext.cc:594]   at long com.google.android.filament.Material.-$$Nest$smnBuilderBuild(long, java.nio.Buffer, int) (Material.java:-1)
    java_vm_ext.cc:594]   at com.google.android.filament.Material com.google.android.filament.Material$Builder.build(com.google.android.filament.Engine) (Material.java:334)
    java_vm_ext.cc:594]   at com.google.android.filament.Material io.github.sceneview.material.MaterialKt.build(com.google.android.filament.Material$Builder) (Material.kt:6)
    java_vm_ext.cc:594]   at void com.example.hanautours.ARFragment.addSceneComponent(com.example.hanautours.models.SceneComponent, io.github.sceneview.ar.node.ArModelNode, dev.romainguy.kotlin.math.Float3) (ARFragment.kt:367)
    java_vm_ext.cc:594]   at void com.example.hanautours.ARFragment.addSceneComponent$default(com.example.hanautours.ARFragment, com.example.hanautours.models.SceneComponent, io.github.sceneview.ar.node.ArModelNode, dev.romainguy.kotlin.math.Float3, int, java.lang.Object) (ARFragment.kt:350)
`

**Comment by johnwhh** [comment]
You probably need to pass the `sceneView` instance to the `build` method which is an extension function defined [here](https://github.com/SceneView/sceneview-android/blob/961b47f8399153ea964a827ddf5f869370b484c9/sceneview_1_0_0/src/main/java/io/github/sceneview/material/Material.kt#L58).

Also try calling the `createInstance(sceneView:name:)` method on the `material` instead of using `defaultInstance`.

**Comment by PixelsteinLangenselbold** [comment]
At first this seems to be the right direction but then I realized that this is sceneview_1_0_0 which seems not to be available when I use

`dependencies {
    // 3D and ARCore
    implementation 'io.github.sceneview:arsceneview:0.9.10'
}`

There is no Material.kt that I can import into my class.
