### ISSUE TITLE
How to show shadow of a model using ArSceneView?

### ISSUE THREAD

**Issue by Devansh-Maurya** [SceneView/sceneview-android#318]
I have a model of a card and I want to show the shadow of it when it is placed on a plane. Without the shadow, the model appears floating in space even when placed on a plane. I tried setting `setCastShadows(true)` and `setReceiveShadows(true)` on the model node but this does not seem to have any effect.

What can be done to show the shadows? Is there any sample app anywhere that achieves this effect?

**Comment by pablojoseoroz** [comment]
Hi @Devansh-Maurya, I neither can realized this, any solution? thx

**Comment by ryust** [comment]
I've never gotten shadows to work either.
