### ISSUE TITLE
How to get selected node

### ISSUE THREAD

**Issue by DeemAQ** [SceneView/sceneview-android#328]
Hi, I asked many times on the discord server but it seems the community is inactive. I'm hoping I'll get my answer here.
How can I get the selected AR node? I have a list of AR model nodes on the screen, and I want to click/tap on a node to make it the "selected node" and a bunch of control options related to this node will appear when selected.
I tried sceneView.selectedNodes but it didn't work, and I didn't really understand onTap function (I wasn't able to find any helpful documentation).

@grassydragon @RGregat @ThomasGorisse

**Comment by grassydragon** [comment]
Hi!
When the `SceneView` is tapped, the `onTap` method is called with a `Node` that is under the touch point and this `Node` is selected. However, currently it's only possible to select `Node`s that have opaque materials.

**Comment by DeemAQ** [comment]
> Hi!
> When the `SceneView` is tapped, the `onTap` method is called with a `Node` that is under the touch point and this `Node` is selected. However, currently it's only possible to select `Node`s that have opaque materials.


Thanks for the reply! 
All of my nodes are opaque. I'm currently using the onTap in ARScene function to place the model on the screen (just like the ecommerce PR). How can I use sceneView's onTap function?
