### ISSUE TITLE
model-vewer panic: “Texture format 40 is not mipmappable.”

### ISSUE THREAD

**Issue by KevinCain** [SceneView/sceneview-android#329]
[The SceneView sample.model-viewer for Android](https://github.com/SceneView/sceneview-android) compiles in Android Studio and runs fine for me on Pixel 7 but halts early in execution on Magic Leap 2 (which also runs Android). Logcat notes a panic @ ‘generateMipmaps:396’ for the reason that “Texture format 40 is not mipmappable.”

Note that this happens when trying to load any file, from a plane to a point cloud to the sample's included 'MaterialSuite.glb'. In fact, the error appears to happen before the model is loaded.

Is there perhaps a way to turn off mipmapping?

I see the same error in 'samples.ar-model_viewer', for what it's worth.

**Comment by ThomasGorisse** [comment]
Hi.
Could you please try to disable the light estimation?

**Comment by KevinCain** [comment]
Thanks @ThomasGorisse for a good suggestion. I ventured a naive approach to disable light estimation, adapted from the ARSceneView context: 

`sceneView.lightEstimationConfig = LightEstimationConfig.DISABLED`

The above isn't supported as written and I couldn't find a parallel call for 'sceneView.lightManager' or 'sceneView.lightNode'.

However, simply disabling the HDR indirect light and skybox did the trick, although now when tumbling the object view I see 'smearing' from as the previous render is persistent beneath the new rendered frame.

**Comment by ThomasGorisse** [comment]
I'm pretty interested in what you're doing.
Could you share some screen record?

**Comment by KevinCain** [comment]
[This video clip](https://photos.app.goo.gl/qvCwQPTLBVShQS6r6) shows what I see when running the sample model viewer on the Magic Leap 2. You'll see me twirling the model using the AR controller, and the persistent rendering background I noted.

Running the same binary several times, sometimes it hangs on launch and sometimes it works as shown -- it's not consistent, so any further help with disabling light estimation would be welcome.

**Comment by KevinCain** [comment]
While I can run the SceneView demo with arbitrary .glb models, I still see errors in logcat that cause segfaults, though strangely only after a few launch cycles!

I see a compilation error in fragment shader "view":
"0:107(13): error: no matching function for call to `texture(samplerExternalOES, vec2, float)'; candidates are:
                                                                                                    0:107(13): error:    vec4 texture(sampler1D, float)

Since that shader fails to compile, it also fails to link with: "error: linking with uncompiled/unspecialized shader"

I see SceneView is using GLSL ES 3.20, which apparently has a different call structure than the above. Would changing the GLSL version help, and if so how can I do that?

In Logcat Filament  reports: sceneview.sample.modelviewer  V  [X.Org], [AMD MERO (DRM 3.37.0, 5.4.19-android-x86_64, LLVM 10.0)], [OpenGL ES 3.2 Mesa 20.1.2 (git-2a070a5e21)], [**OpenGL ES GLSL ES 3.20**]

**Comment by KevinCain** [comment]
I've tried to poll the GLSL version supported on the Magic Leap 2 Android device with the following Kotlin code, but I may be doing it wrong as I get a null string back. See below, I have that outcome report 'Unable to retrieve the supported GLSL version." to Logcat:

```
import android.opengl.GLES30
import android.util.Log

// ...

val glslVersion: String? = GLES30.glGetString(GLES30.GL_SHADING_LANGUAGE_VERSION)
if (glslVersion != null) {
    Log.d("GLSL_VERSION", "Supported GLSL version: $glslVersion")
} else {
    Log.d("GLSL_VERSION", "Unable to retrieve the supported GLSL version.")
}

```
