### ISSUE TITLE
Cannot load GLB model in ArScene composable - app crashes

### ISSUE THREAD

**Issue by GerganaT** [SceneView/sceneview-android#338]
Hello team,

I've been trying to load GLB model for some days now and I can't seem to make it work. I have read a lot of documentation but nothing works so far. Could you please view my code and let me know where am I mistaken?
Thanks a lot beforehand!

```
@Composable
fun MyArScene(
) {
    val context = LocalContext.current
    val nodes = remember {
        mutableStateListOf<ModelNode>()
    }
    val coroutineScope = rememberCoroutineScope()

    ARScene(
        modifier = Modifier.fillMaxSize(),
        childNodes = nodes.toSet(),
        planeRenderer = true,
        onCreate = { arSceneView ->
            coroutineScope.launch {
                ModelLoader(
                    arSceneView.engine,
                    context,
                ).loadModelAsync(
                    fileLocation = context.getResourceUri(R.raw.myModel),
                    resourceResolver = { "myModel.glb"},
                    onResult = { model ->
                        model?.let {
                            nodes.add(
                                ModelNode(
                                    modelInstance = it.instance,
                                    autoAnimate = true,
                                    scaleToUnits = 0.5f,
                                    centerOrigin = Position(y = -1.0f)
                                )
                            )
                        }
                    })
            }
            arSceneView.configureSession { session, config ->
                config.depthMode = Config.DepthMode.AUTOMATIC
                config.instantPlacementMode = Config.InstantPlacementMode.LOCAL_Y_UP
                config.lightEstimationMode = Config.LightEstimationMode.ENVIRONMENTAL_HDR
                config.planeFindingMode = Config.PlaneFindingMode.HORIZONTAL
            }
        },
    )
}
```

**Comment by ThomasGorisse** [comment]
Hi.
I'm actually working on the Composable part to make it more standard.
Could you please create a PR here with a new sample named `ar-model-viewer-compose` that is based on the same sample common app theme?
This would make me gain time in testing.
Thanks

**Comment by Takexito** [comment]
Hi,

It seems you haven't specified the exact issue with your example. Is the model not showing up on the scene or is there another problem?

If the model isn't appearing, here's a solution that worked for me:
Inherit from ArModelNode and override the isVisibleInHierarchy as follows:
```kotlin
override val isVisibleInHierarchy: Boolean
        get() = parentNode?.isVisibleInHierarchy != false
```

It appears there might be an issue related to the isCameraTracking within the isVisibleInHierarchy property of ArNode:
```kotlin
    override val isVisibleInHierarchy: Boolean
        get() = super.isVisibleInHierarchy && isCameraTracking
```

**Comment by ThomasGorisse** [comment]
https://github.com/SceneView/sceneview-android/blob/main/samples/ar-model-viewer-compose/src/main/java/io/github/sceneview/sample/armodelviewer/compose/MainActivity.kt#L52-L101

**Comment by ThomasGorisse** [comment]
In your local model case, you can directly call those 2 NOT suspend functions:

https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/loaders/ModelLoader.kt#L67-L87

**Comment by GerganaT** [comment]
Thank you - the issue has been resolved by updating to the latest version.

**Comment by ThomasGorisse** [comment]
Fixed https://github.com/SceneView/sceneview-android/commit/815f6a35befc6cdfcd321f2c2143940f6c97ef4b
