### ISSUE TITLE
How to load custom light in ArSceneView?

### ISSUE THREAD

**Issue by GerganaT** [SceneView/sceneview-android#340]
Is there anything like SceneView's `loadHdrIndirectLight`  but for `ArSceneView`? My model looks quite dark even with `Config.LightEstimationMode.ENVIRONMENTAL_HDR`.

**Comment by GerganaT** [comment]
I have found some light effect within the `ARScene` composable and tried this code : ` mainLight = rememberMainLight(engine, creator = {
            LightNode(
                engine = engine,
                builder = LightManager.Builder(LightManager.Type.SUN)
            )
        }),` but my model is still quite dark - I want to illuminate the model completely to look like this for example:
![image](https://github.com/SceneView/sceneview-android/assets/51824954/862ae6d9-c20b-4cb1-9f95-ffee6e3cf8da)

**Comment by GerganaT** [comment]
The issue was resolved by updating the library to the latest version.

**Comment by ThomasGorisse** [comment]
https://github.com/SceneView/sceneview-android/commit/d2bfbfc82643316ff4bbba975b3a4a4ccdfa84e9
