### ISSUE TITLE
Cannot visualize ViewNode in the AR scene

### ISSUE THREAD

**Issue by mark100198** [SceneView/sceneview-android#351]
Hi! First of all thank you for all your work. I need your help since I am trying to move from sceneform to sceneview for my AR-based android app. In my app I'm trying to visualize a ViewNode on top of a ModelNode. This is the code, part of a fragment:

        val anchor = hitResult.createAnchor() ?: return
        val anchorNode = AnchorNode(sceneView.engine, anchor).apply { isEditable = true }

        val model = ModelNode(
            modelInstance = sceneView.modelLoader.createModelInstance("models/pin.glb"),
            parent = anchorNode,
            scaleToUnits = 0.004f
        ).apply {
            position = Position(0.0f, -0.06f, 0.0f)
            rotation = Rotation(90.0f, 0.0f, 0.0f)
            isEditable = true
        }

        ViewNode(
            engine = sceneView.engine,
            modelLoader = sceneView.modelLoader,
            viewAttachmentManager = ViewAttachmentManager(context, view),
            parent = model
        ).apply {
            isEditable = true
            loadView(requireContext(), R.layout.card_new)
            onViewLoaded = {_, _ ->
                Log.d(TAG, "View Loaded!")
            }
            position = Position(x = 0.0f, y = 0.2f, z = 0.0f)
        }
        sceneView.addChildNode(anchorNode)
        
I can see the ModelNode, but not the ViewNode, even if onViewLoaded gets called. I couldn't find any examples of code for ViewNode to check if my code is fine. Can you please provide any or tell me if I'm doing anything wrong?

Thank you very much

**Comment by pablojoseoroz** [comment]
Hi @mark100198 , I suggest you to create ViewAttachmentManager onViewCreated and call his onResume and onPause in your fragment lifecycle methods. Then use it as property when add ViewNode.

**Comment by Hyzam-Ali** [comment]
Hey @mark100198. I am facing the same issue as well

**Comment by mark100198** [comment]
Thank you @Hyzam-Ali, good to know that it's not related to my code. In the meantime, I've tried defining ViewAttachmentManager with different views and in different parts of the code. Maybe that's the source of the issue, but I still don't get how to make it work

**Comment by kay-itintouch** [comment]
@mark100198 I had the same problem and got ii working this way:
in onViewCreated I build the viewAttachmentManager using the sceneview in my fragment:
`  sceneView = view.findViewById(R.id.sceneView)
        this.viewAttachmentManager = ViewAttachmentManager(requireContext(), sceneView)`
I implemented onResume and onPause and call the corresponding methods on the manager object.
 And I build the ViewNode like this (this is based on old code using SceneForm which I rewrote to use ScenView):
`val modelNode =
            ViewNode(sceneView.engine, sceneView.modelLoader, viewAttachmentManager).apply {
                setRenderable(viewRenderable)
            }`
One thing I noticed was a bad UV mapping that required a scale with negative y axis to get it right:
` node.scale = Scale(scale, -scale, scale)`

Hope this helps.

**Comment by mark100198** [comment]
Thank you very much @kay-itintouch, your solution solved my problem as well. I followed your steps and, as you mention, I had to fix the position, orientation and scaling of the view by trial and error and found it quite cumbersome. It's a shame that the ViewNode has these problems and still doesn't work on its own having to rely on the external ViewRenderable builder from sceneform. 

I think there's still some fixing needed. In any case, I am closing the issue. 

Thanks everybody for your precious help!

**Comment by sameerjj** [comment]
for me what helped was calling `parent.addChildNode(viewNode)` only after the viewNode has completed rendering (either using callback or calling after suspend fun loadView has completed). I also had to use the scale hack to get the view to rotate to the orientation I was expecting.
