### ISSUE TITLE
onTapAR removed :-(

### ISSUE THREAD

**Issue by pablojoseoroz** [SceneView/sceneview-android#356]
Sorry, on new version 1.2.3 how can I detect removed scene onTapAR? Thanks!

**Comment by pabloMillanCb** [comment]
I am having the same problem. It seems there is a solution for composable projects in the sample folder, but I'm not using Composable and can't find a way to make it work

**Comment by santhoshpulliman** [comment]
Need to use compose to make use of onTapAR ?

**Comment by pabloMillanCb** [comment]
It is not necesary. For not-compose, make this inner class:

`inner class MyGestureDetector : GestureDetector.OnGestureListener
	{
		override fun onContextClick(e: MotionEvent, node: Node?) {
			console.log("onContextClick")
		}
		
		override fun onDoubleTap(e: MotionEvent, node: Node?) {
			console.log("onDoubleTap")
		}
		
		override fun onDoubleTapEvent(e: MotionEvent, node: Node?) {
			console.log("onDoubleTapEvent")
		}
		
		override fun onDown(e: MotionEvent, node: Node?) {
			console.log("onDown")
		}
		
		override fun onFling(e1: MotionEvent?, e2: MotionEvent, node: Node?, velocity: Float2) {
			console.log("onFling")
		}
		
		override fun onLongPress(e: MotionEvent, node: Node?) {
			console.log("onLongPress")
			onSingleTapConfirmed(e, node)
		}
		
		override fun onMove(detector: MoveGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onMove")
		}
		
		override fun onMoveBegin(detector: MoveGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onMoveBegin")
		}
		
		override fun onMoveEnd(detector: MoveGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onMoveEnd")
		}
		
		override fun onRotate(detector: RotateGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onRotate")
		}
		
		override fun onRotateBegin(detector: RotateGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onRotateBegin")
		}
		
		override fun onRotateEnd(detector: RotateGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onRotateEnd")
		}
		
		override fun onScale(detector: ScaleGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onScale")
		}
		
		override fun onScaleBegin(detector: ScaleGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onScaleBegin")
		}
		
		override fun onScaleEnd(detector: ScaleGestureDetector, e: MotionEvent, node: Node?) {
			console.log("onScaleEnd")
		}
		
		override fun onScroll(e1: MotionEvent?, e2: MotionEvent, node: Node?, distance: Float2) {
			console.log("onScroll")
		}
		
		override fun onShowPress(e: MotionEvent, node: Node?) {
			console.log("onShowPress")
		}
		
		override fun onSingleTapConfirmed(e: MotionEvent, node: Node?) {
			
			if(node==null){
				binding?.sceneView?.frame?.hitTest(e)
					?.firstByTypeOrNull(planeTypes = setOf(Plane.Type.HORIZONTAL_UPWARD_FACING))?.createAnchorOrNull().let {
						val modelIndex = sceneParameters?.index ?: -1
						if(it != null && modelIndex >= 0) {
							try {
								val modelNode = sceneParameters?.model?.get(modelIndex)?.node
								addAnchorNode(it, modelNode)
							} catch(_: Exception) {
							}
						}
					}
			}
		}
		
		override fun onSingleTapUp(e: MotionEvent, node: Node?) {
			console.log("onSingleTapUp")
		}
	}`
	
	And then this:

`sceneView = binding?.sceneView?.apply {
					gestureDetector.listener = MyGestureDetector()`
