### ISSUE TITLE
Detect dimensions/size of 3D model and scale accordingly?

### ISSUE THREAD

**Issue by kelvinwatson** [SceneView/sceneview-android#36]
Is there a way to detect the size (dimensions) of a loaded GLB file and calculate a scale factor so that the 3D model fits on the Android screen? Filament has a method called `transformToUnitCube()` which "tells the model viewer to transform the root node of the scene such that it fits into a 1x1x1 cube centered at the origin". 
Could we build something like that for `SceneView`?
```
private fun loadGlb(name: String) {
   val buffer = readAsset("models/${name}.glb")
   modelViewer.loadModelGlb(buffer)
   modelViewer.transformToUnitCube()
}
``` 

Source: https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67

**Comment by ThomasGorisse** [comment]
Here is what you are looking for:
https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/kotlin/io/github/sceneview/node/ModelNode.kt#L332-L337

It will scale your model to a unit cube.

**Comment by ThomasGorisse** [comment]
You could encounter some issue if your model is animated due to an actually wrong bounding box calculation returned by Filament.
If it's your case, please create an issue within the Filament repo and link it here.

**Comment by ThomasGorisse** [comment]
BTW, that's the kind of thing that makes me love the [kotlin-math](https://github.com/romainguy/kotlin-math) integration within SceneView:
```kotin
val halfExtent = asset.boundingBox.halfExtent.let { v -> Float3(v[0], v[1], v[2]) }
modelScale = Scale(units / max(halfExtent))
```

**Comment by kelvinwatson** [comment]
Really appreciate your help @ThomasGorisse Thank you!

**Comment by ThomasGorisse** [comment]
Sorry. I won't be able to answer you on the deprecated/archived version of Google Sceneform within those repositories issues context.

**Comment by kelvinwatson** [comment]
No worries, I will be migrating over to SceneView.
