### ISSUE TITLE
How to enable vertical plane renderer?

### ISSUE THREAD

**Issue by dwane13** [SceneView/sceneview-android#361]
Is it possible now to enable the vertical planes renderer? Currently, I tried to enable vertical planes rendering with:

`config.planeFindingMode = Config.PlaneFindingMode.VERTICAL`

`this.planeRenderer.planeRendererMode = PlaneRenderer.PlaneRendererMode.RENDER_ALL`

This approach renders horizontal planes correctly, but vertical planes still do not work as expected, although I can still place objects on them.

**Comment by dwane13** [comment]
And suddenly when I submitted this issue vertical plane rendering finally works without any code adjustments.

**Comment by hlefe** [comment]
Hello, I provided a solution to this issue here: https://github.com/SceneView/sceneview-android/issues/54#issuecomment-2508181759
