### ISSUE TITLE
How to store and retrieve the anchor from local storage.

### ISSUE THREAD

**Issue by sagarjgborg** [SceneView/sceneview-android#363]
I am building an application in which users can store their added anchors in a plane in **local storage** and retrieve them again when required. Is there any way to do so?

Thanks in advance.

**Comment by RGregat** [comment]
It is not straightforward to store an Anchor. The only way to store an Anchor is by using a CloudAnchor (https://developers.google.com/ar/develop/java/cloud-anchors/quickstart) or a Geospatial Anchor (https://developers.google.com/ar/develop/java/geospatial/anchors).
The hosting takes place on a Google-Server.
If you want to store something local you have to implement some kind of reference mechanism, for example a AugmentedImage on a fixed place or two+ points in real life to calculate transformation parameters to restore the Anchors.

**AugmentedImage**
* Scan the Image
* The scanned Image has it's own local coordinate system if I remember correctly
* Based on the local coordinate system place nodes as a child of the found AugmentedImage

**Transformation**
* In your session where you place your points, place also at least two more points which are used later to reference another session.
* Store the local coordinate of all points in the local database
* On a second session, place at the exact location the reference points again.
* Now you have for all reference points two coordinates (session 1 and session 2). With a 4 parameter Helmert transformation you can calculate parameters to transform all other points which where placed in session 1 to session 2.
* Note, the accuracy depends highly on the placed reference points.

So you see both approaches are not that easy to implement and the accuracy isn't constant. If possible I would stick with **CloudAnchor** or **Geospatial Anchor**

**Comment by sagarjgborg** [comment]
Hey @RGregat, I have implemented **AugmentedImage**. But, the results were not promising and accuracy isn't constant as you said. Will check out **Transformation**.
