### ISSUE TITLE
Android min API level support

### ISSUE THREAD

**Issue by meor9zcu12** [SceneView/sceneview-android#37]
Compile error when under Android API level 24.

Wonder to see if it is possible to allow compile under API level 24 and require run-time checking to use.
For the 3D only package that without ARCore, see if it is possible to allow lower API level.

**Comment by ThomasGorisse** [comment]
24 is not so high but we can try to lower it.
Could you make a PR with it and try dicreasing it until you got errors?

**Comment by RGregat** [comment]
Filament has set as the minSdk **19**. So I guess that is the lowest API level we can possible go.

**Comment by Devansh-Maurya** [comment]
I need to use this library in a project having min SDK as Android 21. Would like to know what issues might occur if we try to lower the minSDK? That would also help me understand why the minSDK was chosen as 24.
I can work on lowering the minSDK after knowing the repercussions.
Thanks.
