### ISSUE TITLE
How can I display text with ViewNode using jetpack compose? @ThomasGorisse

### ISSUE THREAD

**Issue by millerjeison** [SceneView/sceneview-android#370]
aRSceneView = findViewById<ARSceneView?>(R.id.sceneView).apply {
            configureSession { session, config ->
                session.configure(
                    config.apply {
                        geospatialMode = Config.GeospatialMode.ENABLED
                    }
                )
            }
            onSessionUpdated = { session, frame ->
                if (session?.earth?.trackingState == TrackingState.TRACKING) {

                    if(!loadData) {
                        Log.e("ingreso onSessionUpdated $loadData",session?.earth?.trackingState.toString() )
                        val qx = 0f
                        val qy = 0f
                        val qz = 0f
                        val qw = 1f
                      val anchorNode = AnchorNode(engine = engine, anchor = earthAnchor)
                        var earthAnchor: Anchor = session?.earth!!.createAnchor(6.2579617,-75.539315, 1778.28, qx, qy, qz, qw)

                        aRSceneView.addChildNode(
                            AnchorNode(aRSceneView.engine, earthAnchor,
                                ).apply {
                                ViewNode(
                                engine=aRSceneView.engine,
                                modelLoader = aRSceneView.modelLoader,
                                viewAttachmentManager= ViewAttachmentManager(aRSceneView.context,aRSceneView),
                            ).apply {
                                loadView(this@MainActivity,  R.layout.view_text)
                                isEditable = true
                                scale = Scale(50f)
                                isVisible = true                        }
                            }
                        )
                            loadData=true
                    }
                }

            }
        }

**Comment by sameerjj** [comment]
you want to create an anchorNode with that earth anchor. then add a ViewNode as a child of the anchornode.

**Comment by millerjeison** [comment]
> you want to create an anchorNode with that earth anchor. then add a ViewNode as a child of the anchornode.
If this is what I'm trying to do but it doesn't do anything it doesn't show anything
`  var earthAnchor: Anchor = session?.earth!!.createAnchor(6.2579617,-75.539315, 1778.28, qx, qy, qz, qw)

                        aRSceneView.addChildNode(
                            AnchorNode(aRSceneView.engine, earthAnchor).apply {
                                ViewNode(
                                engine=aRSceneView.engine,
                                modelLoader = aRSceneView.modelLoader,
                                viewAttachmentManager= ViewAttachmentManager(aRSceneView.context,aRSceneView),
                            ).apply {
                                loadView(this@MainActivity,  R.layout.view_text)
                                isEditable = true
                                scale = Scale(5f)
                                isVisible = true                        }
                            }
                        )`

**Comment by sameerjj** [comment]
see https://github.com/SceneView/sceneview-android/issues/351

**Comment by millerjeison** [comment]
> see #351
Even though the problem persists, it doesn't show anything and says everything is fine.

      aRSceneView = findViewById<ARSceneView?>(R.id.sceneView).apply {
            configureSession { session, config ->
                session.configure(
                    config.apply {
                        geospatialMode = Config.GeospatialMode.ENABLED
                    }
                )
            }
            onSessionUpdated = { session, frame ->
                if (session?.earth?.trackingState == TrackingState.TRACKING) {



                    if(!loadData) {
                        Log.e("ingreso onSessionUpdated $loadData",session?.earth?.trackingState.toString() )
                        val qx = 0f
                        val qy = 0f
                        val qz = 0f
                        val qw = 1f
//                        val anchorNode = AnchorNode(engine = engine, anchor = earthAnchor)
                        var earthAnchor: Anchor = session?.earth!!.createAnchor(6.2579617,-75.539315, 1778.28, qx, qy, qz, qw)

                        val anchorNode = AnchorNode(aRSceneView.engine, earthAnchor).apply { isEditable = true }
                        
                                val model = ModelNode(
                                    modelInstance = aRSceneView.modelLoader.createModelInstance("marker.glb"),
                                    parent = anchorNode,
                                    scaleToUnits = 0.004f
                                ).apply {
//                                    position = Position(0.0f, -0.06f, 0.0f)
//                                    rotation = Rotation(90.0f, 0.0f, 0.0f)
                                    isEditable = true
                                }
                                ViewNode(
                                engine=aRSceneView.engine,
                                modelLoader = aRSceneView.modelLoader,
                                    parent=model,
                                viewAttachmentManager= ViewAttachmentManager(aRSceneView.context,aRSceneView),
                            ).apply {
                                loadView(this@MainActivity,  R.layout.view_text)
                                    onViewLoaded = {_, _ ->
                                        Log.d(TAG, "View Loaded!")
                                    }
                                isEditable = true
                                scale = Scale(50f)
                                isVisible = true                        }

                        aRSceneView.addChildNode(anchorNode)
                            loadData=true
                    }
                }

            }
        }

**Comment by sameerjj** [comment]
you have to manually addChild(viewNode) in onViewLoaded, you're not doing that

**Comment by millerjeison** [comment]
> you have to manually addChild(viewNode) in onViewLoaded, you're not doing that

The problem still persists, sorry, I'm a newbie to Kotlin, if you have an example with geopositional that can help me as a guide, I would appreciate it.

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        aRSceneView = findViewById<ARSceneView?>(R.id.sceneView).apply {
            configureSession { session, config ->
                session.configure(
                    config.apply {
                        geospatialMode = Config.GeospatialMode.ENABLED
                    }
                )
            }
            onSessionUpdated = { session, frame ->
                if (session?.earth?.trackingState == TrackingState.TRACKING) {
                    if(!loadData) {
                        var originNode: Node? = null
                        Log.e("ingreso onSessionUpdated $loadData",session?.earth?.trackingState.toString() )
                        val qx = 0f
                        val qy = 0f
                        val qz = 0f
                        val qw = 1f
                        var earthAnchor = session?.earth!!.createAnchor(6.258688,-75.539315, 1778.28, qx, qy, qz, qw)
                        addAnchorNode(earthAnchor)
                        loadData=true
                    }
                }

            }
        }
    }
override fun onResume() {
        viewAttachmentManager.onResume()
        super.onResume()
    }
override fun onPause() {
        viewAttachmentManager.onPause()
        super.onPause()
    }

fun addAnchorNode(anchor: Anchor) {
        originNode = Node(aRSceneView.engine)
        viewAttachmentManager = ViewAttachmentManager(aRSceneView.context, aRSceneView)
       var anchorNode=    AnchorNode(aRSceneView.engine, anchor)
                .apply {
                    isEditable = true
                    lifecycleScope.launch {
                        isLoading = true
                        ViewNode(
                            engine=aRSceneView.engine,
                            modelLoader = aRSceneView.modelLoader,
                            viewAttachmentManager= viewAttachmentManager,
                            parent = originNode!!
                        ).apply {
                            loadView(this@MainActivity,  R.layout.view_text)
                            isEditable = true
                            scale = Scale(5f)
                            isVisible = true
                            onViewLoaded = {_, view ->
                                originNode!!.addChildNode(this)
                            }
                        }
                        isLoading = false
                    }
                }
        aRSceneView.addChildNode( anchorNode)
    }
```

**Comment by millerjeison** [comment]
Solution 👍 

```
    ViewRenderable.builder()
            .setView(aRSceneView.context,R.layout.view_text)
            .build(aRSceneView.engine).thenAccept{r: ViewRenderable? ->
                aRSceneView.addChildNode  ( ViewNode(
                    engine=aRSceneView.engine,
                    modelLoader = aRSceneView.modelLoader,
                    viewAttachmentManager= viewAttachmentManager!!
                ).apply {
                    setRenderable(r)
                    isEditable = true
                    scale = Scale(5f)

                })

        }
```
