### ISSUE TITLE
ViewNode not rendering

### ISSUE THREAD

**Issue by BorkoCvejic** [SceneView/sceneview-android#389]
Hi guys, 

I want to track an image, and show some text above it. There is an "ar-augmented-image" sample, so I changed the part of the code where a "rabbit" image is detected. Instead of adding ModelNode() I'm adding ViewNode, but for some reason my text is not rendering.

```
ViewRenderable.builder()
         .setView(sceneView.context, R.layout.view_text)
          .build(sceneView.engine)
          .thenAccept {
                 sceneView.addChildNode(ViewNode(
                        engine = sceneView.engine,
                        modelLoader = sceneView.modelLoader,
                        viewAttachmentManager = viewAttachmentManager
                   ).apply {
                         quaternion = dev.romainguy.kotlin.math.Quaternion.fromEuler(-90f, 0f, 0f)
                         it.view.findViewById<TextView>(R.id.tvContent).text = "TEST TEST TEST"
                         setRenderable(it)
                         isEditable = true
                         scale = Scale(5f, -5f, 5f)
                         Toast.makeText(requireContext(), "IMAGE DETECTED", Toast.LENGTH_SHORT).show()
                    })
           }
```
                                        
In onViewCreated: 
```
sceneView = view.findViewById<ARSceneView>(R.id.sceneView)
viewAttachmentManager = ViewAttachmentManager(requireContext(), sceneView)
```
and view_text.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/tvContent"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@android:color/holo_purple"
        android:text="DUGACAK TEkST"
        android:textColor="@android:color/black"
        android:textSize="20sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

I read in other issue that onViewLoaded might be needed but something like this didn't help as well:

```
onViewLoaded = { renderableInstance, view ->
     sceneView.addChildNode(this)
}
```

What am I doing wrong?

**Comment by BorkoCvejic** [comment]
augmentedImage.trackingState is in state PAUSED, and it triggers only once, even in sample project, that's unexpected.

**Comment by ryust** [comment]
What worked in 0.9.5 no longer works in 2.0.2 regarding ViewNodes. In my case the ViewRenderable builder never completes.

**Comment by BorkoCvejic** [comment]
Seems like it behaves the same on my side with 0.9.5 sadly.

**Comment by BorkoCvejic** [comment]
I think there was some unnecessary code in the first post, but this cleaner version is still not working:

`val node = ViewNode(
       engine = sceneView.engine,
       modelLoader = sceneView.modelLoader,
       viewAttachmentManager = viewAttachmentManager
       )
       node.apply {
               loadView(
                      requireContext(),
                      R.layout.view_text
               )
       quaternion = dev.romainguy.kotlin.math.Quaternion.fromEuler(-90f, 0f, 0f)
        isEnabled = true
        scale = Scale(5f)
        Toast.makeText(requireContext(), "IMAGE DETECTED", Toast.LENGTH_SHORT).show()
}
sceneView.addChildNode(node)` 
                                    
I noticed there is different ViewNode in ModelViewer sample, but ViewNode which is used with ARSceneView is not working.

**Comment by BorkoCvejic** [comment]
Thanks for answering, but still no luck. 

Here is a whole [MainFragment ](https://pastecode.io/s/qwr9pygb)if somebody wants to take a look, there are minimal changes from ar-augmented-image sample.

**Comment by BorkoCvejic** [comment]
Thank you so much, it works! No idea why my code doesn't work.

When I try to create AnchorNode with anchor(centerPose) to be the rootNode for your solution it crashes, and when I set sceneView as parent, the view is a bit away and rotated but it renders! :) So, I'll need to figure out some more stuff but your solution renders.

**Comment by ryust** [comment]
I am using the Geospatial API which will create a terrain anchor via "earth.resolveAnchorOnTerrainAsync". Then I create an AnchorNode via "AnchorNode(engine, terrainAnchor).

**Comment by BorkoCvejic** [comment]
Ok so you are not using centerPose and createAnchor which are crashing for me.
