### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#394]
The fatal signal crash when closing the ARSceneView is back again in the 2.0.2 release.

**Comment by chandroidx** [comment]
It seems to occur when use Scene in **Dialog**

**Comment by ryust** [comment]
Yes, that's how I'm displaying the ARSceneView.

**Comment by ryust** [comment]
I moved the code from a DialogFragment to a regular Fragment and it all works now.
