### ISSUE TITLE
Basic cube is Sceneview is only partially shown. 

### ISSUE THREAD

**Issue by nallaperumal** [SceneView/sceneview-android#395]
I am not an expert in 3d and I know it is a very trivial issue. I am trying to load a cube in Scene composable but I see it is partially shown. Attaching screenshot and code
![screenshot](https://github.com/SceneView/sceneview-android/assets/4082215/04f7447c-39c7-4d5c-88da-7d07e41923dc)
[Source of MainActivity here in jetpack compose](https://github.com/SceneView/sceneview-android/files/13957962/MainActivity.zip)

**Comment by nallaperumal** [comment]
I understand that this issue is linked to [379](https://github.com/SceneView/sceneview-android/issues/379)

**Comment by ryust** [comment]
Was this "fixed" in 2.0.3 with #392? I am still experiencing similar shearing of models in the latest release.
