### ISSUE TITLE
Refactor Renderable and RenderableInstance

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#40]
How this can be done:
- Use `typealias`es for `Int` IDs and extension methods as, for example, for Filament lights (https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/kotlin/io/github/sceneview/light/Light.kt) or transforms (https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67). This seems to be a good approach to make Filament easier to use in Kotlin.

**Comment by ThomasGorisse** [comment]
My POV here is that we should have a `ModelNode.model: FilamentInstance?` and extension functions around `FilamentInstance`.
I don't know if it could be posible to only manage `FilamentAsset` only and exclude the `FilamentInstance` that generates a lit of confusion for user. For exemple, we never know if we must change the shadow or materal params on an instance or asset.
If the gap between the loading time of a `FilamentAsset` vs creating a `FilamentInstance` is not so big we should definetly make things less confusing.

**Comment by grassydragon** [comment]
Features of `RenderableDefinition`:

- Specifying submeshes without worrying about indices in Filament buffers
- Updating Filament buffers from the list of submeshes
- Determining attributes stored in vertex buffers based on the first vector
