### ISSUE TITLE
Augmented Image - 3D model is whole black (problem with texture?). How to enable rotation and zooming? VideoNode - status?

### ISSUE THREAD

**Issue by PepaZapletal** [SceneView/sceneview-android#406]
Hi,

I`m trying to use this sample code: 

https://github.com/SceneView/sceneview-android/blob/2230c5ab996dde289bd77dcf075a2fb1120356b5/samples/ar-augmented-image/src/main/java/io/github/sceneview/sample/araugmentedimage/MainFragment.kt#L30

in the app. Implement basic Augmented images. But If I try the sample code, then it shows the 3D model of the rabbit. But the whole model is black (I also tried a different model but the result was the same).

And how can we enable the rotation and zooming of the model by the gesture? 

And do you have some status about VideoNode? It can also be a very cool feature (with a big WOW effect)

Thank you for your best library!

**Comment by dhaval-android** [comment]
I am also looking good example for video node if anyone have, I tried my self but I cant able to create proper video node.
