### ISSUE TITLE
ANR due to arCore.destroy() being called on the main thread

### ISSUE THREAD

**Issue by sameerjj** [SceneView/sceneview-android#407]
## Problem
- getting Crashlytics reports of ANR and user reports of app hanging when closing AR activity
## Solution
- from ArCore Session documentation:
> Releases resources (a significant amount of native heap memory) used by an ARCore session.
Failure to close sessions explicitly may cause your app to run out of native memory and crash. If your app contains a single AR-enabled activity, it is recommended that you call close() from the activity's onDestroy method.
**This method will take several seconds to complete. To prevent blocking the main thread, call pause() on the main thread, and then call close() on a background thread.**

- use coroutine scope to call destroy off of MainThread

**Comment by sameerjj** [comment]
Fixes #407

**Comment by mlxyz** [comment]
@ThomasGorisse Any timeline for when this fix will be released? I am seeing crashes when navigating away from arsceneview with `libc	Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)` (but only when a model node with glb file is in the scene) and was wondering if this is related to this fix.

**Comment by grassydragon** [comment]
Hi @mlxyz!
The fix will be available soon in the release `2.0.4`: https://github.com/SceneView/sceneview-android/releases/tag/v2.0.4
