### ISSUE TITLE
Get child renderable node by onSingleTap

### ISSUE THREAD

**Issue by vicgcode** [SceneView/sceneview-android#410]
Hello!

I use ArSceneView 2.0.3. 
I have a model that contains almost twenty child nodes. I try to get a child node when user tap on the scene, but `onSingleTapUp`  and `onSingleTapConfirmed` callbacks return a parent node that contains all existing child nodes, but I don;t know how to find selected child node. How to get selected/tapped child node?

My code:
```
override fun onSingleTapUp(e: MotionEvent, node: Node?) {
            Log.e("oops", "onSingleTapUp")
            if (node != null) {
                val nodes = node.childNodes
                val renderableNodes = nodes.mapNotNull {
                    it as? ModelNode.RenderableNode
                }
                // here all child nodes, but I need selected one
                renderableNodes.forEach {
                    Log.e("oops", "${it.name}")
                }
            }
        }
```

Also I tried to use Compose, but it returns the same - all child nodes instead the one that tapped by user.

```
onGestureListener = rememberOnGestureListener(
                            onSingleTapConfirmed = { motionEvent, node ->
                                if (node != null) {
                                    val nodes = node.childNodes
                                    val renderableNodes = nodes.mapNotNull {
                                        it as? ModelNode.RenderableNode
                                    }
                                    val entity = node.entity
                                    val name = (node as? ModelNode.RenderableNode)?.name
                                    renderableNodes.forEach {
                                        Log.e("oops", "child name = ${it.name}")
                                    }
```

@ThomasGorisse
@grassydragon

and All members

**Comment by vicgcode** [comment]
Thank you for the answer @grassydragon! Is there a any version of SceneView in which picking works with child nodes?

**Comment by grassydragon** [comment]
I think you should try a version before this release: https://github.com/SceneView/sceneview-android/releases/tag/v1.2.0

**Comment by bankbiz** [comment]
@vicgcode I try to handle `onSingleTap` and check the node name.
I wonder how you can access the `name` property from `Node`? 
Due to their being gone [since v0.10.2](https://github.com/SceneView/sceneview-android/blob/722101172c7a324844e08d9a2f841aed1da9fe88/sceneview/src/main/java/io/github/sceneview/node/Node.kt#L69), according to my understanding. Currently [Node.kt](https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/node/Node.kt)
