### ISSUE TITLE
Viewnodes are not rendered.

### ISSUE THREAD

**Issue by comst19** [SceneView/sceneview-android#414]
hello.
I'm using SceneView2.0.2.

Currently, the modelNode is visible to the camera, but the viewNode is not.
I want to know the reason.

    private fun addAnchorNode(anchor: Anchor, capsule: CapsuleMarker) {
        Log.d("CameraFragmentAR", "addAnchorNode added")
        val anchorNode = AnchorNode(binding.sceneView.engine, anchor)

        viewLifecycleOwner.lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                binding.sceneView.modelLoader.loadModelInstance("https://sceneview.github.io/assets/models/DamagedHelmet.glb").let { modelInstance ->
                    modelInstance?.let {
                        val modelNode = ModelNode(modelInstance = it).apply {
                            playAnimation(0)
                            onSingleTapConfirmed = {
                                viewModel.cameraEvent(CameraViewModel.CameraEvent.ShowCapsulePreviewDialog(capsule.id.toString(), capsule.capsuleType.toString()))
                                false
                            }
                        }

                        ViewRenderable.builder()
                            .setView(binding.sceneView.context, R.layout.capsule_skin)
                            .build(binding.sceneView.engine).thenAccept { viewRenderable: ViewRenderable? ->
                                val viewNode = ViewNode(
                                    engine = binding.sceneView.engine,
                                    modelLoader = binding.sceneView.modelLoader,
                                    viewAttachmentManager = ViewAttachmentManager(requireContext(), binding.sceneView)
                                ).apply {
                                    setRenderable(viewRenderable)
                                    isEditable = true
                                    scale = Scale(1f, 1f, 1f)
                                    position = Position(0f, 0f, -0.5f)
                                }

                                anchorNode.addChildNode(viewNode)
                            }

                        anchorNode.addChildNode(modelNode)
                    }
                }
            }
        }

        binding.sceneView.addChildNode(anchorNode)
        this.anchorNode = anchorNode
    }

**Comment by dhaval-android** [comment]
I tried like bellow and its working fine you can check 


Custom Class
```
class ARContentNode(
    val arscene: ARSceneView,
    val viewAttManager: ViewAttachmentManager,
    val onLoaded: (node: ViewNode) -> Unit
) {

    init {
        renderContent()
    }

    private fun renderContent() {
        ViewRenderable.builder()
            .setView(arscene.context, R.layout.layout_custom_card) //Replace your view id here.
            .build(arscene.engine).thenAccept { r: ViewRenderable? ->
                val viewNode = ViewNode(
                    engine = arscene.engine,
                    modelLoader = arscene.modelLoader,
                    viewAttachmentManager = viewAttManager
                ).apply {
                    if (r != null) {
                        setRenderable(r)
                        isEditable = true
                    }
                }
                onLoaded(viewNode)
            }
    }
}
```

Method fire once find anchor using tap or any other way
```
fun addCardObj(anchor: Anchor) {
        val arContentNode =
            bindingView?.sceneView?.let { scenview ->
                iewAttachmentManager?.let { attachManager ->
                    ARContentNode(scenview, attachManager, onLoaded = { viewNode ->
                        bindingView?.sceneView?.engine?.let {
                            AnchorNode(it, anchor)
                                .apply {
                                    isEditable = true
                                    lifecycleScope.launch {
                                        addChildNode(viewNode)
                                    }
                                    anchorNode = this
                                }
                        }?.let {
                            bindingView?.sceneView?.addChildNode(
                                it
                            )
                        }
                    })
                }
            }
    }
```




Methods in Activity or fragment 
   ```
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        bindingView = ActivityArElementBinding.inflate(layoutInflater)
        setContentView(bindingView!!.root)
        iewAttachmentManager = ViewAttachmentManager(
            bindingView?.sceneView?.context,
            bindingView?.sceneView
        )
    }



    override fun onResume() {
        super.onResume()
        iewAttachmentManager?.onResume()
    }

    override fun onPause() {
        super.onPause()
        iewAttachmentManager?.onPause()
    }

```

**Comment by comst19** [comment]
Thanks to you, I solved it.

**Comment by comst19** [comment]
private fun addAnchorNode(anchor: Anchor, capsule : CapsuleMarker) {
        Log.d("CameraFragmentAR", "addAnchorNode added")
        val arContentNode =
            binding.sceneView.let { scenview ->
                viewAttachmentManager.let { attachManager ->
                    ARContentNode(scenview, attachManager, onLoaded = { viewNode ->
                        binding.sceneView.engine.let {
                            AnchorNode(it, anchor)
                                .apply {
                                    isEditable = true
                                    onSingleTapConfirmed = {
                                        Log.d("클릭", "onSingleTapConfirmed")
                                        viewModel.cameraEvent(CameraViewModel.CameraEvent.ShowCapsulePreviewDialog(capsule.id.toString(), capsule.capsuleType.toString()))
                                        false
                                    }
                                    onSingleTapUp = {
                                        Log.d("클릭", "onSingleTapUp")
                                        viewModel.cameraEvent(CameraViewModel.CameraEvent.ShowCapsulePreviewDialog(capsule.id.toString(), capsule.capsuleType.toString()))
                                        false
                                    }
                                    lifecycleScope.launch {
                                        addChildNode(viewNode)
                                    }
                                    anchorNode = this
                                }
                        }.let {
                            binding.sceneView.addChildNode(it)
                        }
                    })
                }
            }
    }
