### ISSUE TITLE
On-click gesture returning parent node position instead of selected child node position

### ISSUE THREAD

**Issue by KvRae** [SceneView/sceneview-android#419]
When utilizing the on-click gesture in the Scene, I encounter a problem where attempting to select a specific child node and retrieve its position results in the position of the parent node being returned instead.

Upon selecting a child node using the on-click gesture, the position returned should correspond to the selected child node's position in the scene
Instead of returning the position of the selected child node, the position of the parent node is consistently returned.
This issue persists across multiple attempts and scenarios.
Other gestures and interactions with child nodes function as expected.
This behavior impacts the accurate positioning of elements within the scene, leading to unintended results in application functionality. I'm using Scene View version: 2.0.3

**Comment by yahya-rootinfosol** [comment]
I am also facing the same issue even in latest version 
`implementation("io.github.sceneview:sceneview:2.2.1")`

this is the code which I am using I want to show a 3d view Model of a human being consisting different child nodes like ear, nose, hands, legs, etc but when I click on that node callback is giving me the parent node.

`setContent {
            CamposerTheme {
                CamposerTheme {

                    val context = LocalContext.current
//                    SceneViewWithTapHandling(context)

                    Box(modifier = Modifier.fillMaxSize()) {

                        val engine = rememberEngine()
                        val modelLoader = rememberModelLoader(engine)
                        val environmentLoader = rememberEnvironmentLoader(engine)

                        val cameraNode = rememberCameraNode(engine).apply {
                            position = Position(z = 5f)
                        }

                        val centerNode = rememberNode(engine)
                            .addChildNode(cameraNode)
                        val cameraTransition =
                            rememberInfiniteTransition(label = "CameraTransition")
//                    val cameraRotation by cameraTransition.animateRotation(
//                        initialValue = Rotation(y = 0.0f),
//                        targetValue = Rotation(y = 360.0f),
//                        animationSpec = infiniteRepeatable(
//                            animation = tween(durationMillis = 7.seconds.toInt(MILLISECONDS))
//                        )
//                    )

                        val modelNode =

                            ModelNode(
                                modelInstance = modelLoader.createModelInstance(
                                    assetFileLocation = "models/male_body_3.glb"
                                ),
                                scaleToUnits = 0.25f,

                                ).apply {
                                name = "male body"
                                isTouchable = true
                                isHittable = true
                                isVisible = true
                                isPositionEditable = true
                                isEditable = true
                                scale = Scale(1 / 40f)
                                position = Position(0f, y = -2f)
                                nodes.forEach {
                                    it.isTouchable = true
                                    it.isHittable = true
                                    it.isVisible = true
                                    it.isPositionEditable = true
                                    it.isEditable = true

                                }
                            }


                        val child = arrayListOf<Node>()
                        modelNode.nodes.forEach {

                            child.apply {
                                it.isTouchable = true
                                it.isHittable = true
                                it.isVisible = true
                                it.isPositionEditable = true
                                it.isEditable = true
                            }.add(it)
                        }
                        val childs = modelNode.childNodes.take(20)

                        childs.forEach {
                            it.onSingleTapConfirmed = { e ->
                                Toast.makeText(this@SceneviewActivity, it.name, Toast.LENGTH_SHORT)
                                    .show()
                                true
                            }
                        }

                        val nodes = arrayListOf(centerNode)
                        nodes.addAll(childs)
                        Scene(
                            modifier = Modifier.fillMaxSize(),
                            engine = engine,
                            modelLoader = modelLoader,
                            cameraNode = cameraNode,
                            childNodes = rememberNodes{
                                modelNode.nodes.forEach {

                                    add(it)
                                }
                            }
                            ,
                            onFrame = {
//                                centerNode.rotation = cameraRotation
                                cameraNode.lookAt(centerNode)
                            },
                            onGestureListener = rememberOnGestureListener(
                                onSingleTapConfirmed = { _, node ->

                                    Log.e("node", "onsingletap confirm: " + node?.entity)
                                    Toast.makeText(
                                        this@SceneviewActivity,
                                        "node:" + node?.name,
                                        Toast.LENGTH_SHORT
                                    )
                                        .show()
                                },
                                onDoubleTap = { _, node ->

                                    node?.apply {
                                        scale *= 2.0f
                                    }
                                }
                            ),
                            onTouchEvent = { event: MotionEvent, hitResult: HitResult? ->


                                Log.e("node", "onTouch: " + hitResult?.node?.entity)
                                hitResult?.let { println("node tapped : ${hitResult.node?.name}") }
                                // The touch event is not consumed

                                false
                            }
                        )

                        TopAppBar(
                            title = {
                                Text(
                                    text = stringResource(id = R.string.app_name)
                                )
                            },
                            colors = TopAppBarDefaults.topAppBarColors(
                                containerColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.25f),
                                titleContentColor = MaterialTheme.colorScheme.onPrimary

                            ),
                        )
                    }
                }
            }
        }`

**Comment by KvRae** [comment]
Hi, I remember that this issue was fixed in the latest release for Sceneview there was an issue with the collision system. You might have a mess with your code as I see so try to clean it up

**Comment by yahya-rootinfosol** [comment]
I have tried many ways by directly adding child and other but didn't succeed here is the clean up code.

`Box(modifier = Modifier.fillMaxSize()) {

                        val engine = rememberEngine()
                        val modelLoader = rememberModelLoader(engine)
                        val view = rememberView(engine)
                        val renderer = rememberRenderer(engine)
                        val scene = rememberScene(engine)
                        val materialLoader = rememberMaterialLoader(engine)
                        val collisionSystem = rememberCollisionSystem(view)

                        Scene(
                            modifier = Modifier.fillMaxSize(),
                            engine = engine,
                            view = view,
                            renderer = renderer,
                            scene = scene,
                            modelLoader = modelLoader,
                            materialLoader = materialLoader,
                            collisionSystem = collisionSystem,
                            isOpaque = true,
                            mainLightNode = rememberMainLightNode(engine) {
                                intensity = 100_000.0f
                            },
                            cameraNode = rememberCameraNode(engine) {
                                position = Position(z = 4.0f)
                            },
                            cameraManipulator = rememberCameraManipulator(),
                            // Scene nodes
                            childNodes = rememberNodes {
                                add(ModelNode(
                                    modelInstance = modelLoader.createModelInstance(
                                        assetFileLocation = "models/male_body_3.glb"
                                    ),
                                    scaleToUnits = 0.25f,
                                ).apply {
                                    scale = Scale(1 / 40f)
                                    position = Position(0f, y = -2f)
                                })
                            },
                            onGestureListener = rememberOnGestureListener(
                                onSingleTapUp = { _, node ->
                                    Log.e("===", "onSingleTapUp")
                                    if (node != null) {
                                        val nodes = node.childNodes
                                        val renderableNodes = nodes.mapNotNull {
                                            it as? ModelNode.RenderableNode
                                        }
                                        // here all child nodes, but I need selected one
                                        renderableNodes.forEach {
                                            Log.e("===", "${it.name}")
                                        }
                                    }
                                },
                                onSingleTapConfirmed = { _, node ->

                                    Log.e("node", "onsingletap confirm: " + node?.entity)
                                    Toast.makeText(
                                        this@SceneviewActivity,
                                        "node:" + node?.name,
                                        Toast.LENGTH_SHORT
                                    )
                                        .show()
                                },
                            ),

                            )

                        TopAppBar(
                            title = {
                                Text(
                                    text = stringResource(id = R.string.app_name)
                                )
                            },
                            colors = TopAppBarDefaults.topAppBarColors(
                                containerColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.25f),
                                titleContentColor = MaterialTheme.colorScheme.onPrimary

                            ),
                        )
                    }`
                    
     Help me out if I am doing something wrong, I am not getting child node that is selected.

**Comment by KvRae** [comment]
You're trying to access each part of the body model which is the parent, and then you are adding body parts which are child nodes that's what logic says,

but in your implementation, you have only one model that represents the whole body (male_body_3.glb) for the body parts(child nodes) you didn't specify where each part is located exactly in the body.
 
When you use the click gesture (click with your finger), the collision system can identify your finger position on the screen and convert it into the position inside your scene. So it finds the body (male_body_3.glb) instead of placing the part because you didn't specify the position of each part inside the body(male_body_3.glb).

I recommend adding a collider box for each part of the body so the collision system can identify the part that you want to click on
