### ISSUE TITLE
Issue with Video Texture when we using chroma Video function.

### ISSUE THREAD

**Issue by dhavalenstead** [SceneView/sceneview-android#421]
Default video material not working from sdk, So I just implemented custom material for Video texture with chroma video or plane video, So Now issue is plain video ( without chroma color) working fine but when I try to play video with chroma color then else of showing video texture its showing camera feed on object. 

You can find screenshot and my implemented code at bellow.

**Not working proper**
   if (chromaColor == null) "materials/video_texture.filamat" else "materials/video_texture_chroma_key.filamat",
![withChromaColor](https://github.com/SceneView/sceneview-android/assets/156281723/54443b8a-4242-4db5-a31f-788b72e23980)

**Working**
if (chromaColor == null) "materials/video_texture.filamat" else "materials/video_texture.filamat",
![withoutChroma png](https://github.com/SceneView/sceneview-android/assets/156281723/54084419-f043-4727-866b-30b51795dddf)

[Here is my whole code snap ](https://github.com/SceneView/sceneview-android/issues/409#issuecomment-1953543972)

**Comment by erikhric** [comment]
ExoPlayer supports transparency with vp9 webm format, but SceneView materials are unable to use that alpha channel and we are still forced to use Chroma keying 😭 any update on that?
