### ISSUE TITLE
PlaneRenderer - Move to Filament mesh builder

### ISSUE THREAD

**Issue by ThomasGorisse** [SceneView/sceneview-android#43]
> Would you mind doing the move from RenderableDefinittion to Filament direct mesh creation?

We just need to make sure that we aren't missing any important features that Sceneform provided for mesh creation. I actually only used the direct Filament approach.

_Originally posted by @grassydragon in https://github.com/SceneView/sceneview-android/issues/39#issuecomment-1066126542_

**Comment by grassydragon** [comment]
I'll continue working on it after we resolve issues with Filament picking.
