### ISSUE TITLE
The release 2.0.4 is broken

### ISSUE THREAD

**Issue by KvRae** [SceneView/sceneview-android#432]
I have tried to upgrade from Scene View Android 2.0.3 to 2.0.4 and I figured that the library's files had been removed from my project's external libraries  folder and a lot of properties such as `Scene()` from `io.github.sceneview:sceneview:2.0.3` has gone in the 2.0.4
Do you have any proposed solution for that?

**Comment by grassydragon** [comment]
Hi!
It looks like the version `2.0.4` hasn't been uploaded to the Maven Central repository yet.

**Comment by KvRae** [comment]
Okay, I see, does it include the fix for the selected node passed to the gestures?
