### ISSUE TITLE
ImageNode or PlaneNode cannot change the color/material

### ISSUE THREAD

**Issue by natasam** [SceneView/sceneview-android#436]
I was trying to change the color of the ImageNnode and PlaneNode, by loading material, creating materialInstance, and setting color, but nothing worked. Also, when the image has opacity, it will not be rendered at all. How to properly set or change the color of the PlaneNode? Everything I get is light grey, white or black.
this is my Scene: 
 ```
Scene(
                modifier = Modifier.fillMaxSize(),
                engine = engine,
                onViewCreated = {
                    scene.skybox = Skybox.Builder().color(255f, 255f, 255f, 1.0f).build(engine)
                    scene.indirectLight = environment.indirectLight
                },
                modelLoader = modelLoader,
                cameraNode = cameraNode,
                childNodes = listOf(
                    centerNode, plane
                ),
              
                onFrame = {
                }
            )

```
And the plane is: 
 ```
val plane =  PlaneNode(
            engine = engine,
            size = Size(2f, 2f),
            center = Position(x = 0f, y = 1f, z = 0.1f),
            normal = Direction(x = 0f, y = 0f, z = 0f),
           // materialInstances = listOf(materialInstance),
             materialInstance = materialInstance,
        )
```
Material is loaded corectly. But no color is shown.
<img width="432" alt="Screenshot 2024-03-06 at 21 13 26" src="https://github.com/SceneView/sceneview-android/assets/16170722/2c6e402a-94f0-4789-b308-fb7a4af5484c">

**Comment by KvRae** [comment]
i was working with this method and its working fine on my side 
CubeNode(
            engine = engine,
        ).apply {
//...
            if (materialLoader != null) {
                materialInstance = materialLoader.createColorInstance(
                        color = Color(0.561f, 0.561f, 0.561f, 1.0f)
                    )
// ...
            }
        }
feel free to try it ^^

**Comment by natasam** [comment]
Thanks @KvRae , but its still not working... 😢  I don't know what is wrong here, why do you check for materialLoader if it is null? How do you initialize the materialLoader? Can you add how do you setup your scene?

**Comment by natasam** [comment]
Thanks @KvRae , setting size in the cubeNode works, as a workaround...
```
 val cube =  CubeNode(
                engine = engine,
               size = Size(x=10f, y=10f, z=0.1f)
            )
```

**Comment by KvRae** [comment]
That's great to hear! I hope everything gets fixed in the meantime...
