### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) is back in 2.0.4

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#439]
As the title says, "Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)" has returned in 2.0.4 when exiting the activity containing an ARSceneView. Using 2.0.3 with no code changes, the app exits the activity correctly without crashing the app. The activity is similar to sample app with a main Activity and a Fragment to display the scene.

**Comment by ryust** [comment]
Discovered the crash happens when ARSession.close() is called when destroying the fragment containing it.

**Comment by AlexDarigan** [comment]
Related to #440 

Wondering if this came from the newest fix where destroy was moved to a background thread? Possibly trying to destroy it when it was already out of scope? (a guess)

**Comment by NikitaGvozdilko** [comment]
Any progress?

**Comment by ThomasGorisse** [comment]
Fixed in [v2.2.0](https://github.com/SceneView/sceneview-android/releases/tag/v2.2.0)
