### ISSUE TITLE
ViewNode for 2.1.0

### ISSUE THREAD

**Issue by ryust** [SceneView/sceneview-android#449]
The 2.1.0 version has changed ViewNodes. Is there a working sample to help make the transition to the new release? And NOT using Compose.

**Comment by pabloMillanCb** [comment]
Do you have any example on how to add a ViewNode in 2.0.4? I'm trying but I can't visualize it yet. My code is the following:

`sceneView?.let {scene ->
				AnchorNode(scene.engine, anchor).apply {

					isEditable = false
					/*
					modelNode?.let { node ->
						
						addChildNode(node).apply {
							isEditable = false
						}
					}
					 */
					geospatialText?.let { text ->
						console.log("sceneview", "añadiendo texto")
						val attachmentManager =
							ViewAttachmentManager(this@ARMainActivity, sceneView)
						attachmentManager.onResume()
						val textNode = ViewNode(scene.engine, scene.modelLoader, attachmentManager)
						textNode.loadView(this@ARMainActivity, R.id.testText , onLoaded = { instance, view ->
							addChildNode(textNode)
						})
					}
					
				}
			}?.let { anchorNode ->
				anchorNode.isEditable = false
				sceneView?.addChildNode(anchorNode)
				console.log("Sceneview", "node added")
				//sceneView?.cameraNode?.let { anchorNode.lookAt(it) }
			}`

**Comment by NikitaGvozdilko** [comment]
Try this:
#456
