### ISSUE TITLE
Can't add session features during ARCore initialization in ARSceneView

### ISSUE THREAD

**Issue by Kliuchko** [SceneView/sceneview-android#459]
Hi guys! Am I missing something basic or is there really a bug in the project? How do I add a Session Feature during ARCore initialization if in the ARSceneView class the "sessionFeatures" field looks like this: val sessionFeatures: Set<Session.Feature> = setOf(). So have setOf() ?? Do I understand correctly that there is no way to add a new element to the set or am I missing something very simple?

**Comment by ThomasGorisse** [comment]
You have to add the `ARSceneView` programticaly or use an internal override of it.

**Comment by Kliuchko** [comment]
So obvious, of course. Thank you
