### ISSUE TITLE
disable scale gestures on a 3d model in sceneview

### ISSUE THREAD

**Issue by v01dn3ph1l1m** [SceneView/sceneview-android#474]
val engine = rememberEngine()
        val modelLoader = rememberModelLoader(engine)

        val cameraNode = rememberCameraNode(engine) {
            isScaleEditable = false
        }
        val centerNode = rememberNode(engine)
            .addChildNode(cameraNode)
        val modelInstance = remember { modelLoader.createModelInstance("female_mode.glb") }

        val modelNode = rememberNode {
            ModelNode(
                modelInstance = modelInstance,
                scaleToUnits = 0.4f,
                autoAnimate = false
            )

        }.apply {
            isScaleEditable = false
        }
        
        
                Scene(
            modifier = modifier.fillMaxSize(),
            engine = engine,
            modelLoader = modelLoader,
            cameraNode = cameraNode,
            isOpaque = false,
            childNodes = listOf(centerNode, modelNode),
            onFrame = {
                cameraNode.lookAt(centerNode)
            }
        )

i tried this but didnt work

also tried this

       val onGestureListener = rememberOnGestureListener(
           onScaleBegin = { _, _, _ -> } 
            onScale = { _, _, _ -> } 
        )
        
 I am on version 2.1.1. please help

**Comment by v01dn3ph1l1m** [comment]
@ThomasGorisse would appreciate your help here. I tried setting isScaleEditable on camera, center and model nodes. Nothing works. Maybe i am doing a mistake on my end.

**Comment by ThomasGorisse** [comment]
1. Please avoid mentioning 
2. This is not an Issue but a Discussion 
3. Please learn how to use Compose: you are adding the camera node to the center node on each recomposition 
4. Please follow the 3D development tutorial before asking: you cannot scale a no size Node, even more a Camera
