### ISSUE TITLE
sample-model-viewer, cannot move models onTouch 

### ISSUE THREAD

**Issue by kelvinwatson** [SceneView/sceneview-android#48]
I'm playing with the sample-model-viewer app and I see that touch events are being detected via the `nodeGestureRecognizer` but the models don't move. It seems that the `OnGestureStartedListener`s are not being added and so the touch event doesn't get propagated. 

What is the proper way to ensure touch events like drag and pinch are able to rotate/scale a model in 3D only mode?

**Comment by StevenMOG** [comment]
Support for gestures in 3D and AR will be added with #38 .

**Comment by grassydragon** [comment]
I'm closing this issues since I'll create new issues for specific problems.
