### ISSUE TITLE
sample project is not working

### ISSUE THREAD

**Issue by Hanif-MI** [SceneView/sceneview-android#489]
@ThomasGorisse I was trying to run the sample project but I was getting the error I attached the screenshot of the error.
![image](https://github.com/SceneView/sceneview-android/assets/158578603/e1d30c42-7985-4fa7-986a-973158b850d2)
![image](https://github.com/SceneView/sceneview-android/assets/158578603/36fe77cb-d366-4d50-9d06-8046f6a742f3)

**Comment by dhatriparakal** [comment]
I got the same issue - how did you fix it?
