### ISSUE TITLE
Missing MSAA 4x and too low minScale value on DynamicResolution

### ISSUE THREAD

**Issue by waxmar** [SceneView/sceneview-android#49]
I'm experiencing sawy edges when loading a model in the SceneView. Hardware Acceleration seems to be disabled.

The error occured on an a Galaxy Tab S8

simply added a SceneView like this

```
<io.github.sceneview.SceneView
        android:id="@+id/sceneView"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        />

```
```
sceneView = findViewById(R.id.sceneView)
...
val model = ModelNode()
sceneView.addChild(model)

lifecycleScope.launchWhenCreated {
      model.loadModel(
           context = this@MainActivity,
           glbFileLocation = "models/FiatPunto.glb",
           autoAnimate = false,
           autoScale = true,
           centerOrigin = Position(x = 0.0f, y = 0.0f, z = 0.0f)
      )
}
```
If I print 

`Log.i("SceneView", "HWaccel = " + sceneView.isHardwareAccelerated)`

I recieve `false`.

That's how it looks like (very prominent on the lower end of the windows):
![Screenshot_20220322-160014_HelloSceneView](https://user-images.githubusercontent.com/5690170/159513438-426e3a9f-4e1a-4a08-adaf-79e1c7b107dc.jpg)

**Comment by waxmar** [comment]
Here is a picture of the same Punto model loaded into the sample Filament viewer
![Screenshot_20220408-170238_gltf viewer](https://user-images.githubusercontent.com/5690170/162469624-2a3a4686-9eb1-40e2-9921-d48d101586f0.jpg)
.
As discussed with grassydragon it might be a mipmapping issue not anti-aliasing.

**Comment by waxmar** [comment]
After some more investigation I could reconstruct similar artefacts on the sample-gltf-viewer.
Those are the settings on the sample-gltf-viewer
<img width="656" alt="image" src="https://user-images.githubusercontent.com/5690170/162534935-a2e0d243-783d-4ef2-ae8c-e5eef153c54e.png">

And this is the resulting scene
![Screenshot_20220408-233111_gltf viewer](https://user-images.githubusercontent.com/5690170/162535129-eb4dc864-00b9-4fdd-b925-406d48bbeec4.jpg)

**Comment by waxmar** [comment]
```
var view = sceneView.renderer.filamentView
view.renderQuality = view.renderQuality.apply {
  hdrColorBuffer = View.QualityLevel.MEDIUM
}

view.dynamicResolutionOptions = view.dynamicResolutionOptions.apply {
  enabled = true
  minScale = 0.7f
  maxScale = 0.8f
}

view.multiSampleAntiAliasingOptions = view.multiSampleAntiAliasingOptions.apply {
  enabled = true
  sampleCount = 4
}

view.antiAliasing = View.AntiAliasing.FXAA
```

It turned out the issues was that the default settings of the filamentView were applied and the have MSAA disabled and dynamic screen resolution turned on with some minScale and maxScale values applied by default. The above code makes it possible to access some of the render settings. But things might change with RIP Renderer (?)

**Comment by Veerarma** [comment]
Hi!,
where I can find this sample-gltf-viewer?

**Comment by StevenMOG** [comment]
@Veerarma The sample viewer is part of https://github.com/google/filament . It's included in the releases for desktop platforms.
