### ISSUE TITLE
Incorrect conversion of worldToScreen

### ISSUE THREAD

**Issue by jacobmattsson** [SceneView/sceneview-android#499]
The calculation of the screen Y-coordinate in [View.worldToScreen](https://github.com/SceneView/sceneview-android/blob/ffb2f40500c6d1807d33a028e0a50f9f6630a79f/sceneview/src/main/java/io/github/sceneview/utils/View.kt#L72) seems to be incorrect:

`y *= 1.0f - x`

Instead of being based on the screen _X-coordinate_, the calculation of the screen Y-coordinate ought to be based on the _viewport height_.

**Comment by ThomasGorisse** [comment]
Thanks for the report!
Would you give a hand on the indirect linked #483 so we include the fixes at the same place?
