### ISSUE TITLE
Tap event is called multiple times and outside the node area

### ISSUE THREAD

**Issue by JeromeCHA** [SceneView/sceneview-android#522]
Currently, with the version `2.2.0`, I am facing the issue where hitTest result is returned even if we tapped outside the node.

The behavior can be reproduced with the following simple code.

```Kotlin
val engine = rememberEngine()
val modelLoader = rememberModelLoader(engine)
val testNode = SphereNode(
    engine = engine,
    radius = 1f,
).apply {
    position = Position(z = -5f)
}
Scene(
    modifier = Modifier.fillMaxSize(),
    engine = engine,
    modelLoader = modelLoader,
    childNodes = rememberNodes {
        add(testNode)
    },
    onTouchEvent = { _, result ->
        // check if the tapped node is our testNode
        if (result?.node == testNode) {
            Toast.makeText(this, "Tapped on the node", Toast.LENGTH_SHORT).show()
        }
        false
    }
)
```
or with the gesture listener
```Kotlin
onGestureListener = rememberOnGestureListener(
    onSingleTapConfirmed = { _, node ->
        if (node == testNode) {
            Toast.makeText(this, "Tapped on the node", Toast.LENGTH_SHORT)
                .show()
        }
    }
),
```

Here is the result

![tap_bug](https://github.com/SceneView/sceneview-android/assets/11457628/e5aa8047-0509-43fd-8b9a-f4cea66d741c)

Is there something I am doing wrong? or anything I can do to avoid this?

Edit : Still occurs in `2.2.1`

**Comment by RGregat** [comment]
This is not a solution, but an idea why it happens.
My guess is that the SphereNode is using a bounding box for the collision test. 

![SceneView_SphereNode_Issue](https://github.com/SceneView/sceneview-android/assets/3974162/41d32427-9a2a-4d4b-a4c8-5dc09482d255)

A quick rundown revealed, that a box must be used:
* https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/node/SphereNode.kt#L36
* https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/geometries/Sphere.kt#L51
* https://github.com/SceneView/sceneview-android/blob/main/sceneview/src/main/java/io/github/sceneview/geometries/Geometry.kt#L212

In the collision package there is a class called Sphere.java. Probably a remnant of SceneForm, but you can give it a try.

**Comment by JeromeCHA** [comment]
@RGregat Ohh I see, thank you for the explanation. I hope it can be fixed 🤔 
For a SphereNode, I guess you can check if the tap is outside the sphere area, but for some models (using ModelNode for example) it will be tough to avoid that behavior

| Shape | Result |
|:-:|:-:|
| <img src="https://github.com/SceneView/sceneview-android/assets/11457628/36cb7835-0366-4b74-8b43-7385240d36fc" width="400"> | ![T](https://github.com/SceneView/sceneview-android/assets/11457628/644f8201-5bf0-4e37-95d5-08b9d5a86431) |

sorry for the poor quality of the gif
