### ISSUE TITLE
Crash while running the ar-cloude-anchor sample project. 

### ISSUE THREAD

**Issue by Hanif-MI** [SceneView/sceneview-android#533]
I cloned the whole project. I have run the **ar-cloude-anchor** sample project. 

I am getting this error.
`lateinit property cloudAnchorNode has not been initialized`

 inside the codebase I did not see cloudAnchorNode object is initialized. Can anyone guide/help me on how can I initialize that?

**Comment by Rina196** [comment]
@Hanif-MI, Please check fork: [8d3013c](https://github.com/SceneView/sceneview-android/commit/8d3013c69579b06b481b11b5b4b105d737bd79e0)

Now, you can run the **ar-cloud-anchor** sample project without a crash.

**Comment by Rina196** [comment]
@ThomasGorisse Please check this fork.
