### ISSUE TITLE
VideoNode back in next Release?

### ISSUE THREAD

**Issue by ofreye** [SceneView/sceneview-android#538]
Hello there,

thanks for your work at SceneView, i use it in my current project and i am overall happy with it!

I have to implement Videos in AR and it seems like you are on it to bring the VideoNode back, as i can see in the current main branch.

Now i ask myself if the VideoNode or VideoMaterial is back in the next release and when this release will happen?

Kind regards

**Comment by PepaZapletal** [comment]
it would be great if there were also support for VideoNode

@ofreye you haven't sorted it out yet, have you?

**Comment by ofreye** [comment]
Hi @PepaZapletal, 
i used the ExoPlayerNode from the main branch that is not in the current release yet and modified it a lil bit for my needs. Here is my solution:

ExoPlayerNode.kt
`
import android.content.Context
import android.util.Log
import androidx.annotation.OptIn
import androidx.core.graphics.drawable.toBitmap
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import com.google.android.filament.Engine
import com.google.android.filament.RenderableManager
import mypackage.R
import mypackage.core.materials.VideoMaterial
import dev.romainguy.kotlin.math.normalize
import io.github.sceneview.geometries.Plane
import io.github.sceneview.loaders.MaterialLoader
import io.github.sceneview.math.Direction
import io.github.sceneview.math.Position
import io.github.sceneview.math.Scale
import io.github.sceneview.math.Size
import io.github.sceneview.node.ImageNode
import io.github.sceneview.node.PlaneNode

const val MIN_CONTROLS_WIDTH = 0.012f

class ExoPlayerNode(
    private val videoMaterial: VideoMaterial,
    val exoPlayer: ExoPlayer,
    val showControls: Boolean = true,
    context: Context,
    materialLoader: MaterialLoader,
    size: Size = Size(x = 1f, z = 1f),
    center: Position = Plane.DEFAULT_CENTER,
    normal: Direction = Plane.DEFAULT_NORMAL,
    rotateToNode: Boolean = false,
    builderApply: RenderableManager.Builder.() -> Unit = {},
) : PlaneNode(
    engine = videoMaterial.engine,
    size = if (rotateToNode) Size(x = size.x, y = 0.0f, z = size.y) else size,
    center = if (rotateToNode) Position(x = 0.0f, y = center.z, z = 0.0f) else center,
    normal = normal,
    materialInstance = videoMaterial.instance,
    builderApply = builderApply,
) {
    private var isPlaying = false
    private var isEnded = false

    private var playNode: ImageNode? = null
    private var pauseNode: ImageNode? = null
    private var replayNode: ImageNode? = null


    init {
        exoPlayer.setVideoSurface(videoMaterial.surface)
        if (size == Plane.DEFAULT_SIZE) {
            exoPlayer.doOnVideoSized { player, width, height ->
                if (exoPlayer == player) {
                    updateGeometry(
                        size = normalize(
                            when (rotateToNode) {
                                true -> Size(x = width.toFloat(), y = 0.0f, z = height.toFloat())
                                false -> Size(x = width.toFloat(), y = height.toFloat(), z = 0.0f)
                            },
                        ),
                    )
                }
            }
        }


        val scaleFactorControls = Math.max(size.x * 0.1f, MIN_CONTROLS_WIDTH)

        val CONTROL_SIZE = Size(scaleFactorControls, 0f, scaleFactorControls)

        val controlsPosition = Position(
            x = center.x,
            y = 0.001f,
            z = center.z + (size.z / 2) - CONTROL_SIZE.z/2,
        )


        fun createControlNode(drawableId: Int, action: () -> Unit): ImageNode {
            val bitmap = context.getDrawable(drawableId)?.toBitmap(100, 100)
                ?: throw IllegalArgumentException("Invalid drawable ID: $drawableId")
            return ImageNode(
                materialLoader = materialLoader,
                bitmap = bitmap,
                size = CONTROL_SIZE
            ).apply {
                setPriority(7)
                position = controlsPosition
                onSingleTapUp = {
                    action()
                    true
                }
            }
        }

        if(showControls) {
            playNode = createControlNode(R.drawable.ic_play) {
                Log.i("ExoPlayerNode", "Playing video")
                play()
            }
            addChildNode(playNode!!)

            pauseNode = createControlNode(R.drawable.ic_pause) {
                Log.i("ExoPlayerNode", "Pausing video")
                pause()
            }
            addChildNode(pauseNode!!)

            replayNode = createControlNode(R.drawable.ic_replay) {
                Log.i("ExoPlayerNode", "Replaying video")
                replay()
            }
            addChildNode(replayNode!!)
        }

        setPriority(0)


        exoPlayer.addListener(object : Player.Listener {
            override fun onPlaybackStateChanged(playbackState: Int) {
                isPlaying = playbackState == Player.STATE_READY && exoPlayer.playWhenReady
                isEnded = playbackState == Player.STATE_ENDED
                updateControlsVisibility()
            }
        })
    }

    constructor(
        engine: Engine,
        materialLoader: MaterialLoader,
        exoPlayer: ExoPlayer,
        showControls: Boolean = true,
        context: Context,
        chromaKeyColor: Int? = null,
        rotateToNode: Boolean = false,
        size: Size = Size(x = 1f, z = 1f),
        center: Position = Plane.DEFAULT_CENTER,
        normal: Direction = Plane.DEFAULT_NORMAL,
        builderApply: RenderableManager.Builder.() -> Unit = {},
    ) : this(
        videoMaterial = VideoMaterial(
            engine = engine,
            materialLoader = materialLoader,
            chromaKeyColor = chromaKeyColor,
        ),
        materialLoader = materialLoader,
        context = context,
        exoPlayer = exoPlayer,
        rotateToNode = rotateToNode,
        size = size,
        center = center,
        normal = normal,
        builderApply = builderApply,
        showControls = showControls,
    )

    override fun destroy() {
        Log.d("ExoPlayerNode", "Destroying ExoPlayerNode")
        super.destroy()
        exoPlayer.stop()
        exoPlayer.release()
        videoMaterial.destroy()
    }

    private fun play() {
        exoPlayer.play()
        isPlaying = true
        updateControlsVisibility()
    }

    private fun pause() {
        exoPlayer.pause()
        isPlaying = false
        updateControlsVisibility()
    }

    private fun replay() {
        exoPlayer.seekTo(0)
        exoPlayer.play()
        isEnded = false
        isPlaying = true
        updateControlsVisibility()
    }

    private fun updateControlsVisibility() {
        if(!showControls) return
        playNode.apply {
            isVisible = !isPlaying && !isEnded
            isHittable = !isPlaying && !isEnded
        }
        pauseNode.apply {
            isVisible = isPlaying
            isHittable = isPlaying
        }
        replayNode.apply {
            isVisible = isEnded
            isHittable = isEnded
        }
    }

    override fun updateVisibility() {
        super.updateVisibility()
        when (isVisible) {
            true -> if (exoPlayer.isPlaying.not()) exoPlayer.play()
            else -> if (exoPlayer.isPlaying) exoPlayer.pause()
        }
    }
}

@OptIn(UnstableApi::class)
private fun ExoPlayer.doOnVideoSized(block: (player: ExoPlayer, videoWidth: Int, videoHeight: Int) -> Unit) {
    val videoWidth = videoFormat?.width ?: 0
    val videoHeight = videoFormat?.height ?: 0
    if (videoWidth > 0 && videoHeight > 0) {
        block(this, videoWidth, videoHeight)
    } else {
        addListener(
            object : Player.Listener {
                override fun onPlaybackStateChanged(playbackState: Int) {
                    if (playbackState == Player.STATE_READY) {
                        val width = videoFormat?.width ?: 0
                        val height = videoFormat?.height ?: 0
                        if (width > 0 && height > 0) {
                            block(this@doOnVideoSized, width, height)
                        }
                    }
                }
            },
        )
    }
}
`

VideoMaterial.kt
`
import android.graphics.SurfaceTexture
import android.view.Surface
import com.google.android.filament.Engine
import com.google.android.filament.MaterialInstance
import com.google.android.filament.Stream
import io.github.sceneview.loaders.MaterialLoader
import io.github.sceneview.material.setExternalTexture
import io.github.sceneview.safeDestroyStream
import io.github.sceneview.safeDestroyTexture
import io.github.sceneview.texture.VideoTexture

class VideoMaterial(
    val engine: Engine,
    materialLoader: MaterialLoader,
    chromaKeyColor: Int? = null
) {
    /**
     * Images drawn to the Surface will be made available to the Filament Stream.
     */
    val surfaceTexture = SurfaceTexture(0).apply {
        detachFromGLContext()
    }

    /**
     * The Android surface.
     */
    val surface = Surface(surfaceTexture)

    /**
     * The Filament Stream.
     */
    val stream = Stream.Builder()
        .stream(surfaceTexture)
        .build(engine)

    /**
     * The Filament Texture diffusing the stream.
     */
    val texture = VideoTexture.Builder()
        .stream(stream)
        .build(engine)

    val instance: MaterialInstance = materialLoader.createVideoInstance(texture, chromaKeyColor)

    init {
        instance.setExternalTexture(texture)
    }

    fun destroy() {
        engine.safeDestroyTexture(texture)
        engine.safeDestroyStream(stream)
        surface.release()
        surfaceTexture.release()
    }
}
`

**Comment by PepaZapletal** [comment]
@ofreye Thank you for your help!

I have the basic functionality ready

But I have one more question. I would like the video to play exactly in the area of the detected photo. Do you know how to set it up? I have set rotateToNode = true and I still need to set it there somehow to fit the photo. 

I'd like to end up with something like this: https://www.youtube.com/shorts/yKBTFQTkBj0

I have this page https://ibb.co/k6GXFvf and this image https://ibb.co/H4cwK1J 

And now I'd like to play the video exactly over that image to make it fit. 

Do you know how to do that somehow? Have you solved something like this?

Thanks for the help

**Comment by erikhric** [comment]
Is there a chance that video alpha channel will be translated into transparency of the VideoMaterial? Chromakeying looks awful...
