### ISSUE TITLE
Adjusting the view models radius

### ISSUE THREAD

**Issue by fianik** [SceneView/sceneview-android#565]
My app uses AR based on the ar-model-viewer example. I need to display a very large model, but to see it fully I have to move far away.  ARCore starts to crop it off, showing less information as I move away. I learned this is called Frustum culling. Can it be adjusted to increase the display radius?

**Comment by aleyooop** [comment]
Take a look at `cameraNode.far`

**Comment by fianik** [comment]
Thank you so much! That's exactly what I needed
