### ISSUE TITLE
The collision shape of the ViewNode isn't updated

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#57]
If the `ViewNode` is moved to another location, it still responds to touches where it has been before.

**Comment by ThomasGorisse** [comment]
Is the collision system still needed?
It's quite consuming and will be replaced by the Filament Pick in coming next release (#38). On which @StevenMohr is doing a great work.
Do you see any other reason to keep it in place?
I'm also actually doing a quite big work on moving renderable to model (Filament asset) and this part will be moved since it was inside the Renderer (RIP)

**Comment by grassydragon** [comment]
> Is the collision system still needed?
It's quite consuming and will be replaced by the Filament Pick in coming next release

Will it be possible to interact with `View`s shown by the `ViewNode`?

**Comment by grassydragon** [comment]
I think, if we can project the screen coordinates at the plane of the picked renderable, we should be able to replace the old collision system.
https://github.com/google/filament/blob/df6a100fcba66d9c99328a49d41fe3adecc0165d/android/filament-android/src/main/java/com/google/android/filament/View.java#L1722-L1729

**Comment by ThomasGorisse** [comment]
Great. I'm currently working on the Kotlin-Math project and unproject equation from the Camera so it won't be difficult.
I just hope not making any errors in the equation between the view matrix, the projection and the model one.
- https://github.com/google/filament/blob/df6a100fcba66d9c99328a49d41fe3adecc0165d/android/filament-android/src/main/java/com/google/android/filament/Camera.java#L470-L485
- https://github.com/google/filament/blob/df6a100fcba66d9c99328a49d41fe3adecc0165d/android/filament-android/src/main/java/com/google/android/filament/Camera.java#L517-L531
- https://github.com/google/filament/blob/df6a100fcba66d9c99328a49d41fe3adecc0165d/android/filament-android/src/main/java/com/google/android/filament/Camera.java#L549-L562

I have to admit that I'm a little confused between each one usage.

**Comment by ThomasGorisse** [comment]
If I'm not wrong, it should be:
```kotlin
/**
 * ### Convert a point from world space into screen space.
 *
 * The X value is negative when the point is left of the viewport, between 0 and the width of
 * the [SceneView] when the point is within the viewport, and greater than the width when
 * the point is to the right of the viewport.
 *
 * The Y value is negative when the point is below the viewport, between 0 and the height of
 * the [SceneView] when the point is within the viewport, and greater than the height when
 * the point is above the viewport.
 *
 * The Z value is always 0 since the return value is a 2D coordinate.
 *
 * @param position the point in world space to convert
 * @return a new vector that represents the point in screen-space.
 */
fun worldToScreenPoint(position: Position): Float2 {
    val m = projectionMatrix * viewMatrix
    return (m * Float4(v = position, w = (1.0f / (m * Float4(v = position))).w)).xy
}
```

**Comment by grassydragon** [comment]
> I have to admit that I'm a little confused between each one usage.

The projection matrix transforms the points from the world coordinate system to the OpenGL clip space.
The view matrix transforms the points in the world coordinate system so that they appear to be viewed from the camera point. That means that instead of moving the camera the world is moved in the opposite direction.
The model matrix represents the camera transform similarly to other nodes.

> If I'm not wrong, it should be:

I think it should be:

``` Kotlin
val clipSpacePosition = m * Float4(position, 1f)
clipSpacePosition.xy = clipSpacePosition.xy / clipSpacePosition.w
val screenPosition = Float2(
    (clipSpacePosition.x + 1) / 2 * sceneView.width,
    (1 - clipSpacePosition.y) / 2 * sceneView.height
)
```

**Comment by grassydragon** [comment]
I've solved the original issue by calling the `Node.onTransformChanged()` after the `ViewNode` has been moved.
