### ISSUE TITLE
Transformable ArNode

### ISSUE THREAD

**Issue by xiaoxiaoying** [SceneView/sceneview-android#6]
addChild(TransformableNode)?
Why doesn't it work for me?
DepathNode(context,coroutineScope = lifecycleScope,modelGlbFileLocation = "url",onModelLoaded = {}).apply{

addChild(TransformableNode(arSceneView.nodeGestureRecognizer).apply{
select()
})

}

Please give me a hand

**Comment by ThomasGorisse** [comment]
Linked: https://github.com/SceneView/sceneview-android/issues/29

**Comment by grassydragon** [comment]
I'm closing this issue together with the related one.
