### ISSUE TITLE
Background color on SceneView covers scene

### ISSUE THREAD

**Issue by ninjz** [SceneView/sceneview-android#70]
Previously when using SceneForm, I'm able to have a white background behind all the models being rendered in the scene like this:

```java
sceneView.setBackgroundColor(Color.rgb(255, 255, 255));
sceneView.setTransparent(true);
sceneView.setZOrderOnTop(true);
```

Now when I do this in SceneView, all I get is a blank white view.

**Comment by RGregat** [comment]
What do you want to achieve by setting a background color? If you just want to show a Model without the AR-Context you can take look at this Sample-Project https://github.com/SceneView/sceneview-android/tree/main/samples/model-viewer

**Comment by ninjz** [comment]
I want to get a white background for my scene in place of the black one being rendered here:
![Screenshot 2022-04-22 at 4 46 25 PM](https://user-images.githubusercontent.com/5641860/164654073-1938c90a-7983-4445-bb93-ac6319d9c2e9.png)

My scene is being rendered with this environment:
```kotlin
sceneView.environment = KTXLoader.loadEnvironment(
  context = requireContext(),
  lifecycle = lifecycle,
  iblKtxFileLocation = "environments/default_environment_ibl.ktx",
  skyboxKtxFileLocation = null
)
```

**Comment by ninjz** [comment]
@RGregat any suggestions on how I can achieve this result?

**Comment by ThomasGorisse** [comment]
Since your `environment.skybox` is `null` your layout background or `sceneView` should be applied. If it's not the case, something must be wrong in the latest version.
Please call `sceneView.setBackground` after setting your environment.

**Comment by ThomasGorisse** [comment]
Since your `environment.skybox` is `null` your layout background or `sceneView` should be applied. If it's not the case, something must be wrong in the latest version.
Please call `sceneView.setBackground` after setting your environment.

**Comment by ninjz** [comment]
> your layout background or `sceneView` one should be applied.

Sorry, I'm not quite sure what you mean by this. I am calling `sceneView.setBackgroundColor` after setting the environment. I'm not calling `sceneView.setBackground` because I'm not using a Drawable

**Comment by ninjz** [comment]
Nevermind, I was able to get the background color set by setting:
```java
sceneView.backgroundColor = Color(255f, 255f, 255f, 1f)
```

I guess I was using the wrong Color class which was returning an `Int` instead of the required `Float4` type
