### ISSUE TITLE
How to automatically place multiple models in AR scene

### ISSUE THREAD

**Issue by khmaies5** [SceneView/sceneview-android#75]
I want to be able to add multiple objects on the plane automatically based on a condition i make (walking distance, time, loop...)

I couldn't find documentation for the project and the samples projects are very basic and lacking comments.

**Comment by grassydragon** [comment]
To place an object on a plane you usually do a raycast in ARCore. Maybe the new Geospatial API is better suited for walking: https://developers.google.com/ar/develop/geospatial.
