### ISSUE TITLE
Listening for the node touch events

### ISSUE THREAD

**Issue by LukasPoque** [SceneView/sceneview-android#83]
The onArFrameHitResult method is currently not called, even if the node is clicked by the user. This is really bad because many use cases include the selection of specific modelNodes for interacting with them.

It's pointed out that the bug is known but since there is no ticket (I can't find one) and this problem is the only one preventing me from migrating to this package, I thought a separate ticket is a good way to track the progress on this.

@grassydragon on discord:
> If there is only one node, you can use a workaround from here: https://github.com/SceneView/sceneview-android/blob/main/samples/ar-model-viewer/src/main/java/io/github/sceneview/sample/armodelviewer/MainFragment.kt#L66
Otherwise, we need to fix picking a particular node.

**Comment by LukasPoque** [comment]
If someone can prevent information on where to start I could give it a try.

**Comment by grassydragon** [comment]
Hi!
Thank you for creating an issue!
I plan to start working on it after the 24 of May since I'm currently working on my master's thesis.
The problem that hasn't been solved yet is that Filament picking returns a renderable ID but in case of a model it can be a part of the model and not the root node. We need to find the root node of the model from the renderable ID and match this root node transform to a `ModelNode` in the `SceneView`.
I suppose we can get a parent transform until we find it in the `SceneView.

**Comment by grassydragon** [comment]
Hi @LukasPoque!
I'm sorry I haven't noticed at first but the `onArFrameHitResult` event listener is called when the node is positioned automatically based on where the camera is looking.

However, I will still make sure that the picking system works correctly, there is a listener to detect when a node is touched and add documentation so it is clear how to use it.

**Comment by grassydragon** [comment]
Hi @LukasPoque!
The tap events were fixed and documented in this pull request: https://github.com/SceneView/sceneview-android/pull/96

**Comment by yhishi** [comment]
@grassydragon 
Hi, thanks for everything.
I don't think the tap event on the `ViewNode` has been fixed yet, 
the `ArModelNode` is working.

Add onTap [here](https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/samples/ar-model-viewer/src/main/java/io/github/sceneview/sample/armodelviewer/MainActivity.kt#L141-L161) and onTap was called.

However, the ViewNode's onTap is not called.
```
val textView = TextView(this)
textView.layoutParams =
    LinearLayout.LayoutParams(
        LinearLayout.LayoutParams.MATCH_PARENT,
        LinearLayout.LayoutParams.WRAP_CONTENT
    )
textView.setBackgroundColor(Color.parseColor("#111111"))

textView.text = "test"
textView.textSize = 30F

ViewRenderable.builder()
    .setView(this, textView)
    .build(lifecycle)
    .thenAccept { renderable: ViewRenderable? ->
        val viewNode = ViewNode()
        viewNode.setRenderable(renderable)
        viewNode.onTap = { hitResult, motionEvent ->
            // not called!!
        }
        sceneView.addChild(viewNode)
        sceneView.selectedNode = viewNode
    }
```

The difference is whether [Node's onTap](https://github.com/SceneView/sceneview-android/blob/b7341cced9c0d7ac036d3a039a5c5fa9a8d39c1a/sceneview/src/main/java/io/github/sceneview/node/Node.kt#L498-L501) function is called or not.

**Comment by grassydragon** [comment]
> I don't think the tap event on the ViewNode has been fixed yet

Hi!
Yes, unfortunately, I haven't had a chance to work on it yet.

**Comment by yhishi** [comment]
@grassydragon 
Thanks!
I thought it was fixed [here](https://github.com/SceneView/sceneview-android/pull/96).
Thanks for letting me know.:pray:
