### ISSUE TITLE
how to create a fixed 3d model node on SceneView.

### ISSUE THREAD

**Issue by Arun1947** [SceneView/sceneview-android#85]
ie , 
On background I need a camera view and my 3d model node will be on the screen (as a sticky one), even I changed the camera position the node will be there , camera view will only change..!

This one I have intergrated on sceneForm, but when I moved to sceneView , its not working

pls help.?

**Comment by grassydragon** [comment]
I've provided an answer here: https://github.com/SceneView/sceneview-android/discussions/90
