### ISSUE TITLE
SceneView IS NOT RENDERING GLB FILES CONTAINING KTX2 TEXTURE

### ISSUE THREAD

**Issue by Tomlp14** [SceneView/sceneview-android#86]
Will SceneView support rendering GLB files containing KTX2 texture in the future? Or there is already a way to do so?
I used one of your sample projects to do some testing  (Ar Model Viewer)
With KTX2 texture        |  Without KTX2 texture  (PNG)
:-------------------------:|:-------------------------:
![Screenshot_20220517-164401_AR Model Viewer](https://user-images.githubusercontent.com/8157591/169165390-75ab3173-710d-4f2d-81bc-703fdd854924.jpg))  | ![Screenshot_20220517-164241_AR Model Viewer](https://user-images.githubusercontent.com/8157591/169166047-aa31f851-f930-44a1-a0e9-974a38fea83c.jpg)
With KTX2 texture        |  Without KTX2 texture  (PNG)
:-------------------------:|:-------------------------:
  ![Screenshot_20220518-125718_AR Model Viewer](https://user-images.githubusercontent.com/8157591/169167095-86a54a9d-00b4-4f96-b44f-43e9c0b4058c.jpg)| ![Screenshot_20220518-125902_AR Model Viewer](https://user-images.githubusercontent.com/8157591/169167129-6fddfbce-c728-4dd4-a50a-ac06a97142d9.jpg)

I'm sharing few resource with you guys:
KTX explanation by Khronos group : https://www.khronos.org/ktx/

**Comment by ThomasGorisse** [comment]
Hi,

We are actually using KTX for the environment part only (Indirect light and Skybox)
Mostly for 3D only usage (and for reflections in case of non AR Environmental HDR lighting mode)
This part is completely dependent on Filament new features and I have to say that we didn't investigate it yet.

Would you mind asking it on the [Filament discussions section](https://github.com/google/filament/discussions/) and link it here?

Thanks for the report

**Comment by StevenMOG** [comment]
I just took a look and KTX2 was added in Filament 1.22.1 a few days ago (https://github.com/google/filament/issues/4771). So it should work as soon as we update to this Filament version.

**Comment by ThomasGorisse** [comment]
It's now handled by SceneView > 0.8.0
