### ISSUE TITLE
How to add Multiple STL files in a model 

### ISSUE THREAD

**Issue by umer-aprevoapp** [SceneView/sceneview-android#9]
I am trying to face problem for adding and removing stl files from a model.
What I want to achieve is : 
Add Multiple STL models in a mesh 
can able to remove an STL model on selecting.
please help to update the code and mention here
What I want is referring to this app below: 
https://play.google.com/store/apps/details?id=com.performance.meshview

**Comment by grassydragon** [comment]
Hi!
The library only supports loading glTF models in `.glb` format. If you want to display STL models you need to create your own loader or find an existing library to do that.

**Comment by umer-aprevoapp** [comment]
okay, but if we proceed with .glb format, how can I add multiple glb models in a single mesh.
Also how to remove the specific model from any mesh.

**Comment by grassydragon** [comment]
I'm sorry for not answering earlier. Is it possible to construct a model by correctly placing several smaller `.glb` models and attaching them to a parent node? Then you will be able to detect clicks for individual parts and hide them if needed.

**Comment by umer-aprevoapp** [comment]
can you add the support to add multiple .glb models and attaching them to parent node.
Also if possible can you please add the feature to detect and hide the individual part functionality.
Thanks

**Comment by grassydragon** [comment]
It should be already possible to do. If you need a more stable API, you can use Sceneform for now: https://github.com/SceneView/sceneform-android
